### DISCUSSION TITLE
Cameras out of sync - frame rate issue?

### DISCUSSION THREAD

**Discussion by encryptededdy** [roflcoopter/viseron#1030] [Q&A]
Hello!

First of all, just want to say I'm loving Viseron. I'm not using any of the AI features and just using it for 24/7 recording, however I love the very low resource consumption and slick web UI in this mode.

I'm currently using Viseron with a variety of relatively modern Axis cameras, recording in H.264 on a Raspberry Pi CM5 to a PCIe SSD.

My config is very basic and looks like this for each camera:
```
    m3116lve:
      name: Balcony Wide
      host: 192.168.1.xx
      port: 554
      path: /axis-media/media.amp
      username: xxxx
      password: xxxx
      record_only: true
      recorder:
        continuous_recording: true
        continuous:
          max_size:
            gb: 128
      still_image:
        url: http://192.168.1.xx/axis-cgi/jpg/image.cgi
        username: xxxx
        password: xxxx
        authentication: digest
```

followed by just an entry for each camera under `nvr:`

The issue I'm having is that during playback, my two outdoor cameras seem to be a bit desynced from the indoor cameras. Hopefully the below screenshot demonstrates the issue.

![image](https://github.com/user-attachments/assets/6ae6ce4a-db39-4909-a370-588d87b28592)

You can see the top two cameras (indoor) are within 10s of the indicated timestamp in the timeline view based on the camera's OSD. My other indoor cameras are have a similar 0~10s delay.

However, the two outdoor cameras are running 30s~60s ahead! Sync with the timestamp on the timeline view isn't important to me, however sync amongst the cameras is.

I don't think it's an issue with the cameras themselves, as I've tried putting 3 or 4 cameras up on my computer using `ffplay` and left them running for hours, when I come back they're still within 10s sync of each other.

The main thing that sets the outdoor cameras apart from the indoor ones is I've configured them to drop their shutter speed as low as 1/5s at night, thus also dropping the frame rate to 5fps (down from the normal 30fps in daytime). I'm not sure what assumptions Viseron makes about static frame rate, but perhaps that causes issues?

The other thing is all cameras are configured for dynamic GOP up to 300 frames, so I wonder if the GOP length is getting too long at 5fps for Viseron to handle?

I don't think the host is being overloaded, as noted I'm running with no detectors, and the Pi has <5% CPU usage and <0.2 load. It's also only using ~512MB/8GB of RAM.

Anyway, interested to hear any thoughts anyone may have on what could be the cause of my issue, or anything I could check to help.
