### DISCUSSION TITLE
Please help with getting zones working correctly

### DISCUSSION THREAD

**Discussion by JasonVarney** [roflcoopter/viseron#234] [Q&A]
Hi, I have five cameras with object detection zones setup on four of them, problem is I still seem to get recording triggers with a "person" outside the zones. I can see the zones are aligned correctly in the MJPEG static streams and they even turn green when a person enters them, yet I'm still getting triggers outside the zones, a person inside the house behind a window for instance. I suspect I'm missing something in the config.yaml and there's still some global object detection going on.

Otherwise object detection is working amazingly well, absolutely no false positives, Darknet - YoloV4.

my config.yaml file, no errors in the logs...
[config_yaml.txt](https://github.com/roflcoopter/viseron/files/6708415/config_yaml.txt)

In this screengrab from one of the MJPEG static streams you can see one zone but I still get a recording trigger when someone stands at the window...
![Screen Shot 2021-06-24 at 12 27 39](https://user-images.githubusercontent.com/81792731/123247929-a2df2900-d4e7-11eb-8037-908dc015069e.jpg)

What am I missing? 

Thank you.

**Comment by gniknalu** [comment]
I have a very similar issue. **Thought it was just me** so I've not complained anymore. 

In the other areas, I've tried a mask - didn't work. Tried creating a zone `name: doNotRecord` and, in the  `label: person`  set it to `trigger_recorder: false` but still get person detection and recording.

**Comment by roflcoopter** [comment]
What if you add
```yaml
object_detection:
  labels: []
```

The thing is, the camera inherits the values from the global object detection, which defaults to tracking persons.
So if you dont override it, it will always track persons.
I am away for the weekend, but please let me know if you still have issues with this and i will take a closer look at it asap

**Reply by JasonVarney** [reply]
Thanks, enjoy your weekend.

So I added that to the parent object_detection: as so...

```
object_detection:
  type: darknet
  model_path: /detectors/models/darknet/yolov4.weights
  model_config: /detectors/models/darknet/yolov4.cfg
  model_width: 480
  model_height: 480
  labels: []
```

Unfortunately I'm still getting triggers outside the zone.

Static MJPEG stream:
![Screen Shot 2021-06-25 at 12 02 52](https://user-images.githubusercontent.com/81792731/123409533-907bf280-d5ae-11eb-9575-da88a1499eb6.jpg)

Person detected and recording triggered:
![Screen Shot 2021-06-25 at 12 02 23](https://user-images.githubusercontent.com/81792731/123409722-cae58f80-d5ae-11eb-8398-0250bce77506.jpg)

Relevant log snippet:
```
[2021-06-25 11:49:59] [DEBUG   ] [viseron.nvr.patio.object] - Objects: [{'label': 'person', 'confidence': 0.903, 'rel_width': 0.155, 'rel_height': 0.422, 'rel_x1': 0.635, 'rel_y1': 0.338, 'rel_x2': 0.79, 'rel_y2': 0.76}]
[2021-06-25 11:49:59] [INFO    ] [viseron.recorder.patio  ] - Starting recorder
[2021-06-25 11:49:59] [DEBUG   ] [viseron.cleanup         ] - Pausing segment cleanup
[2021-06-25 11:49:59] [INFO    ] [viseron.nvr.patio       ] - Starting motion detector
[2021-06-25 11:49:59] [DEBUG   ] [viseron.recorder.patio  ] - Creating folder /recordings/2021-06-25/Patio
[2021-06-25 11:49:59] [DEBUG   ] [viseron.recorder.patio  ] - Saving thumbnail in /recordings/thumbnails/Patio
```

The camera settings for that particular camera:

```
cameras:
   - name: Patio
     width: 2304
     height: 1296
     fps: 15
     audio_codec: "aac"
     rtsp_transport: tcp
     mqtt_name: Patio
     host: 192.168.1.201
     port: 8554
     username: xxxxxxx
     password: xxxxxxx
     path: /proxied2
     static_mjpeg_streams:
       patio-debug:
         width: 2304
         height: 1296
         draw_objects: True
         draw_zones: True
     zones:
       - name: PatioZone1
         points:
           - x: 1
             y: 1292
           - x: 8
             y: 954
           - x: 353
             y: 328
           - x: 349
             y: 6
           - x: 1102
             y: 2
           - x: 1080
             y: 303
           - x: 1593
             y: 1286
     object_detection:
         enable: true
         interval: 0.33
         labels:
           - label: person
             require_motion: False
             confidence: 0.9
             height_min: 0.232
             height_max: 0.9999
             width_min: 0.0695
             width_max: 0.434
             trigger_recorder: true
```

I tried adding enable: false to the parent object_detection: but get this in the logs:
```
voluptuous.error.MultipleInvalid: You have disabled object detection globally, but have enabled object detection for camera FrontDoor. This is not supported.
```

For now I'm going to change the parent object_detection: to this...

```
object_detection:
  type: darknet
  model_path: /detectors/models/darknet/yolov4.weights
  model_config: /detectors/models/darknet/yolov4.cfg
  model_width: 480
  model_height: 480
  interval: 21600
  labels:
    - label: person
      require_motion: false
      confidence: 1
      height_min: 0.232
      height_max: 0.9999
      width_min: 0.0695
      width_max: 0.434
      trigger_recorder: false
```
I hope the child camera interval will override the parent, seems like it does from the logs, lets see.

**Reply by gniknalu** [reply]
> ```
> object_detection:
>   labels: []
> ```

After several days of testing, I can confirm that this has significantly reduced **my** "people" false-positives.

**Reply by JasonVarney** [reply]
Hi, could you please post your config.yaml, sensitive info stripped of course, I'd be very interested to see how yours differs to mine?

**Reply by gniknalu** [reply]
> Hi, could you please post your config.yaml, sensitive info stripped of course, I'd be very interested to see how yours differs to mine?

The lines mentioned in my previous comment are 116 and 186. Those are the only two cameras where there have been a lot of false positives. (I don't care to know when something happens on other properties - only on mine.)

```
cameras:
  - name: "BackEast"
    host: !secret *************
    port: !secret *************
    stream_format: rtsp
    username: !secret *************
    password: !secret *************
    path: /*******************************************
    fps: 25
    mqtt_name: camera_back_east
    publish_image: true
    static_mjpeg_streams:
      stream_back_east:
        draw_objects: true
        draw_motion: true
    motion_detection:
      interval: 1
      trigger_detector: false
      threshold: 15
      alpha: 0.6
      max_timeout: 300
      mask:
        - points:
            - x: 1914
              y: 1
            - x: 320
              y: 1
            - x: 320
              y: 148
            - x: 872
              y: 33
            - x: 1914
              y: 174
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9

  - name: "FrontWest"
    host: !secret *************
    port: !secret *************
    stream_format: rtsp
    username: !secret *************
    password: !secret *************
    path: /*******************************************
    mqtt_name: camera_front_west
    publish_image: true
    static_mjpeg_streams:
      stream_front_west:
        draw_objects: true
        draw_motion: true
    zones:
      - name: DrivewayRegion
        points:
          - x: 320
            y: 278
          - x: 1044
            y: 95
          - x: 1331
            y: 93
          - x: 1651
            y: 146
          - x: 1920
            y: 306
          - x: 1920
            y: 751
          - x: 1496
            y: 563
          - x: 1161
            y: 681
          - x: 561
            y: 1071
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: car
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
      - name: doNotRecordFrWest
        points:
          - x: 294
            y: 0
          - x: 1920
            y: 0
          - x: 1920
            y: 206
          - x: 1651
            y: 136
          - x: 1331
            y: 83
          - x: 1044
            y: 85
          - x: 321
            y: 233
        labels:
          - label: person
            confidence: 1
            trigger_recorder: false
    motion_detection:
      interval: .5
      trigger_detector: false
      timeout: true
      max_timeout: 330
    object_detection:
      labels: []
      interval: .5
  - name: "FrontEast"
    host: !secret *************
    port: !secret *************
    stream_format: rtsp
    username: !secret *************
    password: !secret *************
    path: //*******************************************
    mqtt_name: camera_front_east
    publish_image: true
    static_mjpeg_streams:
      stream_front_east:
        draw_objects: true
        draw_motion: true
    zones:
      - name: EDrivewayRegion
        points:
          - x: 670
            y: 1073
          - x: 649
            y: 453
          - x: 926
            y: 422
          - x: 1200
            y: 196
          - x: 1913
            y: 253
          - x: 1913
            y: 498
          - x: 1906
            y: 1073
        labels:
          - label: person
            confidence: 0.9
            trigger_recorder: true
          - label: dog
            confidence: 0.8
            trigger_recorder: true
          - label: cat
            confidence: 0.8
            trigger_recorder: true
      - name: doNotRecordFrEast
        points:
          - x: 1
            y: 1
          - x: 1912
            y: 1
          - x: 1910
            y: 237
          - x: 1609
            y: 196
          - x: 1404
            y: 126
          - x: 1123
            y: 122
          - x: 922
            y: 416
          - x: 1
            y: 455
        labels:
          - label: person
            confidence: 1
            trigger_recorder: false
    motion_detection:
      interval: .5
      trigger_detector: false
      timeout: true
      max_timeout: 330
    object_detection:
      labels: []
      interval: .5
  - name: "BackWest"
    host: !secret *************
    port: !secret *************
    stream_format: rtsp
    username: !secret *************
    password: !secret *************
    path: /*******************************************
    fps: 29
    mqtt_name: camera_back_west
    publish_image: true
    motion_detection:
      interval: 1
      trigger_detector: false
      timeout: true
      max_timeout: 300
    object_detection:
      interval: 1
    logging:
      level: debug

  - name: "Interior1"
    host: !secret *************
    port: !secret *************
    stream_format: rtsp
    username: !secret *************
    password: !secret *************
    path: /*******************************************
    fps: 25
    mqtt_name: camera_interior1
    publish_image: true
    motion_detection:
      interval: 1
      trigger_detector: false
      timeout: true
      max_timeout: 300
    object_detection:
      interval: 1

  - name: "Interior2"
    host: !secret *************
    port: !secret *************
    stream_format: rtsp
    username: !secret *************
    password: !secret *************
    path: /*******************************************
    fps: 25
    mqtt_name: camera_interior2
    publish_image: true
    motion_detection:
      interval: 1
      trigger_detector: false
      timeout: true
      max_timeout: 300
    object_detection:
      interval: 1
```

**Reply by JasonVarney** [reply]
Thank you! 

In my case I've left all the global object detection settings to the parent object_detection: section, no object_detection: per camera and just having zones with one label: person, have not gotten any triggers outside the zones now.

I tried  labels: [] on the parent the and zones still trigger recording I just don't get a nice "person" bounding box drawn,  looked at nvidia-smi, seems to be using about the same resources anyway so will leave as it for the time being.

Really haven't had one case now when a person standing outside the defined zones triggered an object detection recording.

**Comment by JasonVarney** [comment]
Okay, the above changes didn't work, re-read docs carefully, specifically the config fragment for zones and reworked the whole config.yaml, removing per camera object_detection: and and adding a "full frame" zone to the first camera that wasn't using zones leaving me with to the following which seems to be working as expected...

Complete config.yaml for those that may be interested:
```
logging:
  level: debug

motion_detection:
  interval: 21600
  trigger_recorder: False
  trigger_detector: False

object_detection:
  type: darknet
  model_path: /detectors/models/darknet/yolov4.weights
  model_config: /detectors/models/darknet/yolov4.cfg
  model_width: 480
  model_height: 480
  interval: 0.33
  labels:
    - label: person 
      require_motion: false
      confidence: 0.9
      height_min: 0.232
      height_max: 0.9999
      width_min: 0.0695
      width_max: 0.434
      trigger_recorder: false
      
cameras:

   - name: FrontDoor
     width: 2304
     height: 1296
     fps: 15
     audio_codec: "aac"
     rtsp_transport: tcp
     mqtt_name: FrontDoor
     host: 192.168.1.201
     port: 8554
     username: xxxxxx
     password: xxxxxx
     path: /proxied1
     static_mjpeg_streams:
       frontdoor-debug:
         width: 2304
         height: 1296
         draw_objects: True
         draw_zones: True
     zones:
       - name: FrontDoorZone1
         points:
           - x: 1
             y: 1295
           - x: 1
             y: 1
           - x: 2303
             y: 1
           - x: 2303
             y: 1295
         labels:
           - label: person
             require_motion: False
             confidence: 0.9
             height_min: 0.232
             height_max: 0.9999
             width_min: 0.0695
             width_max: 0.434
             trigger_recorder: true

   - name: Patio
     width: 2304
     height: 1296
     fps: 15
     audio_codec: "aac"
     rtsp_transport: tcp
     mqtt_name: Patio
     host: 192.168.1.201
     port: 8554
     username: xxxxxx
     password: xxxxxx
     path: /proxied2
     static_mjpeg_streams:
       patio-debug:
         width: 2304
         height: 1296
         draw_objects: True
         draw_zones: True
     zones:
       - name: PatioZone1
         points:
           - x: 5
             y: 909
           - x: 335
             y: 323
           - x: 347
             y: 2
           - x: 846
             y: 2
           - x: 882
             y: 309
           - x: 1063
             y: 311
           - x: 1570
             y: 1290
           - x: 2
             y: 1294
         labels:
           - label: person
             require_motion: False
             confidence: 0.9
             height_min: 0.232
             height_max: 0.9999
             width_min: 0.0695
             width_max: 0.434
             trigger_recorder: true

   - name: ServiceArea
     width: 2304
     height: 1296
     fps: 15
     audio_codec: "aac"
     rtsp_transport: tcp
     mqtt_name: ServiceArea
     host: 192.168.1.201
     port: 8554
     username: xxxxxx
     password: xxxxxx
     path: /proxied5
     static_mjpeg_streams:
       servicearea-debug:
         width: 2304
         height: 1296
         draw_objects: True
         draw_zones: True
     zones:
       - name: ServiceAreaZone1
         points:
           - x: 791
             y: 1286
           - x: 693
             y: 2
           - x: 2303
             y: 1
           - x: 2301
             y: 1292
         labels:
           - label: person
             require_motion: False
             confidence: 0.9
             height_min: 0.232
             height_max: 0.9999
             width_min: 0.0695
             width_max: 0.434
             trigger_recorder: true

   - name: GarageDoor
     width: 2304
     height: 1296
     fps: 15
     audio_codec: "aac"
     rtsp_transport: tcp
     mqtt_name: GarageDoor
     host: 192.168.1.201
     port: 8554
     username: xxxxxx
     password: xxxxxx
     path: /proxied4
     static_mjpeg_streams:
       garagedoor-debug:
         width: 2304
         height: 1296
         draw_objects: True
         draw_zones: True
     zones:
       - name: GarageDoorZone1
         points:
           - x: 2197
             y: 248
           - x: 1928
             y: 1292
           - x: 512
             y: 1294
           - x: 300
             y: 604
           - x: 752
             y: 509
           - x: 705
             y: 4
         labels:
           - label: person
             require_motion: False
             confidence: 0.9
             height_min: 0.232
             height_max: 0.9999
             width_min: 0.0695
             width_max: 0.434
             trigger_recorder: true

   - name: PoolArea
     width: 2304
     height: 1296
     fps: 15
     audio_codec: "aac"
     mqtt_name: PoolArea
     host: 192.168.1.201
     port: 8554
     username: xxxxxx
     password: xxxxxx
     path: /proxied3
     static_mjpeg_streams:
       poolarea-debug:
         width: 2304
         height: 1296
         draw_objects: True
         draw_zones: True
     zones:
       - name: PoolAreaZone1
         points:
           - x: 636
             y: 1294
           - x: 884
             y: 877
           - x: 738
             y: 43
           - x: 1171
             y: 43
           - x: 1195
             y: 433
           - x: 1447
             y: 431
           - x: 1440
             y: 43
           - x: 2303
             y: 43
           - x: 2303
             y: 1290
         labels:
           - label: person
             require_motion: False
             confidence: 0.9
             height_min: 0.232
             height_max: 0.9999
             width_min: 0.0695
             width_max: 0.434
             trigger_recorder: true

recorder:
  audio_codec: "aac"
  codec: "copy"
  lookback: 6
  timeout: 14
  retain: 14
  folder: /recordings
  segments_folder: /tmp

  thumbnail:
    save_to_disk: true
    send_to_mqtt: true

# MQTT is optional
mqtt:
  broker: 192.168.1.9
  port: 1883
  #username: <if auth is enabled>
  #password: <if auth is enabled>
```

Notice, no object_detection: clause under each camera, the addition of a zone to the one (FrontDoor) camera so they all use zones now and these keys under labels: per camera, I think I misunderstood how the global object detection inherits its per camera overrides from the labels: under zones and I was trying to use object_detection: per camera which wasn't working as expected, also having one camera without a zone caused errors in the logs, also needed a place to insert the keys below, and failure to start, hence adding zones to all cameras:
```
         labels:
           - label: person
             require_motion: False
             confidence: 0.9
             height_min: 0.232
             height_max: 0.9999
             width_min: 0.0695
             width_max: 0.434
             trigger_recorder: true
```


Many thank!
