### DISCUSSION TITLE
Zone --> Labels --> Confidence --> ignored?

### DISCUSSION THREAD

**Discussion by gniknalu** [roflcoopter/viseron#256] [Q&A] [answered]
The system keeps recognizing an outcropping of leaves as a "person" with the "filter: confidence" of 87%.  So, in my Zone, I have Labels which has one for "person" with the "confidence" set to **1**.  But it still alerts on the same area with the same confidence level. Is this being ignored?

this is the area of the config file (with the X/Y omitted)
```
    zones:
      - name: EDrivewayRegion
        points:
.
.
.
.
.
        labels:
          - label: person
            confidence: 1
            trigger_recorder: true
```

**Comment by roflcoopter** [comment]
Could you show the full config? I suspect the default values might give you some trouble...

**Reply by gniknalu** [reply]
> Could you show the full config? I suspect the default values might give you some trouble...

[Here is the current config](https://pastebin.com/Td2N1dzQ)

**Comment by roflcoopter** [comment, marked as answer]
Sorry for the late reply.

Can you try this config for the camera that is giving you trouble?
The problem is that Viseron looks for `person` in the entire field of view by default, which i believe is whats causing you issues.
I think i probably need to change this, its user friendly for someone with a simple setup, but as soon as you start using zones and other advanced features it becomes confusing...

```yaml
  - name: "FrontEast"
    host: !secret fronteast2
    port: !secret fronteast2
    stream_format: rtsp
    username: !secret fronteast2
    password: !secret fronteast2
    path: /cam/***********************
    fps: 25
    mqtt_name: camera_front_east
    publish_image: true
    static_mjpeg_streams:
      stream_front_east:
        draw_objects: true
        draw_motion: true
        draw_zones: true
    zones:
      - name: EDrivewayRegion
        points:
          - x: 959
            y: 1518
          - x: 959
            y: 678
          - x: 1188
            y: 441
          - x: 2092
            y: 441
          - x: 2684
            y: 592
          - x: 2684
            y: 1016
          - x: 2324
            y: 1518
        labels:
          - label: person
            confidence: 1
            trigger_recorder: true
          - label: dog
            confidence: 0.8
            trigger_recorder: true
          - label: cat
            confidence: 0.8
            trigger_recorder: true
    motion_detection:
      interval: .5
      trigger_detector: false
      timeout: true
      max_timeout: 330
    object_detection:
      interval: .5
      labels: []
      mask:
        - points:
          - x: 957
            y: 1515
          - x: 957
            y: 676
          - x: 1186
            y: 438
          - x: 2100
            y: 438
          - x: 2684
            y: 590
          - x: 2684
            y: 1
          - x: 1
            y: 1
          - x: 1
            y: 1515
```

Let me know if it works out or not!
