### DISCUSSION TITLE
Home Assistant Notification

### DISCUSSION THREAD

**Discussion by jasonpstokes** [roflcoopter/viseron#314] [Show and tell]
Here's my Home Assistant notification that displays the snapshot on object detection and then, once the clip finishes recording, adds the clip as an action to view. I'm sure others have done this already - and likely in better ways! - but as I couldn't find something here thought I'd share this to (hopefully) help someone.

Please let me know if something's not clear or right, or if this can be done easier/cleaner/better!! e.g. I tried to use a common script and then a blueprint, but couldn't get the wait_template / wait_for_trigger to work in them... 🤷‍♂️

**config.yaml** in Viseron, to save thumbnails to disk
```yaml
recorder:
  thumbnail:
    save_to_disk: true
```

**docker-compose.yml** - mount Viseron's recording folder into your HA container as /media
```yaml
services:
  home-assistant:
    ...
    volumes:
      - /path/to/docker/viseron/recordings:/media:ro
```

**viseron.yaml** ([HA package](https://www.home-assistant.io/docs/configuration/packages/))
```yaml
sensor:
  - platform: mqtt
    name: "Driveway clip"
    icon: hass:cctv
    state_topic: "viseron/driveway/sensor/status/state"
    value_template: > # Gets the clip filename
      {% if value_json.attributes.last_recording_start %}
        {{value_json.attributes.last_recording_start.split('T')[1].split('.')[0]}}.mp4
      {% else %}
        unavailable
      {% endif %}

# when duplicating for additional cameras, find and replace driveway with your camera name.
automation:
  - id: "viseron_driveway_notification"
    alias: "Viseron Camera Driveway Notification"
    trigger:
      - platform: state
        entity_id: # entity_ids you want notifications for
          - binary_sensor.viseron_driveway_object_detected_dog
          - binary_sensor.viseron_driveway_object_detected_person
        to: 'on'
    condition:
      - "{{ (as_timestamp(now()) - as_timestamp(state_attr('automation.viseron_driveway_notification','last_triggered'))|int(0)) > 300 }}" # only notify once per 5 mins
    variables:
      tag: "{{ as_timestamp(now())|int }}"
      time: "{{ states('sensor.time') }}"
    action:
      - service: notify.notify
        data:
          message: "{{ trigger.entity_id.split('_')[-1]|capitalize }} detected on {{ trigger.entity_id.split('_')[2]|capitalize }} at {{ time }}"
          data:
            tag: "{{ tag }}"
            image: "/media/local/thumbnails/{{trigger.entity_id.split('_')[2]|capitalize}}/latest_thumbnail.jpg"
            channel: 'Motion'
            importance: 'high'
            group: viseron
            notification_icon: "mdi:cctv"
            actions:
            - action: URI
              title: View Snapshot
              uri: "https://your.external.viseron.url/recordings/thumbnails/{{trigger.entity_id.split('_')[2]|capitalize}}/latest_thumbnail.jpg"
      - wait_for_trigger:
        - platform: state
          entity_id: sensor.viseron_driveway_status
          from: "recording"
        timeout:
          minutes: 5
        continue_on_timeout: false
      - delay: 5 # give viseron time to write the file out
      - service: notify.notify
        data:
          message: "{{ trigger.entity_id.split('_')[-1]|capitalize }} detected on {{ trigger.entity_id.split('_')[2]|capitalize }} at {{ time }}"
          data:
            tag: "{{ tag }}"
            image: "/media/local/thumbnails/{{trigger.entity_id.split('_')[2]|capitalize}}/latest_thumbnail.jpg"
            channel: 'Motion'
            importance: 'high'
            group: viseron
            notification_icon: "mdi:cctv"
            actions:
            - action: URI
              title: View Snapshot
              uri: "https://your.external.viseron.url/recordings/thumbnails/{{trigger.entity_id.split('_')[2]|capitalize}}/latest_thumbnail.jpg"
            - action: URI
              title: View Clip
              uri: "https://your.external.viseron.url/recordings/{{states('sensor.date_time_iso').split('T')[0]}}/{{trigger.entity_id.split('_')[2]|capitalize}}/{{states('sensor.driveway_clip')}}"
```

EDIT: updated MQTT sensor so HA doesn't throw errors whilst there is no mqtt camera data.
