### DISCUSSION TITLE
modularize :: How to set camera to debug

### DISCUSSION THREAD

**Discussion by gniknalu** [roflcoopter/viseron#331] [Q&A] [answered]
Rather than having all camera data in in the log when set to debug, how do you set just a single camera to debug?

I tried:
```
       logging:
         level: debug
```

and

```
       logger:
         default_level:
```

At the camera level. Neither worked.

Thank you

**Comment by roflcoopter** [comment, marked as answer]
This is not technically possible any longer.

Would be nice if you could do something like this perhaps:
```yaml
logger:
  default_level: info
  logs:
    viseron.components.ffmpeg.*.camera1: debug # Catch all ffmpeg logs for camera1
```
Or:
```yaml
logger:
  default_level: info
  logs:
    .*.camera1.*: debug # Catch ALL logs for camera1
```

**Reply by gniknalu** [reply]
OK - thank you

**Comment by roflcoopter** [comment]
Fyi, managed to implement this in a pretty simple way now
The logger component now supports this config:
```yaml
logger:
  default_level: info
  cameras:
    camera1: debug
```

That will set all logs containing the name camera1 to debug!
