### DISCUSSION TITLE
modularized :: Deepstack ignores background_subtractor

### DISCUSSION THREAD

**Discussion by gniknalu** [roflcoopter/viseron#336] [Q&A] [answered]
Switched to `deepstack` in hopes of fixing the issues I was having. (Still having similar issues - LOL) Noticed `deepstack` ignores the settings I have for `background_subtractor`. It is alerting on anything in the video defined in `object_detector`

**Comment by roflcoopter** [comment]
Sorry missed this one!
What do you mean ignore? Can you show the config?

**Reply by gniknalu** [reply]
> Sorry missed this one! What do you mean ignore? Can you show the config?

The `background_subtractor` masks aren't being honored. It is detecting anything defined within the camera view.

```
cat config.yaml
ffmpeg:
  camera:
    FrontEast2:
       name: Front_East2
       host: !secret camera_ip_front_east2
       username: !secret camera_us_front_east2
       password: !secret camera_pw_front_east2
       path: /cam/realmonitor?channel=1&subtype=0&proto=Private3
       port: 80
       fps: 29
       recorder:
         idle_timeout: 10
         codec: h264
         filename_pattern: 'FrontE_%Y-%m-%d-%H%M%S'
         lookback: 7
         retain: 90
         thumbnail:
           filename_pattern: 'FrontE_%Y-%m-%d-%H%M%S'
    FrontWest:
       name: Front_West
       host: !secret camera_ip_front_west
       username: !secret camera_us_front_west
       password: !secret camera_pw_front_west
       path: /Streaming/Channels/101?transportmode=unicast&profile=Profile_1
       port: 554
       fps: 25
       recorder:
         idle_timeout: 10
         codec: h264
         filename_pattern: 'FrontW_%Y-%m-%d-%H%M%S'
         lookback: 7
         retain: 90
         thumbnail:
           filename_pattern: 'FrontW_%Y-%m-%d-%H%M%S'

deepstack:
  host: 192.198.0.252
  port: 5000
  object_detector:
    image_width: 1024
    image_height: 1024
    cameras:
      FrontEast2:
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            trigger_recorder: true
            require_motion: true
          - label: car
            trigger_recorder: true
            require_motion: true
      FrontWest:
        fps: 1
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            trigger_recorder: true
            require_motion: true
          - label: car
            trigger_recorder: true
            require_motion: true

background_subtractor:
  motion_detector:
    cameras:
      FrontEast2:
        fps: 1
        mask:
          - coordinates:
              - x: 957
                y: 1515
              - x: 957
                y: 676
              - x: 1186
                y: 438
              - x: 2100
                y: 438
              - x: 2684
                y: 590
              - x: 2684
                y: 1
              - x: 1
                y: 1
              - x: 1
                y: 1515
      FrontWest:
        fps: 1
        mask:
          - coordinates:
              - x: 294
                y: 0
              - x: 1920
                y: 0
              - x: 1920
                y: 206
              - x: 1651
                y: 136
              - x: 1120
                y: 114
              - x: 321
                y: 233
          - coordinates:
              - x: 1
                y: 537
              - x: 1
                y: 1080
              - x: 1920
                y: 1080
              - x: 1920
                y: 810
              - x: 1278
                y: 870
              - x: 526
                y: 1015


nvr:
  FrontEast2:
  FrontWest:

webserver:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_us
  password: !secret mqtt_pw
  client_id: viseron
  home_assistant:

logger:
  default_level: info
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```

**Comment by roflcoopter** [comment, marked as answer]
The one under background_subtractor > motion_detector only affects that motion detector, nothing else.

If you want to mask out objects you need to add the mask to the deepstack component.
Like so:
```yaml
deepstack:
  host: 192.198.0.252
  port: 5000
  object_detector:
    image_width: 1024
    image_height: 1024
    cameras:
      FrontEast2:
        fps: 1
        scan_on_motion_only: false
        mask:
          ...... <Your mask here>
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            trigger_recorder: true
            require_motion: true
          - label: car
            trigger_recorder: true
            require_motion: true
```

Is that what you are after?
