### DISCUSSION TITLE
modularized :: Deepstack vs Darknet

### DISCUSSION THREAD

**Discussion by gniknalu** [roflcoopter/viseron#346] [Q&A]
When I switched from darknet to deepstack a lot of my problems went away. But after the work you did (thank you!) on deepstack, I decided to kick the tires. Download a fresh image, switched my config files around, and fired it up. Did a perimeter walk around the house. First camera detected right away. Second didn't detect. Third didn't either. Below is a screenshot from the 3rd camera. Seems to pick up on something you mentioned in one of the reported issues. Noticed you said, "I added my own "letterbox" resizing" and you were working on the math with the aid of your wonderful spouse. Maybe it's my config or something because this is what I saw on camera 3

![Screenshot_20220509-111657_Chrome](https://user-images.githubusercontent.com/3652809/167456640-25bfcb1a-5949-45f5-ba0b-8db10ad13269.jpg)

Stopped everything, swapped config files to use deepstack and started everything up and now it's working as it was previously.

Is there something wrong with my darknet config?

```
cat config.yaml.darknet.20220502
ffmpeg:
  camera:
    FrontEast2:
       name: Front_East2
       host: !secret camera_ip_front_east2
       username: !secret camera_us_front_east2
       password: !secret camera_pw_front_east2
       path: /xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
       port: 80
       fps: 29
       recorder:
         idle_timeout: 10
         codec: h264
         filename_pattern: 'FrontE_%Y-%m-%d-%H%M%S'
         lookback: 7
         retain: 90
         thumbnail:
           filename_pattern: 'FrontE_%Y-%m-%d-%H%M%S'
    FrontWest:
       name: Front_West
       host: !secret camera_ip_front_west
       username: !secret camera_us_front_west
       password: !secret camera_pw_front_west
       path: /xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
       port: 554
       fps: 25
       recorder:
         idle_timeout: 10
         codec: h264
         filename_pattern: 'FrontW_%Y-%m-%d-%H%M%S'
         lookback: 7
         retain: 90
         thumbnail:
           filename_pattern: 'FrontW_%Y-%m-%d-%H%M%S'
    BackEast:
       name: Back_East
       host: !secret camera_ip_back_east
       username: !secret camera_us_back_east
       password: !secret camera_pw_back_east
       path: /xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
       port: 554
       fps: 25
       recorder:
         idle_timeout: 10
         extension: mkv
         filename_pattern: 'BackE_%Y-%m-%d-%H%M%S'
         lookback: 12
         retain: 90
         thumbnail:
           filename_pattern: 'BackE_%Y-%m-%d-%H%M%S'
darknet:
  object_detector:
    model_path: /detectors/models/darknet/yolov4-csp-x-swish.weights
    model_config: /detectors/models/darknet/yolov4-csp-x-swish.cfg
    cameras:
      FrontEast2:
        fps: 1
        scan_on_motion_only: false
        mask:
          - coordinates:
              - x: 957
                y: 1515
              - x: 957
                y: 676
              - x: 1348
                y: 309
              - x: 1926
                y: 383
              - x: 2684
                y: 590
              - x: 2684
                y: 1
              - x: 1
                y: 1
              - x: 1
                y: 1515
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            trigger_recorder: true
            require_motion: true
          - label: car
            trigger_recorder: true
            require_motion: true
      FrontWest:
        fps: 1
        scan_on_motion_only: false
        mask:
          - coordinates:
              - x: 294
                y: 0
              - x: 1920
                y: 0
              - x: 1920
                y: 206
              - x: 1651
                y: 136
              - x: 1120
                y: 114
              - x: 321
                y: 233
          - coordinates:
              - x: 1
                y: 537
              - x: 1
                y: 1080
              - x: 1920
                y: 1080
              - x: 1920
                y: 810
              - x: 1278
                y: 870
              - x: 526
                y: 1015
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true
          - label: truck
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: car
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
      BackEast:
        fps: 1
        scan_on_motion_only: false
        mask:
          - coordinates:
              - x: 1
                y: 753
              - x: 1
                y: 1
              - x: 2592
                y: 1
              - x: 2592
                y: 491
              - x: 1332
                y: 405
              - x: 643
                y: 482
        labels:
          - label: person
            trigger_recorder: true
          - label: dog
            trigger_recorder: true
          - label: cat
            trigger_recorder: true

background_subtractor:
  motion_detector:
    cameras:
      FrontEast2:
        fps: 1
        mask:
          - coordinates:
              - x: 957
                y: 1515
              - x: 957
                y: 676
              - x: 1348
                y: 309
              - x: 1926
                y: 383
              - x: 2684
                y: 590
              - x: 2684
                y: 1
              - x: 1
                y: 1
              - x: 1
                y: 1515
      FrontWest:
        fps: 1
        mask:
          - coordinates:
              - x: 294
                y: 0
              - x: 1920
                y: 0
              - x: 1920
                y: 206
              - x: 1651
                y: 136
              - x: 1120
                y: 114
              - x: 321
                y: 233
          - coordinates:
              - x: 1
                y: 537
              - x: 1
                y: 1080
              - x: 1920
                y: 1080
              - x: 1920
                y: 810
              - x: 1278
                y: 870
              - x: 526
                y: 1015
      BackEast:
        fps: 1
        mask:
          - coordinates:
              - x: 1
                y: 753
              - x: 1
                y: 1
              - x: 2592
                y: 1
              - x: 2592
                y: 491
              - x: 1332
                y: 405
              - x: 643
                y: 482


nvr:
  FrontEast2:
  FrontWest:
  BackEast:

webserver:

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_us
  password: !secret mqtt_pw
  client_id: viseron
  home_assistant:

logger:
  default_level: info
  logs:
    viseron.components.data_stream: info
    viseron.components.background_subtractor: info
    viseron.components.mog2: info
```

Thank you!
