### DISCUSSION TITLE
rotate ?

### DISCUSSION THREAD

**Discussion by gofaster** [roflcoopter/viseron#423] [Q&A] [answered]
Hi, I have a rotation question.  Actually 2 questions but they may be related.

1. I have a Pi-based camera that is working fine with Viseron at 1640x928 resolution.  I physically rotated the camera 90 degrees to have more vertical  Field-of-View than horizontal.   As the hw h264 encoder in the Pi has a height limit of 1080, I can't rotate the source stream (without cropping) before sending it to Viseron.   Since persons etc. now appear horizontal in Viseron, the object detectors don't work too well.  The frontend's MJEPG dynamic stream display is also on it's side, as are recordings etc.
Is it possible to have an option in the camera component to rotate the input stream before sending it  down the pipeline?
I'm using the gstreamer component and see that it has a `rotate element` [https://gstreamer.freedesktop.org/documentation/geometrictransform/rotate.html](url)
I think this is the ffmpeg equivalent [http://ffmpeg.org/ffmpeg-filters.html#transpose-1](url)
Possible new config parameter `source_rotate: 90   # × π/180 = radians, constrain to 0,90,180,270 degrees`

2.   While looking through the documentation for an existing solution to #1, I looked at `mjpeg_streams' static streams which has a `rotate:` parameter.  However I believe this would only affect the the video after the detector(s) pipeline.  But in trying this, I could not get anything to display.
Documentation [https://viseron.netlify.app/components-explorer/components/gstreamer](url)

config -
```
    camera_3:  # This value has to be unique across all cameras IMX219
      name: Door
      host: !secret camera_3_host
      port: !secret camera_3_port
      stream_format: rtsp
      path: /unicast
      width: 1640
      height: 928
      fps: 15
      codec: h264
      username: !secret camera_3_username
      password: !secret camera_3_password
      recorder:
#        idle_timeout: 10
#        lookback: 10
        retain: 3
      mjpeg_streams:
        door_stream:
          rotate: 90
          draw_objects: true
```

`http://xxx.xxx.xxx.xxx:8888/camera_3/static-mjpeg-streams/door_stream` did not display anything except the frontend background.

I saw this [https://github.com/roflcoopter/viseron/issues/23#issuecomment-762649661](url)  but
`http://xxx.xxx.xxx.xxx:8888/camera_3/door_stream` did not work either.

What is the correct URL construct?

Thanks for listening.

**Comment by roflcoopter** [comment]
It is quite easy to accomplish actually, you need to add video_filters to both the camera and recorder.

```yaml
ffmpeg:
  camera:
    camera_1:
    ....
      video_filters:   # These filters rotate the images processed by Viseron
        - transpose=2
      recorder:
        video_filters:   # These filters rotate the recorded video
          - transpose=2
```          

This is how transpose works in FFmpeg:
```yaml
0 = 90CounterCLockwise and Vertical Flip (default)
1 = 90Clockwise
2 = 90CounterClockwise
3 = 90Clockwise and Vertical Flip
```

Will add this to the FFmpeg docs as well

**Reply by gofaster** [reply]
That is great.  I missed that part.  Is it the same for the GStreamer component; which is what I'm using on the Jetson Nano?
Something like this?

```
gstreamer:
  camera:
    camera_3:
    ....
      video_filters:   # These filters rotate the images processed by Viseron
        - "rotate angle=1.5708"    # 90 degrees clockwise in radians
      recorder:
        video_filters:   # These filters rotate the recorded video, currently performed by FFmpeg
          - transpose=1  # 90 degrees clockwise

**Reply by roflcoopter** [reply]
Ahh sorry no that is for FFmpeg only.
I added a new config option for gstreamer to support this, `output_element`, its in `dev` now.

You can use it like this:

```yaml
gstreamer:
  camera:
    camera_3:
    ....
      width: xxxx
      height: yyyy
      output_element: "videoflip method=clockwise !" # Rotate images processed by Viseron
      recorder:
        video_filters:   # These filters rotate the recorded video, currently performed by FFmpeg
          - transpose=1  # 90 degrees clockwise
```          

Also added a section on rotating video to both FFmpeg and GStreamer docs
