### DISCUSSION TITLE
403 on refresh or direct navigation to a recordings folder

### DISCUSSION THREAD

**Discussion by netcivil** [roflcoopter/viseron#458] [General]
first off, I have to say I LOVE this program.  It's exactly what I've been looking for to use my rtsp camera.  Simple NVR, love it, don't ever stop maintaining it! :)

I have run into something I haven't found an answer to in here, and perhaps this behavior is intentional or can't be changed, but if I'm on a recording folder for a date on one of my cameras, via the browser (in my case Chrome), if I refresh I get a 403.  Also if I directly navigate to the URL http://<server>:8888/recordings/basement/2023-01-13, same thing.

In the logs I see this...

```
[2023-01-13 11:26:07] [WARNING ] [tornado.general] - 403 GET /recordings/frontwalk/2023-01-13 (192.168.86.152): 2023-01-13 is not a file
[2023-01-13 11:26:07] [WARNING ] [tornado.access] - 403 GET /recordings/frontwalk/2023-01-13 (192.168.86.152) 2.16ms
[2023-01-13 11:27:45] [WARNING ] [tornado.general] - 403 GET /recordings/frontwalk/2023-01-13/ (192.168.86.152): 2023-01-13/ is not a file
[2023-01-13 11:27:45] [WARNING ] [tornado.access] - 403 GET /recordings/frontwalk/2023-01-13/ (192.168.86.152) 1.32ms

```

I know it's a nitpick, but wanted to ask.

Thanks again, great work, it's like you read my mind on how I'd want a DIY PVR to work!

**Comment by roflcoopter** [comment]
Great to hear you like Viseron!

I noticed this as well the other day, it's because of the regex that serves recordings isn't strict enough, which causes this issues.

I have fixed this locally along with the ability to delete recordings and also refresh automatically when new recordings are available. Will probably be done tomorrow and push it to the `dev` tag.

If you come up with any features you would like to see, please let me know!

**Reply by netcivil** [reply]
well since you asked... ;)

and maybe there is a way, but right now after mog2 detects motion, a 10s countdown timer starts in the ffmpeg recorder, it doesn't seem to wait for the motion to stop.

I've upped the recorder timeout to 30s, but it would be cool of mog2 could send the record stop after the motion stopped, then have the countdown start, and if motion were detected again before the timer elapsed, the recorder would just keep recording/'reset'.

I've attached my config if that helps at all.

Thanks again!

```
logger:
  default_level: info
  logs:
    viseron.components.ffmpeg: info
    viseron.components.mog2: debug
## Start by adding some cameras
ffmpeg:
  camera:
    driveway:
      name: driveway  
      host: 10.10.10.158
      port: 554
      path: /h264Preview_01_main
      username: **
      password: **
      height: 720
      fps: 30
      recorder:
        idle_timeout: 30
      substream:
        path: /h264Preview_01_sub
        stream_format: rtsp
        port: 554
        width: 640
        fps: 15
    frontdoor:
      name: frontdoor  
      host: 10.10.10.164
      port: 554
      path: /h264Preview_01_main
      username: **
      password: **
      height: 720
      fps: 30
      recorder:
        idle_timeout: 30
      substream:
        path: /h264Preview_01_sub
        stream_format: rtsp
        port: 554
        width: 640
        fps: 15
    frontwalk:
      name: frontwalk
      host: 10.10.10.165
      port: 554
      path: /h264Preview_01_main
      username: **
      password: **
      height: 720
      fps: 30
      recorder:
        idle_timeout: 30
      substream:
        path: /h264Preview_01_sub
        stream_format: rtsp
        port: 554
        width: 640
        fps: 15
    garage:
      name: garage
      host: 10.10.10.162
      port: 554
      path: /h264Preview_01_main
      username: **
      password: **
      height: 720
      fps: 30
      recorder:
        idle_timeout: 30
      substream:
        path: /h264Preview_01_sub
        stream_format: rtsp
        port: 554
        width: 640
        fps: 15
    basement:
      name: basement
      host: 10.10.10.182
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      username: **
      password: **
      height: 720
      fps: 30
      recorder:
        idle_timeout: 30
      substream:
        path: /cam/realmonitor?channel=1&subtype=1
        stream_format: rtsp
        port: 554
        height: 480
        fps: 15
mog2:
  motion_detector:
    cameras:
      driveway:
        max_recorder_keepalive: 0
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        area: 0.004
      frontdoor:
        max_recorder_keepalive: 0
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        area: 0.004
      frontwalk:
        max_recorder_keepalive: 0
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        area: 0.004
      garage:
        max_recorder_keepalive: 0
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        area: 0.004
      basement:
        max_recorder_keepalive: 0
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        area: 0.004
nvr:
  driveway:
  frontdoor:
  frontwalk:
  garage:
  basement:
```

**Reply by roflcoopter** [reply]
It is due to your `max_recorder_keepalive: 0` i think.
Zero actually means zero seconds of keepalive, not infinite.

Try setting it to something higher. 
I should probably allow zero to be infinite tho.

**Reply by netcivil** [reply]
wow, that was it, too obvious, embarrassing, I'm setup so perfectly now thank you!

**Reply by netcivil** [reply]
[garage.txt](https://github.com/roflcoopter/viseron/files/10415675/garage.txt)

well maybe a spoke a bit too soon, if you look at the attached you'll see for a while it's working as expected, waiting to get a motion stopped to begin the end recording countdown, but after a while it's counting down as soon as motion is detected.

Lemme know if I can provide any more config data, logs, etc.  Or if you want me to test/try anything, look at anything, .....

**Reply by roflcoopter** [reply]
Will take a close look tomorrow!

**Reply by roflcoopter** [reply]
Fixed the motion detection issue (i think) in #460 and the 403 issue in #459 

They are both in the `dev` tag now, can you try them out?

**Reply by netcivil** [reply]
awesome, loading up now and will update you on how it goes, thanks!

**Reply by netcivil** [reply]
looks like the recording still isn't waiting for the motion stopping.  If you look at the logs you'll see the stopping in 9 happening right after the recording starts.

Just to confirm, I'm using the dev tag
CONTAINER ID   IMAGE                           COMMAND              CREATED        STATUS        PORTS                                                           NAMES
2ef52c5986f5   roflcoopter/viseron:dev         "/init"              21 hours ago   Up 21 hours   0.0.0.0:8888->8888/tcp, :::8888->8888/tcp                       viseron

I attached logs and my config file for reference.

Totally not a big deal, for now I can just capture like 30-60s videos on motion.

[vlogs.txt](https://github.com/roflcoopter/viseron/files/10426205/vlogs.txt)

[config.txt](https://github.com/roflcoopter/viseron/files/10426247/config.txt)


thank you again!

**Reply by roflcoopter** [reply]
Could you enable debug logging for one of the cameras and attach that log?
You can do it like this:
```yaml
logger:
  cameras:
    frontwalk: debug
```
