### DISCUSSION TITLE
NVR options

### DISCUSSION THREAD

**Discussion by NikitaKorneev** [roflcoopter/viseron#474] [Ideas]
I would like to humbly request for some features:
- Archive limit option. It would be nice to limit amount of days that are stored.
- Logs. It would be nice to have ability to view logs somewhere in web GUI. 

Thank you for the solution. Nothing less than a game changer for me!

**Comment by roflcoopter** [comment]
Great to hear you like Viseron!

You can set `retention` under the `recorder` for each camera. There you specify the number of days that you want to keep.

Regarding the logs, can you open a feature request issue for that?

**Reply by NikitaKorneev** [reply]
@roflcoopter did I miss the retention option in documentation? I cannot find it there...

Regarding the logs - no problem! THX for reply!

**Reply by roflcoopter** [reply]
My bad, its `retain` not `retention`

As an example: 
```yaml
ffmpeg:
  camera:
    camera_one:
      name: Camera 1
      host: 192.168.XX.X
      port: 554
      path: /Streaming/Channels/101/
      username: !secret camera_one_user
      password: !secret camera_one_pass
      recorder:
        retain: 30 # Will retain recordings for 30 days
```
