### DISCUSSION TITLE
Help adding Wyze camera (wyze_mini) modded

### DISCUSSION THREAD

**Discussion by bizwog** [roflcoopter/viseron#479] [Q&A]
I'm new to sysadmin/docker stuff. I see the config file example with ffmpeg option and a series of camera parameters to set below. I've got the Wyze camera setup for RTSP. Can someone provide a configuration example, please? 

My other question is where do I look for the documentation that covers the possible configuration parameters such as stream type, etc. 

Help is appreciated.

**Comment by roflcoopter** [comment]
You can find the documentation for FFmpeg [here](https://viseron.netlify.app/components-explorer/components/ffmpeg)

You can start out small by just specifying the minimum, something like this:
```yaml
ffmpeg:
  camera:
    camera_one:
      name: Camera 1
      host: <IP or hostname>
      port: <port>
      path: <path to stream, for my Hikvision camera it is /Streaming/Channels/101/>
      username: <username>
      password: <password>
```
