### DISCUSSION TITLE
How to get notifications on Home Assistant

### DISCUSSION THREAD

**Discussion by molohov** [roflcoopter/viseron#490] [Q&A]
I'm very new to HA and MQTT. Could an expert share how they enable MQTT on Viseron, then connect it to HA and then have HA create notifications on events?

**Comment by devarda** [comment]
I thought something like this would have worked in the configuration.yaml but sadly I'm not seeing any notifications at Home Assistant
 
```yaml
notifications:
  homeassistant:
    host: https://XXXXX
    token: XXXXX
    events:
      - motion
      - object_detected
```

I'm able to bash into the docker container and trigger a notification without a problem:

```bash
curl -X POST -H "Authorization: Bearer XXXXXXX" \
     -H "Content-Type: application/json" \
     -d '{"message": "Test notification from Viseron Docker"}' \
     https://XXXXX/api/services/notify/notify
```

And I'm able to see recordings as a person walks - it triggers the recording on motion.

Please advise.
