### DISCUSSION TITLE
[Help]  Error while decoding stream

### DISCUSSION THREAD

**Discussion by frompani** [roflcoopter/viseron#510] [Q&A] [answered]
hi all. 

I'm trying to get it working with just 1 unifi camera  but I get  this error : 

`[2023-03-10 22:43:01] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - Error while decoding stream #0:1: Resource temporarily unavailable`
``

my docker command : 
`sudo docker run --rm   --privileged   -v /media/removable/nvr/recordings:/recordings   -v /media/removable/nvr/config:/config   -v /etc/localtime:/etc/localtime:ro   -v /dev/bus/usb:/dev/bus/usb   -v /opt/vc/lib:/opt/vc/lib   -p 9999:8888   --name viseron   --device=/dev/video10:/dev/video10   --device=/dev/video11:/dev/video11   --device=/dev/video12:/dev/video12   --device /dev/bus/usb:/dev/bus/usb   roflcoopter/viseron:latest`

config.yaml: 
```

`## Start by adding some cameras
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Ingresso
      host: 192.168.10.93
      port: 554
      path: /s1
      username: 
      password:

```

`
working RSTP Url : rtsp://192.168.10.93:554/s1

 running on Rpi4 - 8GB  
any suggestion? 

thanks , 
fab

**Comment by roflcoopter** [comment]
Hardware acceleration seems broken on the rpi4, there is a work around here: https://github.com/roflcoopter/viseron/issues/477#issuecomment-1412094550

**Reply by frompani** [reply]
it works , thank's
fab

**Comment by roflcoopter** [comment]
I upgraded ffmpeg to 5.1.2 which potentially fixes this issue.

It is now built into the `dev` tag, do you have the time to try if that works for you without setting the codec in your config?

**Reply by frompani** [reply]
got this : 


[2023-03-12 22:16:30] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - Unrecognized option 'stimeout'.                   
[2023-03-12 22:16:30] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - Error splitting the argument list: Option not found
[2023-03-12 22:16:30] [ERROR   ] [viseron.components.ffmpeg.camera.camera_1] - FFmpeg process has exited                         

docker command : 
`sudo docker run --rm   --privileged   -v /media/removable/nvr/recordings:/recordings   -v /media/removable/nvr/config:/config   -v /etc/localtime:/etc/localtime:ro   -v /dev/bus/usb:/dev/bus/usb   -v /opt/vc/lib:/opt/vc/lib   -p 9999:8888   --name viseron   --device=/dev/video10:/dev/video10   --device=/dev/video11:/dev/video11   --device=/dev/video12:/dev/video12   --device /dev/bus/usb:/dev/bus/usb   roflcoopter/viseron:dev`

`

config:
`
```

ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Ingresso
      host: 192.168.10.93
      port: 554
      path: /s0
      username: 
      password:
      codec: h264
      fps: 5
      substream:
        port: 554
        path: /s2
        codec: h264
      recorder:
        retain: 7
mog2:
  motion_detector:
    cameras:
      camera_1:
        trigger_recorder: true
        fps: 1
        threshold: 15



nvr:
  camera_1:  # Run NVR for camera_1
`


```


thank's 
fab
