### DISCUSSION TITLE
Setup of domain camera for component ffmpeg with identifier camera_1 failed

### DISCUSSION THREAD

**Discussion by educatedpolarbear** [roflcoopter/viseron#527] [Q&A] [answered]
Hi, the app is not working, and the configuration file looks like this:
```
# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.

## Start by adding some cameras
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: cam1
      host: 14.241.197.248
      port: 2006
      path: rtsp://iocldg:iocldg123123@14.241.197.248:2006/cam/realmonitor?channel=1&subtype=0
      username: 
      password: 

    # camera_2:  # This value has to be unique across all cameras
    #   name: <camera friendly name>
    #   host: <ip address or hostname of camera>
    #   port: <port the camera listens on>
    #   path: <URL path to the stream>
    #   username: <if auth is enabled>
    #   password: <if auth is enabled>


## Then add an object detector
darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

      # camera_2:  # Attach detector to the configured camera_2 above
      #   fps: 1
      #   labels:
      #     - label: person
      #       confidence: 0.75
      #       trigger_recorder: true


## You can also use motion detection
mog2:
  motion_detector:
    cameras:
      # camera_2:  # Attach detector to the configured camera_2 above
      #   fps: 1


## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1
  # camera_2:  # Run NVR for camera_2

# Now you can restart Viseron and you should be good to go!
```

And the error looks like this:

```
2023-03-18 12:47:17 [2023-03-18 05:47:17] [ERROR   ] [viseron.components] - Setup of domain camera for component ffmpeg with identifier camera_1 failed
2023-03-18 12:47:17 [2023-03-18 05:47:17] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain object_detector for component darknet. Failed dependencies: ['domain: camera, identifier: camera_1']
2023-03-18 12:47:17 [2023-03-18 05:47:17] [ERROR   ] [viseron.components] - Unable to setup dependencies for domain nvr for component nvr. Failed dependencies: ['domain: camera, identifier: camera_1', 'domain: object_detector, identifier: camera_1']
```

**Comment by roflcoopter** [comment, marked as answer]
In `path` you should only specify teh path, not the full URL, like this:

```yaml
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: cam1
      host: 14.241.197.248
      port: 2006
      path: /cam/realmonitor?channel=1&subtype=0
      username: iocldg
      password: iocldg123123
```

Viseron will use the information you provide and construct the full URL
