### DISCUSSION TITLE
Services starts but never detects or records anything - help!

### DISCUSSION THREAD

**Discussion by parkroyk** [roflcoopter/viseron#589] [Q&A] [answered]
I'm new and this is my first installation. The service starts and I can see my cameras in the UI. But so far I can't get it to record or detect objects or motions. It's running via docker-compose in a VM with Tesla P4 passthrough. I confirm Viseron is using the GPU and root owns the recordings folder.

Please help!

**docker-compose.yml**

```
version: "2.4"

services:
  viseron:
    image: roflcoopter/amd64-cuda-viseron:latest
    container_name: viseron
    volumes:
      - ./recordings:/recordings
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    tmpfs:
      - /tmp
    runtime: nvidia
```

**config.yaml**

```
ffmpeg:
  camera:
    camera_1:    
      name: Living Room
      host: !secret camera_1_ip
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      username: !secret camera_1_username
      password: !secret camera_1_password
      codec: hevc_cuvid
      audio_codec: aac
      width: 3072
      height: 2048
      fps: 15
      substream:
        path: /cam/realmonitor?channel=1&subtype=1
        port: 554
        codec: hevc_cuvid
        audio_codec: aac
        width: 704
        height: 480
        fps: 15
      mjpeg_streams:
        camera_1_stream:
          width: 3072
          height: 2048
      recorder:
        lookback: 2
        idle_timeout: 3
        retain: 7
        segments_folder: /tmp


    camera_2:    
      name: Basement
      host: !secret camera_2_ip
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      username: !secret camera_2_username
      password: !secret camera_2_password
      codec: hevc_cuvid
      audio_codec: aac
      width: 3072
      height: 2048
      fps: 15
      substream:
        path: /cam/realmonitor?channel=1&subtype=1
        port: 554
        codec: hevc_cuvid
        audio_codec: aac
        width: 704
        height: 480
        fps: 15
      mjpeg_streams:
        camera_2_stream:
          width: 3072
          height: 2048
      recorder:
        lookback: 2
        idle_timeout: 3
        retain: 7
        segments_folder: /tmp

    camera_3:    
      name: Kitchen
      host: !secret camera_3_ip
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      username: !secret camera_3_username
      password: !secret camera_3_password
      codec: hevc_cuvid
      audio_codec: aac
      width: 3072
      height: 2048
      fps: 15
      substream:
        path: /cam/realmonitor?channel=1&subtype=1
        port: 554
        codec: hevc_cuvid
        audio_codec: aac
        width: 704
        height: 480
        fps: 15
      mjpeg_streams:
        camera_3_stream:
          width: 3072
          height: 2048
      recorder:
        lookback: 2
        idle_timeout: 3
        retain: 7
        segments_folder: /tmp

    camera_4:    
      name: Front
      host: !secret camera_4_ip
      port: 554
      path: /live/main
      username: !secret camera_4_username
      password: !secret camera_4_password
      codec: hevc_cuvid
      audio_codec: aac
      width: 3840
      height: 2160
      fps: 15
      substream:
        path: /live/sub
        port: 554
        codec: hevc_cuvid
        audio_codec: aac
        width: 704
        height: 576
        fps: 15
      mjpeg_streams:
        camera_4_stream:
          width: 3840
          height: 2160
      recorder:
        lookback: 2
        idle_timeout: 3
        retain: 7
        segments_folder: /tmp

    camera_5:    
      name: Backyard
      host: !secret camera_5_ip
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      username: !secret camera_5_username
      password: !secret camera_5_password
      codec: hevc_cuvid
      audio_codec: aac
      width: 3072
      height: 2048
      fps: 15
      substream:
        path: /cam/realmonitor?channel=1&subtype=1
        port: 554
        codec: hevc_cuvid
        audio_codec: aac
        width: 704
        height: 480
        fps: 15
      mjpeg_streams:
        camera_5_stream:
          width: 3072
          height: 2048
      recorder:
        lookback: 2
        idle_timeout: 3
        retain: 7
        segments_folder: /tmp

    camera_6:    
      name: Dining Room
      host: !secret camera_6_ip
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif
      username: !secret camera_6_username
      password: !secret camera_6_password
      codec: hevc_cuvid
      audio_codec: aac
      width: 2592
      height: 1944
      fps: 15
      substream:
        path: /cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
        port: 554
        codec: hevc_cuvid
        audio_codec: aac
        width: 704
        height: 480
        fps: 15
      mjpeg_streams:
        camera_6_stream:
          width: 2592
          height: 1944
      recorder:
        lookback: 2
        idle_timeout: 3
        retain: 7
        segments_folder: /tmp


darknet:
  object_detector:
    half_precision: true
    
    cameras:
      camera_1:
        labels:
          - label: person, cat
            confidence: 0.7
            require_motion: true

      camera_2:
        labels:
          - label: person, cat
            confidence: 0.7
            require_motion: true

      camera_3:
        labels:
          - label: person, cat
            confidence: 0.7
            require_motion: true

      camera_4:
        labels:
          - label: person, car, cat, dog, bicycle, truck
            confidence: 0.7
            require_motion: true

      camera_5:
        labels:
          - label: person, cat
            confidence: 0.7
            require_motion: true

      camera_6:
        labels:
          - label: person, cat
            confidence: 0.7
            require_motion: true

mog2:
  motion_detector:
    cameras:
      camera_1:
      camera_2:
      camera_3:
      camera_4:
        detect_shadows: true
      camera_5:
        detect_shadows: true
      camera_6:

nvr:
  camera_1:
  camera_2:
  camera_3:
  camera_4:
  camera_5:
  camera_6:
```

**Comment by roflcoopter** [comment, marked as answer]
You need to split up your labels like this:
```yaml 
darknet:
  object_detector:
    half_precision: true
    
    cameras:
      camera_1:
        labels:
          - label: person
            confidence: 0.7
            require_motion: true
          - label: cat
            confidence: 0.7
            require_motion: true
```

I would also suggest trying without require motion as a start
