### DISCUSSION TITLE
Weird 4k camera issue

### DISCUSSION THREAD

**Discussion by parkroyk** [roflcoopter/viseron#590] [Q&A] [answered]
So all my non-4k cameras are working, objects being detected, recording clips, etc.

The only camera that's currently not working is my [4k camera](https://www.aliexpress.com/item/4000909939548.html?spm=a2g0s.12269583.0.0.d5fb151cyLklha). For some reason, its snapshot/stream looks much taller than 1.78 aspect (3840x2160); more like 4:3 aspect. I am suspecting perhaps the object detector can't recognize person or car (or anything for that matter) as things look stretched vertically?

I tried setting the width & height to 3840x2160 but didn't make a difference. What else can I try?

```
ffmpeg:
  camera:
    1_camera_4:
      name: Front (cam4)
      host: !secret camera_4_ip
      port: 554
      path: /live/main
      username: !secret camera_4_username
      password: !secret camera_4_password
      codec: hevc_cuvid
      audio_codec: aac
      width: 3840
      height: 2160
      fps: 15
      substream:
        path: /live/sub
        port: 554
        codec: hevc_cuvid
        audio_codec: aac
        width: 704
        height: 576
        fps: 15
      recorder:
        lookback: 2
        idle_timeout: 3
        retain: 7
        filename_pattern: cam4_%Y%m%d_%H%M%S
        segments_folder: /tmp
        thumbnail:
          filename_pattern: cam4_%Y%m%d_%H%M%S
```
