### DISCUSSION TITLE
No segments were found - No Recordings

### DISCUSSION THREAD

**Discussion by dadhatdaniel** [roflcoopter/viseron#677] [General]
Hey guys I feel like I've spent the last 2 days digging through documentations/issues and discussions posts but I'm not able to fix this. I'm pretty sure I've tried every configuration option available to try and get this working correctly. I see the components triggering successfully as well as the recording start but nothing ever gets recorded and the only real error i see is below. It is taking pictures when an object is detected - i have several pictures of myself on the back porch but no recordings? I feel like I could have some stupid configuration set up that might be blocking but I have 0 clue how to identify what I did wrong. Any help at this point would be greatly appreciated

docker-compose
```
version: "2.4"
services:
  camera-nvr:
    image: roflcoopter/amd64-cuda-viseron:latest
    volumes:
      - /mnt/user/appdata/media/recordings:/recordings
      - /mnt/user/appdata/lightfootcloud/infra/Viseron:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    runtime: nvidia
```
```
[2023-09-23 16:11:30] [INFO    ] [viseron.components.nvr.nvr.camera_backporch] - Stopping recording in: 0
[2023-09-23 16:11:30] [INFO    ] [viseron.components.ffmpeg.recorder.camera_backporch] - Stopping recorder
[2023-09-23 16:11:30] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_backporch] - Pausing segment cleanup
[2023-09-23 16:11:30] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_backporch] - Concatenating segments
[2023-09-23 16:11:30] [DEBUG   ] [viseron.states] - Setting state of binary_sensor.camera_backporch_recorder to state: off, attributes {'name': 'Back Porch Recorder', 'domain': 'binary_sensor', 'start_time': datetime.datetime(2023, 9, 23, 16, 11, 18, 298875), 'start_timestamp': 1695499878.298875, 'end_time': datetime.datetime(2023, 9, 23, 16, 11, 30, 252061), 'end_timestamp': 1695499890.252061, 'date': '2023-09-23', 'path': '/recordings/camera_backporch/2023-09-23/16:11:18.mp4', 'filename': '16:11:18.mp4', 'thumbnail_path': '/recordings/camera_backporch/2023-09-23/16:11:18.jpg', 'objects': [<viseron.domains.object_detector.detected_object.DetectedObject object at 0x14814e1cc7f0>]}
[2023-09-23 16:11:30] [DEBUG   ] [viseron.states] - Setting state of sensor.camera_backporch_operation_state to state: scanning_for_objects, attributes {'name': 'Back Porch Operation State', 'domain': 'sensor'}
[2023-09-23 16:11:30] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_backporch] - Segment information: {}
[2023-09-23 16:11:30] [ERROR   ] [viseron.components.ffmpeg.recorder.camera_backporch] - No segments were found
[2023-09-23 16:11:30] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_backporch] - Resuming segment cleanup
```

```
# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.

## Start by adding some cameras
ffmpeg:
  camera:

    camera_backporch:  # This value has to be unique across all cameras
      name: Back Porch
      host: 192.168.50.184 
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 30
      path:  /VideoInput/1/h264/1
      username: xxxx
      password: xxxx
      video_filters: # Rotate the frames processed by Viseron
        - transpose=2
      width: 720 # Width of the rotated video = height of the camera
      height: 1280 # Height of the rotated video = width of the camera
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac
        segments_folder: /segments
        video_filters: # Rotate the recorded videos
         - transpose=2
        
    camera_backstairs:  # This value has to be unique across all cameras
      name: Back Stairs
      host: 192.168.50.152 
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 30
      path:  /VideoInput/1/h264/1
      username: xxxx
      password: xxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac


    camera_driveway:  # This value has to be unique across all cameras
      name: Driveway
      host: 192.168.50.159
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 30
      path:  /VideoInput/1/h264/1
      username: xxxxxx
      password: xxxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac


    camera_frontporch:  # This value has to be unique across all cameras
      name: Front Porch
      host: 192.168.50.98
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 30
      path:  /VideoInput/1/h264/1
      username: xxxxx
      password: xxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac

darknet:
  object_detector:
    cameras:

      camera_backporch:  # Attach detector to the configured camera_backporch above
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
          - label: dog
            confidence: 0.65
            trigger_recorder: true

      camera_backstairs:  # Attach detector to the configured camera_backstairs above
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
          - label: dog
            confidence: 0.65
            trigger_recorder: false

      camera_driveway:  # Attach detector to the configured camera_backstairs above
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
          - label: dog
            confidence: 0.65
            trigger_recorder: true

      camera_frontporch:  # Attach detector to the configured camera_backstairs above
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
          - label: dog
            confidence: 0.65
            trigger_recorder: true

#mog2:
#  motion_detector:

 #   cameras:
 #     camera_backporch:  # Attach detector to the configured camera_backstairs above
#        fps: 1
#        trigger_recorder: true
#        recorder_keepalive: true
#        max_recorder_keepalive: 300
      
#      camera_backstairs:  # Attach detector to the configured camera_backstairs above
#        fps: 1
#        trigger_recorder: true
#        recorder_keepalive: true
#        max_recorder_keepalive: 300

#      camera_driveway:  # Attach detector to the configured camera_backstairs above
#        fps: 1
#        trigger_recorder: true
#        recorder_keepalive: true
#        max_recorder_keepalive: 300

#      camera_frontporch:  # Attach detector to the configured camera_backstairs above
#        fps: 1
#        trigger_recorder: true
#        recorder_keepalive: true
#        max_recorder_keepalive: 300

nvr:

  camera_backporch: {}
  camera_backstairs: {}
  camera_driveway: {}
  camera_frontporch: {}

# Now you can restart Viseron and you should be good to go!
##Debugging and logs
logger:
  default_level: debug
  logs:
     viseron.components.ffmpeg: debug
     viseron.components.nvr: debug
     viseron.components.darknet: debug
    #viseron.components.mog2: debug
  cameras:
    camera_backporch: debug
    camera_backstairs: debug
    camera_driveway: debug
    camera_frontporch: debug
```

**Comment by dadhatdaniel** [comment]
This seems to record but in very short segments and no object detection? I know I'm not the brightest but what am I missing here?

```
# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.
#testing

## Start by adding some cameras
ffmpeg:
  camera:

    camera_backporch:  # This value has to be unique across all cameras
      name: Back Porch
      host: 192.168.50.184
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxx
      video_filters: # Rotate the frames processed by Viseron
        - transpose=2
      width: 720 # Width of the rotated video = height of the camera
      height: 1280 # Height of the rotated video = width of the camera
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac
        segments_folder: /segments
        video_filters: # Rotate the recorded videos
         - transpose=2

    camera_backstairs:  # This value has to be unique across all cameras
      name: Back Stairs
      host: 192.168.50.152
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac

    camera_driveway:  # This value has to be unique across all cameras
      name: Driveway
      host: 192.168.50.159
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac

    camera_frontporch:  # This value has to be unique across all cameras
      name: Front Porch
      host: 192.168.50.98
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac


mog2:
  motion_detector:
    
    cameras:
      camera_backporch:  # Attach detector to the configured camera_backstairs above
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        max_recorder_keepalive: 300

      camera_backstairs:  # Attach detector to the configured camera_backstairs above
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        max_recorder_keepalive: 300

      camera_driveway:  # Attach detector to the configured camera_backstairs above
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        max_recorder_keepalive: 300

      camera_frontporch:  # Attach detector to the configured camera_backstairs above
        fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        max_recorder_keepalive: 300

darknet:
  object_detector:
    
    cameras:
      camera_backporch:  # Attach detector to the configured camera_backporch above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
          - label: dog
          - label: cat
            confidence: 0.5
            trigger_recorder: true

      camera_backstairs:  # Attach detector to the configured camera_backstairs above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
          - label: dog
          - label: cat
            confidence: 0.5
            trigger_recorder: true

      camera_driveway:  # Attach detector to the configured camera_backstairs above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
          - label: dog
          - label: cat
            confidence: 0.5
            trigger_recorder: true

      camera_frontporch:  # Attach detector to the configured camera_backstairs above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
          - label: dog
          - label: cat
            confidence: 0.5
            trigger_recorder: true


nvr:

  camera_backporch:
  camera_backstairs: 
  camera_driveway: 
  camera_frontporch:
  
logger:
  default_level: info

  logs:
     viseron.components.ffmpeg: info
     viseron.components.nvr: info
     viseron.components.darknet: info
     viseron.components.mog2: info
  cameras:
    camera_backporch: info
    camera_backstairs: info
    camera_driveway: info
    camera_frontporch: info
  ```

**Comment by dadhatdaniel** [comment]
or like this?

```
## Start by adding some cameras
ffmpeg:
  camera:

    camera_backporch:  # This value has to be unique across all cameras
      name: Back Porch
      host: 192.168.50.184
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxxx
      video_filters: # Rotate the frames processed by Viseron
        - transpose=2
      width: 720 # Width of the rotated video = height of the camera
      height: 1280 # Height of the rotated video = width of the camera
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac
        segments_folder: /segments
        video_filters: # Rotate the recorded videos
         - transpose=2
    camera_backstairs:  # This value has to be unique across all cameras
      name: Back Stairs
      host: 192.168.50.152
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac
        segments_folder: /segments
    camera_driveway:  # This value has to be unique across all cameras
      name: Driveway
      host: 192.168.50.159
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac
        segments_folder: /segments
    camera_frontporch:  # This value has to be unique across all cameras
      name: Front Porch
      host: 192.168.50.98
      port: 554
      protocol: rtsp
      stream_format: rtsp
      fps: 25
      path: /VideoInput/1/h264/1
      username: admin
      password: xxxx
      recorder:
        lookback: 10
        retain: 60
        idle_timeout: 10
        codec: hevc_nvenc
        audio_codec: aac
        segments_folder: /segments

darknet:
  object_detector:

    cameras:
      camera_backporch:  # Attach detector to the configured camera_backporch above
        fps: 15
        scan_on_motion_only: false
        labels:
          - label: person
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: cat
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
          - label: dog
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
      camera_backstairs:  # Attach detector to the configured camera_backstairs above
        fps: 15
        labels:
          - label: person
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: cat
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
          - label: dog
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
      camera_driveway:  # Attach detector to the configured camera_backstairs above
        fps: 15
        labels:
          - label: person
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: cat
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
          - label: dog
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
      camera_frontporch:  # Attach detector to the configured camera_backstairs above
        fps: 15
        labels:
          - label: person
            confidence: 0.8
            trigger_recorder: true
            require_motion: true
          - label: cat
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
          - label: dog
            confidence: 0.7
            trigger_recorder: true
            require_motion: true

mog2:
  motion_detector:
    
    cameras:
      camera_backporch:  # Attach detector to the configured camera_backstairs above
        fps: 15
      camera_backstairs:  # Attach detector to the configured camera_backstairs above
        fps: 15
      camera_driveway:  # Attach detector to the configured camera_backstairs above
        fps: 15
      camera_frontporch:  # Attach detector to the configured camera_backstairs above
        fps: 15

nvr:
  camera_backporch:
  camera_backstairs: 
  camera_driveway: 
  camera_frontporch:
  
logger:
  default_level: info

  logs:
     viseron.components.ffmpeg: info
     viseron.components.nvr: info
     viseron.components.darknet: info
     viseron.components.mog2: info
  cameras:
    camera_backporch: info
    camera_backstairs: info
    camera_driveway: info
    camera_frontporch: info
    
```
man idk at this point I'm just trying to get it to record on object + motion
