### DISCUSSION TITLE
startup errors

### DISCUSSION THREAD

**Discussion by coderunway** [roflcoopter/viseron#691] [Q&A]
I suddenly started getting this error, while starting up Viseron Docker image in the error logs and its not detecting any camera. The same setup was working.. I also checked that I CAN access the camera stream via VLC RTSP url at 554 port. 

**ERROR from logs**

`[2023-12-10 03:41:10] [ERROR   ] [viseron.components.ffmpeg.stream.camera_4] - Retrying None in 2.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 15s. 
[2023-12-10 03:41:10] [ERROR   ] [viseron.components.ffmpeg.stream.camera_4] - Retrying None in 2.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 15s.
[2023-12-10 03:52:03] [ERROR   ] [viseron.components.ffmpeg.stream.camera_4] - [tcp @ 0x55ab0ecb5c80] Connection to tcp://192.168.1.xxx:554?timeout=0 failed: Connection timed out
`

**CONFIG YAML** 

```
# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.

## Start by adding some cameras
ffmpeg:
  camera:
    camera_3:  # This value has to be unique across all cameras
      name: Living Room
      host: 192.168.1.xxx # (MASKED private data)
      port: 554
      path: /stream1
      username: username1
      password: password1
      fps: 6
      recorder:
        lookback: 5
        idle_timeout: 5
        codec: h264
        retain: 40

    camera_4:  # This value has to be unique across all cameras
      name: Guest Room
      host: 192.168.1.xxx  # (MASKED private data)
      port: 554
      path: /stream1
      username: username2 
      password: password2
      fps: 6
      recorder:
        lookback: 5
        idle_timeout: 5
        codec: h264
        retain: 40

## Then add an object detector
# darknet:
#   object_detector:
#     cameras:
#       camera_1:  # Attach detector to the configured camera_1 above
#         fps: 1
#         scan_on_motion_only: true  # Scan for objects even when there is no motion
#         labels:
#           - label: person
#             confidence: 0.75
#             trigger_recorder: true

      # camera_2:  # Attach detector to the configured camera_2 above
      #   fps: 1
      #   labels:
      #     - label: person
      #       confidence: 0.75
      #       trigger_recorder: true


## You can also use motion detection
mog2:
  motion_detector:
    cameras:
      camera_3:  # Attach detector to the configured camera_2 above
              fps: 1
              trigger_recorder: true
      camera_4:  # Attach detector to the configured camera_2 above
              fps: 1
              trigger_recorder: true


## To tie everything together we need to configure one more component.
nvr:
  # camera_1:  # Run NVR for camera_1
  camera_3:  # Run NVR for camera_3
  camera_4:  # Run NVR for camera_4
```
