### DISCUSSION TITLE
Amcrest RTSP connection Error

### DISCUSSION THREAD

**Discussion by Evlmoonkey** [roflcoopter/viseron#712] [Q&A]
Entering in what I assume is the correct information based on component documentation etc. and receiving the following error.

**FFprobe could not connect to stream. Output: {'error': {'code': -99, 'string': 'Cannot assign requested address'}}**

Added the configuration below, just added items as secrets etc. but otherwise out of the box config. 

```
# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.

## Start by adding some cameras
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: garage
      host: !secret garage_ip
      port: !secret port
      path: !secret path
      username: !secret username
      password: !secret password

    camera_2:  # This value has to be unique across all cameras
      name: <camera friendly name>
      host: <ip address or hostname of camera>
      port: <port the camera listens on>
      path: <URL path to the stream>
      username: <if auth is enabled>
      password: <if auth is enabled>


## Then add an object detector
darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

      camera_2:  # Attach detector to the configured camera_2 above
        fps: 1
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true


## You can also use motion detection
mog2:
  motion_detector:
    cameras:
      camera_2:  # Attach detector to the configured camera_2 above
        fps: 1


## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1
  camera_2:  # Run NVR for camera_2

# Now you can restart Viseron and you should be good to go!
```
Any assistance would be appreciated.
