### DISCUSSION TITLE
Smoothing out MQTT Object Detection Sensors

### DISCUSSION THREAD

**Discussion by w-marco** [roflcoopter/viseron#743] [Q&A]
So I integrated Viseron into HomeAssistant using the MQTT component.
There's a sensor now called "object detected". However, since objects often are detected, then fall under the confidence threshold for a moment, then are picked up again, the sensor changes its state multiple times a second.

For example, when a person is in front of my door camera, the sensor changes from on to off and vice versa like 5 times a second, as sometimes the Coral is only 59% instead of 60% sure which is my threshold to avoid false recordings.

Is there a way, to make the MQTT Sensor more smooth? Ideally, it should stay at object detected on for e.g. 5 seconds and only turn off after a cooldown where there was no object detected. 

PS: Sidenote, I saw mentioned somewhere the thumbnail in the events tab as well as in the MQTT thumbnail sensor should have the object detection bounding boxes applied, but for me, they're clean. Has that been removed, do I need to enable the boxes for the thumbnails somewhere?

**Comment by roflcoopter** [comment]
No way to do that as of now unfortunately, will implement in a future release!

Regarding the bounding boxes, they should be there.
You don't happen to trigger recordings on motion? If so then there are no bounding boxes

**Reply by w-marco** [reply]
Thanks for the quick reply! 
I would love implementation of smoothing out the MQTT sensor to improve notification behavior and such.

Regarding the boxes, I do not trigger with motion, but just with objects. See a relevant part of my config here:

```
mog2:
  motion_detector:
    cameras:
      cam1:
        trigger_recorder: false
        fps: 4
        recorder_keepalive: true
        max_recorder_keepalive: 60
        area: 0.2
        threshold: 100
        width: 640
        height: 480
```

```
edgetpu:
  object_detector:
    device: pci
    cameras:
      cam1:
        fps: 4
        scan_on_motion_only: true
        zones:
          - name: zone1
            coordinates:
              - x: 0
                y: 0
              - x: 244
                y: 0
              - x: 0
                y: 410
            labels:
              - label: car
                confidence: 0.7
                require_motion: true
                trigger_recorder: true
              - label: bicycle
                confidence: 0.7
                trigger_recorder: true
              - label: motorcycle
                confidence: 0.7
                trigger_recorder: true
          - name: zone2
            coordinates:
              - x: 0
                y: 480
              - x: 640
                y: 480
              - x: 640
                y: 0
              - x: 244
                y: 0
              - x: 0
                y: 410
            labels:
              - label: person
                confidence: 0.6
                trigger_recorder: true
                store_interval: 10
              - label: umbrella
                confidence: 0.6
                trigger_recorder: true
                store_interval: 10
              - label: hat
                confidence: 0.6
                trigger_recorder: true
                store_interval: 10
              - label: bicycle
                confidence: 0.7
                trigger_recorder: true
              - label: motorcycle
                confidence: 0.7
                trigger_recorder: true
              - label: car
                confidence: 0.7
                trigger_recorder: true
                require_motion: true
```
