### DISCUSSION TITLE
OPENCL and VAAPI setup

### DISCUSSION THREAD

**Discussion by ceewanna** [roflcoopter/viseron#804] [General]
In my setup in debian linux, I have tried the followings.
1. Intel CPU integrated graphics: it can detect opencl. (device /dev/dri) but I don't see any vaapi used.
2. AMD CPU with Nvidia graphic cards: it can detect CUDA. (NVIDIA Docker is deprecated so NVIDIA Container Toolkit was used.)
3. AMDCPU integrated graphics: nothing available eventhough I had opencl and vaapi installed and linux command can detect its presence. Any extra settings need to be done?

Note: In viseron document, it says. 
VAAPI hardware acceleration support is built into every amd64 container.
To utilize it you need to add --device /dev/dri to your docker command.
I have added above line but so far I have never seen VAAPI used in the log.

**Comment by bsyomov** [comment]
In a CUDA container, to use VAAPI, you must use raw_command or hwaccel_args.
Example from my config(CUDA container, Intel iGPU via VAAPI for transcode):

```
      recorder:
        segments_folder: /tmp/cam1
        retain: 30
        idle_timeout: 30
        lookback: 15
        codec: hevc_vaapi
        hwaccel_args:
          - -hwaccel
          - vaapi
          - -hwaccel_device
          - /dev/dri/renderD128
          - -hwaccel_output_format
          - vaapi

```
