### DISCUSSION TITLE
substream being used as main stream and main as substream?

### DISCUSSION THREAD

**Discussion by phanosp** [roflcoopter/viseron#848] [General]
Hi I am very new to viseron so please excuse me if I am doing something wrong. 

After my NVR died last week I was looking for alternatives and I came across the viseron software that I find very interesting and promising. 

I have configure into viseron 7 outdoor cameras but I was looking to reduce the cpu load so after reading the documentation I created for each camera the corresponding substream. I run the substream of each camera from within vlc to make sure the path was correct and then set it up into the configuration of the viseron and restart it.

For one camera the configuration is the following:

 

> camera_3:  # This value has to be unique across all cameras
>       name: Front Door
>       host: 192.168.1.183
>       port: 554
>       path: /user=*******_password=*******_channel=1_stream=0.sdp?real_stream
>       fps: 30
>       substream:
>         port: 554
>         path: /user=******_password=********_channel=1_stream=1.sdp?real_stream
>         fps: 1

But after I notice that the live video and record that happened was of the substream and not of the main stream. The resolution of both the live view and recording is lower (640x480) and even the frames of the video are very low, ~1-2.

![Snapshot_2024-12-04_14-04-13](https://github.com/user-attachments/assets/248ffb85-37d1-4242-814e-c16cd0640297)

According to what I read in the documentation (https://viseron.netlify.app/components-explorer/components/ffmpeg#substream) I was under the impression that the main stream will be used for live view and recording and the substream for motion detection.

Am I doing something wrong or is this a bug?

Thanks

mpc

**Comment by roflcoopter** [comment]
The live view uses the substream, the live streams are pretty bad right now. Essentially they are what Viseron "sees".

But the recordings should definitely be high res.
Are you absolutely sure that the recorded videos are of the substream?

Could you enable debug logging and restart Viseron?
```yaml
logger:
  default_level: debug
```

Seeing your full config wrapped in triple backticks would help as well

**Reply by phanosp** [reply]
If I understand correctly live streams are designed to use the substream and there is nothing I can do to change this correct?

The resolution of the record is 640 x 480 which is different of the resolution 1920 x 1080 which I get when I enter the url of the main path in VLC

I will enable debug and sent it here when I am home. Can you please let me know where the debug log is so I can sent to you?

I will also sent you the full config file

PS I am not sure if you notice but the main path and sub stream path are different in my config above. Is this how it supposed to work? I though that I use the 1080p path in main and in substream I use a lower resolution but maybe I misunderstood.

**Reply by roflcoopter** [reply]
> If I understand correctly live streams are designed to use the substream and there is nothing I can do to change this correct?

Correct, this will be improved in the near future



> I will enable debug and sent it here when I am home. Can you please let me know where the debug log is so I can sent to you?

You need to extract the logs from Docker somehow. Next release will have a log file for convenience



> PS I am not sure if you notice but the main path and sub stream path are different in my config above. Is this how it supposed to work? I though that I use the 1080p path in main and in substream I use a lower resolution but maybe I misunderstood.

Yes that is correct. The low res stream should be under `substream`

**Reply by phanosp** [reply]
thanks @roflcoopter ,

i was able to get to work. I understand now that the substream is being used for live view and detect and the main stream for recording which is best like this.

**Comment by phanosp** [comment]
Hi @roflcoopter this is my configuration.

```
ffmpeg:
  camera:
    camera_1:  
      name: Front Garage
      host: 192.168.XX.XX
      port: 554
      path: /stream0
      username: *******
      password: *******
      fps: 30
      substream:
        port: 554
        path: /channel=0&stream=1.sdp?real_stream
        fps: 1

    camera_2: 
      name: Kitchen
      host: 192.168.XX.XX
      port: 554
      path: /user=*******_password=*******_channel=1_stream=0.sdp?real_stream
      username: *******
      password: *******
      fps: 30
      substream:
        port: 554
        path: /user=*******_password=*******_channel=1_stream=1.sdp?real_stream
        fps: 1
      
    camera_3: 
      name: Front Door
      host: 192.168.XX.XX
      port: 554
      path: /user=*******_password=*******_channel=1_stream=0.sdp?real_stream
      username: *******
      password: *******
      fps: 30
      substream:
        port: 554
        path: /user=*******_password=*******_channel=1_stream=1.sdp?real_stream
        fps: 1

    camera_4:  
      name: Front View Left
      host: 192.168.XX.XX
      port: 554
      path: /user=*******_password=*******_channel=1_stream=0.sdp?real_stream
      username: *******
      password: *******
      fps: 30
      substream:
        port: 554
        path: /user=*******_password=*******_channel=1_stream=1.sdp?real_stream
        fps: 1

    camera_5:  ras
      name: Front View
      host: 192.168.XX.XX
      port: 554
      path: /user=*******_password=*******_channel=1_stream=0.sdp?real_stream
      username: *******
      password: *******
      fps: 30
      substream:
        port: 554
        path: /user=*******_password=*******_channel=1_stream=1.sdp?real_stream
        fps: 1

    camera_6: 
      name: Garage Back
      host: 192.168.XX.XX
      port: 554
      path: /stream1
      username: *******
      password: *******
      fps: 30
      substream:
        port: 554
        path: /stream0
        fps: 1

    camera_7:  
      name: Kitchen First Floor
      host: 192.168.XX.XX
      port: 554
      path: /stream1
      username: ******
      password: ********
      fps: 30
      substream:
        port: 554
        path: /stream0
        fps: 1

logger:
  default_level: debug
  
## You can also use motion detection
mog2:
  motion_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_2 above
        fps: 1
        trigger_recorder: true
      camera_2:  # Attach detector to the configured camera_2 above
        fps: 1
        trigger_recorder: true
      camera_3:  # Attach detector to the configured camera_2 above
        fps: 1
        trigger_recorder: true
      camera_4:  # Attach detector to the configured camera_2 above
        fps: 1
        trigger_recorder: true
      camera_5:  # Attach detector to the configured camera_2 above
        fps: 1
        trigger_recorder: true
      camera_6:  # Attach detector to the configured camera_2 above
        fps: 1
        trigger_recorder: true
      camera_7:  # Attach detector to the configured camera_2 above
        fps: 1
        trigger_recorder: true

## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1
  camera_2:  # Run NVR for camera_2
  camera_3:  # Run NVR for camera_3
  camera_4:  # Run NVR for camera_4
  camera_5:  # Run NVR for camera_5
  camera_6:  # Run NVR for camera_6
  camera_7:  # Run NVR for camera_7
```
