### DISCUSSION TITLE
Navigating events - expectations

### DISCUSSION THREAD

**Discussion by john-** [roflcoopter/viseron#957] [Q&A]
*Update:* I see now I have 10 continuous recording limit but have almost 40gb in segments directory.  I am going to increase that config and then see if that addresses my question.

I am seeing a couple things I do not understand with regards to event clips and navigating the UI.  This will focus on one of those things.

I am using Viseron (3.0.0 - 9865c8c) and trying to understand when I should expect to see a recording when I click on an event.

If I click on the event with timestamp 07:49:22 AM the video plays on the left.  

However, for the event with timestamp 06:37:29 AM when I click on the event there is a screenshot only.  No video plays.  This is the case for some of the events but not all: No video plays just a screenshot appears on the left.

![image](https://github.com/user-attachments/assets/55f024b7-3365-44e2-8f5d-bd31402189f5)

There is an event_clip for the one at 06:37:29 AM and it plays with vlc:
```
-rw-r--r--. 1 root root  5295702 Mar 28 06:37 06:37:29.mp4
```

I don't think the event_clips are used for videos selected on the EVENTS navigator but thought I would mention it.

config.yaml:
```
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: backyard_1
      host: !secret camera_1_host
      port: 554
      path: /axis-media/media.amp
      username: !secret camera_1_username
      password: !secret camera_1_password
      #stream_format: mjpeg
      fps: 16
      recorder:
        idle_timeout: 1
        codec: h264
        create_event_clip: true

mog2:
  motion_detector:
    cameras:
      camera_1:
        trigger_event_recording: true
        threshold: 6
        area: 0.02
        fps: 1
        mask:
          - coordinates:
         - coordinates:
             [coordinates snipped for brevity]

codeprojectai:
  host: penter.slotcar.prv
  port: 32168
  object_detector:
    cameras:
      camera_1:
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
            confidence: 0.4
            trigger_event_recording: true
          - label: cat
            confidence: 0.4
            trigger_event_recording: true
          - label: bird
            confidence: 0.4
            trigger_event_recording: true
          - label: dog
            confidence: 0.4
            trigger_event_recording: true

          - label: car
            confidence: 0.4
            trigger_event_recording: true
          - label: squirrel
            confidence: 0.4
            trigger_event_recording: true
    custom_model: slotcar
    #custom_model: ipcam-combined

nvr:
  camera_1:

webserver:

storage:
  recorder:
    tiers:
      - path: /
        events:
          max_age:
            days: 14
        continuous:
          max_size:
            gb: 10

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  #username: !secret mqtt_user
  #password: !secret mqtt_pass
  home_assistant:
```
```
