### ISSUE TITLE
Docker container consumes all available memory and gets killed - "exited with code 137"

### ISSUE THREAD

**Issue by rudders** [roflcoopter/viseron#10]
I have a Privileged Debian LXC in Proxmox where I am trying to stand up viseron using Docker. 
Starting off with CPU before I battle GPU passthrough (which I've done for Plex and Shinobi in the past). 

But if I start the container the memory usage of the container simply grows until it is killed (8Gb) off by the OS. 

Running top inside the container just shows the Python task slowly growing to the memory limit before the container is killed - take 5minutes or so. Logs show visceron seems to just be waiting for something to detect. 

```
services:
  viseron:
    image: roflcoopter/viseron:dev
    container_name: viseron
    volumes:
      - /mnt/videos:/recordings
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
```

```
viseron     | [2020-09-09 17:18:00] [lib.camera.front_porch_camera] [INFO    ] - Resolution: 2304x1296 @ 180000 FPS
viseron     | [2020-09-09 17:18:00] [lib.camera.front_porch_camera] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel panic -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -rtsp_transport tcp -i rtsp://rudders:jennais5@192.168.0.32:554/h264Preview_01_main -f rawvideo -pix_fmt nv12 pipe:1
viseron     | [2020-09-09 17:18:00] [lib.nvr.front_porch_camera] [DEBUG   ] - <lib.config.ViseronConfig object at 0x7fc24b1c0b70>
viseron     | [2020-09-09 17:18:00] [lib.camera.front_porch_camera] [DEBUG   ] - Starting capture process
viseron     | [2020-09-09 17:18:00] [lib.camera.front_porch_camera] [DEBUG   ] - Starting decoder thread
viseron     | [2020-09-09 17:18:00] [lib.recorder            ] [DEBUG   ] - Initializing ffmpeg recorder
viseron     | [2020-09-09 17:18:00] [lib.recorder            ] [DEBUG   ] - FFMPEG encoder command: ffmpeg -hide_banner -loglevel panic -f rawvideo -pix_fmt nv12 -s:v <width>x<height> -r <fps> -i pipe:0 -y <file>
viseron     | [2020-09-09 17:18:00] [lib.nvr.front_porch_camera] [DEBUG   ] - NVR thread initialized
viseron     | [2020-09-09 17:18:00] [lib.nvr.front_porch_camera] [DEBUG   ] - Waiting for first frame
viseron     | [2020-09-09 17:18:00] [root                    ] [INFO    ] - Initialization complete
viseron     | [2020-09-09 17:18:03] [lib.camera.front_porch_camera] [DEBUG   ] - Running object detection at 1s interval, every 180000 frame(s)
viseron     | [2020-09-09 17:18:03] [lib.camera.front_porch_camera] [DEBUG   ] - Running motion detection at 1s interval, every 180000 frame(s)
viseron     | [2020-09-09 17:18:07] [lib.nvr.front_porch_camera] [DEBUG   ] - First frame received
viseron     | [2020-09-09 17:18:07] [lib.nvr.front_porch_camera] [DEBUG   ] - Objects: []
viseron exited with code 137
```

```
cameras:
  - name: Front Porch Camera
    mqtt_name: viseron_front_porch
    host: 192.168.x.xx
    port: 554
    username: #####
    password: ######
    path: /h264Preview_01_main
    motion_detection:
      interval: 1
      trigger: false
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: cat
          confidence: 0.8

# MQTT is optional
mqtt:
  broker: 192.168.0.252
  port: 1883
  username: hamqtt
  password: hamqtt


recorder:
  lookback: 10
  timeout: 10
  retain: 7
  folder: /recordings

logging:
  level: debug
```

**Comment by roflcoopter** [comment]
```Resolution: 2304x1296 @ 180000 FPS``` seems way off!
Sometimes OpenCV cant detect the fps correctly, try specifying:
```yaml
fps : <camera fps here>
```
in your camera config and see if that helps

**Comment by roflcoopter** [comment]
Just found a small bug, to specify FPS you also need to specify the width and height. So add this to the config.
```yaml
width: 2304
height: 1296
fps: <camera fps here>
```
I will fix this in the next release
