### ISSUE TITLE
[viseron.components.webserver.api.v1.hls] - Could not find init.mp4 file for camera camera_1

### ISSUE THREAD

**Issue by emplos** [roflcoopter/viseron#1013]
Configured viseron to continuous recording.

In segments folder files are created - a lot of .m4s and init.mp4.

When i try to check timeline in webserver i got error:
```
[viseron.components.webserver.api.v1.hls] - Could not find init.mp4 file for camera camera_1
[WARNING ] [tornado.access] - 404 GET /api/v1/hls/camera_1/index.m3u8?start_timestamp=1749621149&daily=true (10.10.10.2) 18.12ms
```

my docker-cmpose.yml
```
services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    shm_size: "1024mb"
    volumes:
      - /mnt/wdmycloud/segments/:/segments
      - snapshots:/snapshots
      - thumbnails:/thumbnails
      - event_clips:/event_clips
      - config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8888:8888
    privileged: true

volumes:
  segments:
    driver: local
    driver_opts:
      device: /mnt/wdmycloud/segments
      o: bind
      type: local
  snapshots:
  thumbnails:
  event_clips:
  config:

```

my configuration:
```
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: kam1
      host: 10.10.10.110
      port: 8554
      path: /main
      username: admin
      password: mypassword
      width: 2304
      height: 1296
      fps: 15
      codec: h264
      audio_codec: aac
      recorder:
        continuous_recording: true  # Not needed since it is the default, included for clarity
        continuous:  # Example of setting a max size of 10 GB for this individual camera
          max_size:
            gb: 10
          max_age:
            days: 7



## Then add an object detector
#darknet:
#  object_detector:
#    cameras:
#      camera_1:  # Attach detector to the configured camera_1 above
#        fps: 1
#        scan_on_motion_only: false  # Scan for objects even when there is no motion
#        labels:
#          - label: person
#            confidence: 0.75
#            trigger_event_recording: true
#
#      camera_2:  # Attach detector to the configured camera_2 above
#        fps: 1
#        labels:
#          - label: person
#            confidence: 0.75
#            trigger_event_recording: true


## You can also use motion detection
#mog2:
#  motion_detector:
#    cameras:
#      camera_2:  # Attach detector to the configured camera_2 above
#        fps: 1


## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1
#  camera_2:  # Run NVR for camera_2

logger:
  logs:
    viseron.components.webserver: debug
# Now you can restart Viseron and you should be good to go!

```
