### ISSUE TITLE
possible to disable recordings?

### ISSUE THREAD

**Issue by djaydev** [roflcoopter/viseron#105]
Hello, thanks for this project.  I'm trying to disable recordings in viseron, I removed the recordings portion from the config.yaml file but I'm still getting new recordings.  Sorry if you already mention this in the readme.

**Comment by roflcoopter** [comment]
There is no neat way to do this, but for each label defined you can add ```triggers_recording: false``` like this:

```yaml
object_detection:
  labels:
    - label: person
      confidence: 0.8
      triggers_recording: false
```
