### ISSUE TITLE
Recording not stopping,. 

### ISSUE THREAD

**Issue by Sloth-on-meth** [roflcoopter/viseron#120]
i have trigger_recording set to false in my config, but object detection seems to cause my instance to record 24/7

```yaml
cameras:
  - name: voortuin
    host: 192.168.178.55
    port: 8554
    username: root
    password: 
    path: /unicast
#    max_timeout: 30
    stream_format: rtsp
    width: 1280
    #logging: debug
    height: 720
    fps: 10
    publish_image: True

motion_detection:
      trigger_detector: false
      timeout: true
      interval: 0.5
      max_timeout: 30
# MQTT is optional
mqtt:
  broker: 192.168.178.79
  port: 1883
  username: mosquitto
  password: 
#  publish_image: true 

recorder:
#  max_timeout: 30
  lookback: 10
  timeout: 10
  retain: 7
  folder: /recordings
  logging:
    level: debug
#  send_to_mqtt: true
post_processors:
  face_recognition:
    model: cnn
    type: dlib
    expire_after: 10
  logging:
    level: debug

object_detection:
      trigger_recording: False
      logging:
        level: debug
      interval: 1
#      timeout: False
      labels:
      ````

**Comment by roflcoopter** [comment]
```trigger_recording``` has to be under the ```label``` section

**Comment by Sloth-on-meth** [comment]
i have it under labels now, but it's still recording as soon as i start

**Comment by roflcoopter** [comment]
Can you show me that config?

**Comment by Sloth-on-meth** [comment]
```
object_detection:
      interval: 8
      labels:
        - label: person
        - label: car
          confidence: 0.5
      triggers_recording: false```
      
      this is with a large chunk of my labels cut out for readability ofc

**Comment by Sloth-on-meth** [comment]
#115 might explain why things are weird..

**Comment by roflcoopter** [comment]
this is what the config should look like
```yaml
object_detection:
      interval: 8
      labels:
        - label: person
          triggers_recording: true
        - label: car
          confidence: 0.5
          triggers_recording: false
```

```triggers_recording``` belongs under each label
Is there a car in view all the time? If so your old config would never stop since ``triggers_recording: true``` is default
