### ISSUE TITLE
filter_args ignored?

### ISSUE THREAD

**Issue by dinaras** [roflcoopter/viseron#123]
Hello,
First of all thank you for this project. it looks very promising. Compared to other similar projects, it supports yolov4 which in my opinion works better.

Now in my question. I am trying to make ffmpeg limit fps as i am unable to limit it from the camera side.
I am using the following in camera config
 - name: main_gate
    host: 192.168.1.184
    port: 554
    username: admin
    password: xxxxxxxxx
    path: /Streaming/Channels/1/
    width: 1280
    height: 720
    fps: 15
    filter_args:
      - "filter:v fps=fps=15"
    substream:
      path: /Streaming/Channels/2/
      width: 720
      height: 480
      fps: 5
      filter_args:
        - "filter:v fps=fps=5"
    motion_detection:
      interval: 0.2
      trigger_detector: true
      threshold: 50
      alpha: 0.4
    object_detection:
      interval: 0.2
      labels:
        - label: person
          confidence: 0.8
        - label: car
          confidence: 0.7
        - label: dog
          confidence: 0.7
        - label: truck
          confidence: 0.7
But while starting viseron in docker i see the following ffmpeg command which does not include the frame filter
[2021-02-10 23:45:37] [lib.camera.main_gate    ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -c:v h264_cuvid -rtsp_transport tcp -i rtsp://admin:Ixxxxx@192.168.1.184:554/Streaming/Channels/2/ -f rawvideo -pix_fmt nv12 pipe:1

Am i doing something wrong here?

**Comment by roflcoopter** [comment]
Thanks for showing interest in Viseron!

Could you repost your config with it enclosed in a code-block, like this:
```yaml
cameras:
  - name: main_gate
    host: 192.168.1.184
```

you do that by wrapping your code in triple backticks like this:
\```yaml
code_goes_here
\```

**Comment by dinaras** [comment]
Hello, thank you for your reply, i know i messed it up
Whatever i might have tried. ffmpeg commands shown in debug when viseron start do not have filters included. Not an expert here though
Please find my conf below hopefully correctly shown
```
cameras:
  - name: front_door
    host: 192.168.1.88
    port: 554
    username: admin
    password: dinaras2010
    path: /00/
    width: 1920
    height: 1080
    fps: 15
    filter_args:
      - "fps": "fps=15"
    substream:
      path: /01/
      width: 720
      height: 480
      fps: 5
      filter_args:
        - "-filter:v": "fps=fps=5"
    motion_detection:
      interval: 0.2
      trigger_detector: true
      threshold: 30
      alpha: 0.3
    object_detection:
      interval: 0.2
      labels:
        - label: person
          confidence: 0.8
          #post_processor: face_recognition
```
