### ISSUE TITLE
recording not stopping parked car

### ISSUE THREAD

**Issue by JustMe0815** [roflcoopter/viseron#129]
HI there,

i do have an issue that the recording is not stopping for a parked car. 
Motion stopped, but recording continues. 
Any help on this?

```
  - name: FrontDoor
    mqtt_name: FrontDoor
    host: 192.168.103.10
    port: 554
    username: admin
    password: xxxxxxx
    path: /ch0_0.264
    width: 1920
    height: 1080
    fps: 25
    substream:
      path: /ch0_1.264
      width: 640
      height: 480
      fps: 15
      rtsp_transport: tcp
    motion_detection:
      interval: 1
      area: 0.01
      alpha: 0.05
      width: 640
      height: 360
      frames: 5
      threshold: 50
      trigger_detector: true
      timeout: true
      max_timeout: 10
      mask:
        - points:
            - x: 13
              y: 4
            - x: 211
              y: 8  
            - x: 209
              y: 44
            - x: 15
              y: 41  
    object_detection:
      interval: 3
      labels:
        - label: person
          confidence: 0.7
          triggers_recording: true
        - label: dog
          confidence: 0.7
          triggers_recording: true
        - label: car
          confidence: 0.7
          triggers_recording: true
    publish_image: false       
```

**Comment by roflcoopter** [comment]
Thanks for trying out Viseron!

At the moment this cant be solved, recordings will not stop until both no motion or object is detected.
I have had several reports of this issue tho so i think i will need to look at this asap.

Just to clarify, you want the recording to continue only when there is both motion **and** objects detected?

**Comment by JustMe0815** [comment]
Thanks for the reply!
Yes, when motion stops, recording should stop as well.

**Comment by roflcoopter** [comment]
@JustMe0815 Sorry forgot to mention it, but i made something that should work for this and released it in 1.8.0b5.

Could you give it a spin and let me know how it goes?

**Comment by JustMe0815** [comment]
ok thanks i will give it a go

**Comment by JustMe0815** [comment]
@roflcoopter I tested this but for some reason its now taking 2 videos when there is movement and it also does not respect the set lookback and timeout for the recorder.

**Comment by roflcoopter** [comment]
Can you share config and debug logs please?

**Comment by JustMe0815** [comment]
when you requested the config, i double checked that i did not have an error in there.... I was using the above config. with the below config it works great.

```
logging:
  level: debug
recorder:
  lookback: 10
  timeout: 10
  retain: 7
  folder: /recordings
  segments_folder: /recordings/segments
  codec: copy
cameras:
  - name: FrontDoor
    mqtt_name: FrontDoor
    host: 192.168.103.10
    port: 554
    username: admin
    password: xyz
    path: /ch0_0.264
    width: 1920
    height: 1080
    fps: 25
    substream:
      path: /ch0_1.264
      port: 554
      width: 640
      height: 480
      fps: 15
      rtsp_transport: tcp
    motion_detection:
      interval: 0.5
      area: 0.02
      alpha: 0.2
      width: 640
      height: 360
      timeout: true
      max_timeout: 30
      trigger_detector: true
      mask:
        - points:
            - x: 13
              y: 4
            - x: 211
              y: 8  
            - x: 209
              y: 44
            - x: 15
              y: 41  
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.3
          triggers_recording: true
        - label: dog
          confidence: 0.3
          triggers_recording: true
        - label: car
          confidence: 0.3
          triggers_recording: true
    publish_image: false       

logging:
  level: debug

# MQTT is optional
mqtt:
  broker: 192.168.100.99
  port: 1886
  home_assistant:
    enable: false
```

**Comment by JustMe0815** [comment]
@roflcoopter can you please make this available for RPI as well?

**Comment by roflcoopter** [comment]
> @roflcoopter can you please make this available for RPI as well?

It should already be available under the `roflcoopter/rpi3-viseron` image

**Comment by JustMe0815** [comment]
> > @roflcoopter can you please make this available for RPI as well?
> 
> It should already be available under the `roflcoopter/rpi3-viseron` image

@roflcoopter  Thanks, i gave this a go, but unfortunately it is giving me an error. Does this not work yet on a raspberry pi 4 ?

**Comment by netpro25** [comment]
I don't think this is fixed, at least I'm having this issue where I'm getting recordings of a parked truck in my driveway. Here's my config. Let me know if there's something off, if not I can send over logs or anything else to help.

```yaml
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Drive
      host: 192.168.0.100
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      recorder:
        idle_timeout: 20
        codec: h264
      username: admin
      password: redacted

darknet:
  object_detector:
    cameras:
      camera_1:  
        fps: 1
        scan_on_motion_only: true 
        labels:
          - label: dog
            confidence: 0.7
            trigger_recorder: false
          - label: person
            confidence: 0.75
            trigger_recorder: true
          - label: car
            confidence: 0.7
            trigger_recorder: true
            require_motion: true
          - label: truck
            confidence: 0.7
            trigger_recorder: true
            require_motion: true 
        mask:
          - coordinates:
            - x: 3835
              y: 688
            - x: 3567
              y: 617
            - x: 3608
              y: 373
            - x: 2641
              y: 193
            - x: 2652
              y: 353
            - x: 1701
              y: 366
            - x: 1108
              y: 397
            - x: 667
              y: 465
            - x: 5
              y: 851
            - x: 2
              y: 3
            - x: 1104
              y: -3
            - x: 3832
              y: 10

mog2:
  motion_detector:
    cameras:
      camera_1:
        trigger_recorder: true
        fps: 1

nvr:
  camera_1:  # Run NVR for camera_1

mqtt:
  broker: mosquitto
  port: 1883
  username: homeassistant
  password: redacted
  home_assistant:
```
