### ISSUE TITLE
never-ending recording

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#14]
I had a strange event this morning.

[snapshot](https://imgur.com/a/IbbU1f8) provided by Viseron. That picture was from a little over an hour ago. There is no movement there, and the info log just showed that the recording kept getting retriggered. I had to quit Viseron to get the recording to stop (and interestingly, also to be able to view the 4.4+GB .mp4, it appears the header is missing information until the recorder stops, which is suboptimal...

How do I help debug this? My config file looks like this. The confidence levels and area are both intentionally "low" because it's not detecting hardly anything at the moment (car goes by, me waving in front of the camera, etc.) and I'm debugging that. I have SecuritySpy watching these same cameras and performing its motion/object detection as well.

```
logging:
  level: info

object_detection:
  type: darknet
  interval: 6
  labels:
    - label: person
      confidence: 0.6
    - label: bicycle
      confidence: 0.6
    - label: car
      confidence: 0.6
    - label: truck
      confidence: 0.6
    - label: motorbike
      confidence: 0.6
    - label: bird
      confidence: 0.6
    - label: cat
      confidence: 0.6
    - label: dog
      confidence: 0.6

motion_detection:
  interval: 1
  trigger: true
  timeout: true
  width: 640
  height: 360
  area: 100
  frames: 3

recorder:
  lookback: 15
  timeout: 15
  retain: 31
  folder: /recordings

mqtt:
  broker: 192.168.x.x
  port: 1883

cameras:
  - name: cam01
    mqtt_name: cam01
    host: 192.168.x.x
    port: 554
    path: /user=...

(repeat for other cameras)
```
