### ISSUE TITLE
[FR] start recording on Motion

### ISSUE THREAD

**Issue by JustMe0815** [roflcoopter/viseron#149]
It would be nice to have the ability to start recording ON MOTION

```
    motion_detection:
      interval: 0.5
      timeout: true
      max_timeout: 30
      trigger_detector: false
      triggers_recording: true
```
