### ISSUE TITLE
[FR] how to supply new object detection models

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#19]
At present, Viseron currently pulls in the object models when Docker creates the image. Would it be possible to specify a second directory (something like `-v /host/path/models/custom:/models/darknet/custom` or somesuch) so that instances could include customized models for their specific application? Can the model library/libraries be re-read with a signal or MQTT topic subscription to update models without restarting Viseron?

**Comment by roflcoopter** [comment]
You can mount your models to whatever folder you like inside the container, and then just point the config to it, example:
```yaml
object_detection:
  type: darknet
  model_path: <path to your mounted model .weights file>
  model_config: <path to your mounted model .cfg file>
  labels_path: <path to your mounted labels file>
```

Regarding the reloading, yes that could work but i think it would add a level of complexity that could take a while to implement.
Right now i have a lot of other things going on with Viseron so reloading without restarting would probably come down the line sometime in the future
