### ISSUE TITLE
Detector unable to detect EdgeTPU

### ISSUE THREAD

**Issue by geekho-me** [roflcoopter/viseron#220]
The Detector is unable to detect my EdgeTPU device:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
************************ UID/GID *************************,
User uid:    0,
User gid:    0,
************************** Done **************************,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-gid-video-device: executing... ,
[cont-init.d] 20-gid-video-device: exited 0.,
[cont-init.d] 30-edgetpu-permission: executing... ,
************** Setting EdgeTPU permissions ***************,
Coral Vendor IDs:,
"1a6e",
"18d1",
Matching USB devices:,
Bus 002 Device 002: ID 1a6e:089a  ,
************************** Done **************************,
[cont-init.d] 30-edgetpu-permission: exited 0.,
[cont-init.d] 40-set-env-vars: executing... ,
****** Checking for hardware acceleration platforms ******,
OpenCL cannot be used,
VA-API cannot be used,
CUDA cannot be used,
*********************** Done *****************************,
[cont-init.d] 40-set-env-vars: exited 0.,
[cont-init.d] 50-check-if-rpi: executing... ,
********** Checking if we are running on an RPi **********,
Not running on any supported RPi,
*********************** Done *****************************,
[cont-init.d] 50-check-if-rpi: exited 0.,
[cont-init.d] 55-check-if-jetson: executing... ,
****** Checking if we are running on a Jetson Board ******,
Not running on any supported Jetson board,
*********************** Done *****************************,
[cont-init.d] 55-check-if-jetson: exited 0.,
[cont-init.d] 60-ffmpeg-path: executing... ,
****************** Getting FFmpeg path *******************,
FFmpeg path: /usr/local/bin/ffmpeg,
*********************** Done *****************************,
[cont-init.d] 60-ffmpeg-path: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
[2021-06-15 16:39:30] [INFO    ] [viseron                 ] - -------------------------------------------,
[2021-06-15 16:39:30] [INFO    ] [viseron                 ] - Initializing...,
[2021-06-15 16:39:34] [ERROR   ] [viseron.detector.edgetpu] - EdgeTPU not found. Detection will run on CPU,
[2021-06-15 16:39:34] [INFO    ] [viseron                 ] - Initializing NVR threads,
[2021-06-15 16:39:36] [INFO    ] [viseron                 ] - Initialization complete,
```

Setup:

Physical Host: VMware ESXi using USB pass through to the Guest.
Guest: Ubuntu 20.04.2 LTS Server running Docker version 20.10.7, build f0df350
Docker Image: Current Dev branch (as of 2021-06-15)

`config.yaml`:

```
cameras:
  - name: front
    host: 192.168.0.60
    port: 1935
    stream_format: rtmp
    path: /bcs/channel0_main.bcs?channel=0&stream=0&user=XXXXXX&password=XXXXXX

object_detection:
  type: edgetpu
  model_path: /detectors/models/edgetpu/model.tflite
  label_path: /detectors/models/edgetpu/labels.txt
  interval: 6
  labels:
    - label: person
      confidence: 0.9
      height_min: 0.1481
      height_max: 0.7
      width_min: 0.0598
      width_max: 0.36
    - label: dog
      confidence: 0.8
```

Guest OS (Ubuntu) can detect the EdgeTPU:

```
user@docker-host:/opt/data/viseron/config$ lsusb
Bus 002 Device 002: ID 1a6e:089a Global Unichip Corp.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
user@docker-host:/opt/data/viseron/config$
```

Container OS can detect the EdgeTPU:

```
root@9062cb6cef60:/src# lsusb
Bus 002 Device 002: ID 1a6e:089a  
Bus 002 Device 001: ID 1d6b:0003  
Bus 001 Device 002: ID 0e0f:0003 VMware VMware Virtual USB Mouse
Bus 001 Device 001: ID 1d6b:0002  
root@9062cb6cef60:/src# 
```
