### ISSUE TITLE
OpenCL errors

### ISSUE THREAD

**Issue by jarekmor** [roflcoopter/viseron#223]
I am testing the latest roflcoopter/amd64-cuda-viseron image with old Nvidia GT730 2GB GPU (compute cap. 3.5).

I started my test with the following config but I noticed errors after the first motion was detected:

```
cameras:
  - name: raspicam
    host: 192.168.1.14
    port: 8555
    stream_format: rtsp
    username: user
    password: password
    path: /unicast
    width: 1280
    height: 720
    fps: 10
    codec: h264_cuvid
    ffmpeg_loglevel: info
    logging:
      level: debug
```
Please find attached logfile.
https://pastebin.com/SUkFGvjB

Then I modified the config file with following changes:

```
cameras:
  - name: raspicam
    host: 192.168.1.14
    port: 8555
    stream_format: rtsp
    username: user
    password: password
    path: /unicast
    width: 1280
    height: 720
    fps: 10
#  codec: h264_cuvid
#  ffmpeg_loglevel: info
    logging:
      level: debug
```
and no errors at the beginning.
After the first motion was detected the picture was saved in recordings folder immediately.
The mp4 file was recorded as there was no motion.

Unfortunately after the second motion detected the container stopped working and there were errors regarding recording proces.
The log file from the last configuration.
https://pastebin.com/b2AtWaGF

From NVTOP I can see that GPU% memory is about 50-70% utilized.
