### ISSUE TITLE
motion_detected MQTT not triggering although log shows motion

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#27]
I'm not sure if I'm just misunderstanding the MQTT implementation or not. I have a camera with a big old spider web in front of it which should be generating lots of motion events. At least I see SecuritySpy going nuts with it so I assume Viseron should also be seeing it.

I see `homeassistant/binary_sensor/cam05/motion_detected/config` with the following value:

```
{
  "name": "cam05 motion_detected",
  "state_topic": "homeassistant/binary_sensor/cam05/motion_detected/state",
  "value_template": "{{ value | upper }}",
  "availability_topic": "viseron/lwt",
  "payload_available": "alive",
  "payload_not_available": "dead",
  "json_attributes_topic": "homeassistant/binary_sensor/cam05/motion_detected/state"
}
```

I have `mosquitto_sub -h localhost -t homeassistant/binary_sensor/cam05/motion_detected/state` running in a shell on the mqtt server.

I see the following in the docker log:

```
[2020-09-13 20:25:07] [lib.motion.cam05        ] [DEBUG   ] - Motion frames: 141, area: 3617.0
[2020-09-13 20:25:11] [lib.motion.cam05        ] [DEBUG   ] - Motion frames: 142, area: 5486.5
[2020-09-13 20:25:15] [lib.motion.cam05        ] [DEBUG   ] - Motion frames: 143, area: 5007.5
[2020-09-13 20:25:19] [lib.motion.cam05        ] [DEBUG   ] - Motion frames: 144, area: 2571.0
```

and finally, the relevant bits of my `config.yaml`:

```
motion_detection:
  interval: 2
  trigger: true
  timeout: true
  width: 640
  height: 360
  area: 1000
  frames: 3
  logging:
    level: debug

cameras:
  - name: cam05
    mqtt_name: cam05
    host: 192.168.x.x
    port: 554
    path: /x
    zones:
      - name: garage_side
        points:
        - x: 0
          y: 0
        - x: 1919
          y: 0
        - x: 1919
          y: 1079
        - x: 0
          y: 1079
```

with `area: 1000` and `frames: 3`, shouldn't the log I showed above be enough to trigger a motion event? I'm wondering if the "frames" number in the log is just the count of motion-detected frames since the start of the docker instance, rather than "I found 3 frames in a row with area 5123".  i.e. the log doesn't help me see how many continuous frames it found with the respective areas.
