### ISSUE TITLE
Never any recognized face

### ISSUE THREAD

**Issue by dadaloop82** [roflcoopter/viseron#271]
Good morning!

I'm very fond of this program, but unfortunately I've never been able to use it 100% because I didn't have a powerful enough HW.
I have never been able to use the facial recognition, neither with the uploaded photos (more than 20 photos per person) nor the saving of new faces not recognized. The recognition of objects (people, etc. ..) instead has always worked sufficiently well.

Now I'm finally in possession of a Board Nvidia JetSon Nano last model with 4Gb of Ram and obviously CUDA support and I was hoping that things would change.

The program runs perfectly but absolutely no face is recognized, either among those loaded or not loaded.
Not even if I put myself in front of the camera, it recognizes me.
I've tried to "play" with the settings, raising the FPS and more but I get no results.
My goal was to have it recognize the faces "on its own" and then associate them with the person by putting the photos in their respective folders.

At this point I think the problem is the camera, considering it's hanging from the ceiling at about a 45° angle filming the entire room. Maybe it needs to be in front to recognize the faces? The resolution is 1280x720 in RTSP
I would also have a USB camera, but can I use it with Viseron?

I look forward to yours and thank you!
Daniel

**Comment by roflcoopter** [comment]
Hello!

Sorry you are having issues, i am aware that the bilt in face recognition is suboptimal, but i have found it difficult to improve.
However, for me it has worked okay at least.

Could you show me your config?

**Comment by dadaloop82** [comment]
Sure! This below is my config.

Some notes:
- I tried to put the camera so that it takes the face frontally, doing several experiments in different positions but the face never detects it
- I tried to put a picture in front of the camera, it doesn't detect any face
- I tried downloading the DEV version but unfortunately it still doesn't work.

Thanks!

```
mqtt:
  broker: 192.168.1.200
  port: 1883
  username: ****
  password: ****

cameras:
  - name: soggiorno
    host: 192.168.1.103
    port: 554
    username: admin
    password: SXRXKI
    path: /Streaming/Channels/101
    width: 1280
    height: 720
    fps: 9
    publish_image: false
    
motion_detection:
  interval: 0.3
  frames: 1
  trigger_detector: true
  trigger_recorder: false

object_detection:
  type: darknet
  interval: 0.5
  log_all_objects: false
  model_path: /detectors/models/darknet/v4/yolov4.weights 
  model_config: /detectors/models/darknet/v4/yolov4.cfg 
  label_path: /detectors/models/darknet/v4/coco.names
  labels:
    - label: person
      confidence: 0.9
logging:
  level: debug
      
post_processors:
  face_recognition:
    type: dlib
    expire_after: 10    
    save_unknown_faces: true
  
  
```

**Comment by dadaloop82** [comment]
This is a snapshot of a frame (get from recording folder)
Recognizes the object (person) but not the face

![13_20_41](https://user-images.githubusercontent.com/48093535/134505170-9f069f46-4266-4dc3-b9b0-a903e9cf54ae.jpg)

**Comment by roflcoopter** [comment]
Ahh i see, this might be a bit unclear but you have to use the `post_processor` config option under `labels`, something like this:

```yaml
mqtt:
  broker: 192.168.1.200
  port: 1883
  username: ****
  password: ****

cameras:
  - name: soggiorno
    host: 192.168.1.103
    port: 554
    username: admin
    password: SXRXKI
    path: /Streaming/Channels/101
    width: 1280
    height: 720
    fps: 9
    publish_image: false
    
motion_detection:
  interval: 0.3
  frames: 1
  trigger_detector: true
  trigger_recorder: false

object_detection:
  type: darknet
  interval: 0.5
  log_all_objects: false
  model_path: /detectors/models/darknet/v4/yolov4.weights 
  model_config: /detectors/models/darknet/v4/yolov4.cfg 
  label_path: /detectors/models/darknet/v4/coco.names
  labels:
    - label: person
      confidence: 0.9
      post_processor: face_recognition  # <------------ This is what i added
logging:
  level: debug
      
post_processors:
  face_recognition:
    type: dlib
    expire_after: 10    
    save_unknown_faces: true
```

Does that work for you?
