### ISSUE TITLE
Faster than 1 second inference?

### ISSUE THREAD

**Issue by jasonbarbee** [roflcoopter/viseron#281]
First, thanks for publishing this project.

I'm trying to infer objects faster than 1 FPS. My camera is 20 FPS.

I have the motion detector down to 0.05 (1/20). 
Object detection interval down to 0.05.
Looking at the debugs, I am guessing I get about 1-2, maybe 3 FPS send into the detector, it's difficult to tell as the viseron logs say the same message (objects detected []) was repeated X times, but it doesn't timestamp each detection log.

My Jetson Nano is idling around 20% cpu across the cores, and barely hitting the GPU (watching via jtop) - and I want to process more FPS for a realtime vehicle application.

I've read some docs and the previous issues. It seems like I need to decrease the motion detector, but when I decrease it below 0.05, I get divide by 0 errors in the code.

How can I increase the FPS pushed into the Object Detection engine and not hit divide by 0 errors?

Here's my config 
```
cameras:
  - name: Camera
    host: 192.168.123.132
    port: 554
    username: <if auth is enabled>
    password: <if auth is enabled>
    path: /live.sdp
    width: 1920
    height: 1920
    fps: 20
motion_detection:
  interval: 0.05
  trigger_detector: false
  trigger_recorder: false
  timeout: true
  max_timeout: 30
  width: 416
  height: 416
  area: 0.1
  threshold: 1
  frames: 1

object_detection:
  type: darknet
  interval: 0.05
  log_all_objects: true

logging:
  level: debug
```
