### ISSUE TITLE
Voluptuous error extra keys not allowed @ data['cameras'][0]['object_detection']['mask']

### ISSUE THREAD

**Issue by olekenneth** [roflcoopter/viseron#301]
Why do I get the config parsing error, do you know?

```yaml
cameras:
  - name: Ute
    mqtt_name: ute
    host: 192.168.0.*
    port: 554
    username: ***
    password: "***"
    path: '/h264'
    height: 2592
    width: 1944
    fps: 5
    publish_image: true
    filter_args:
      - '-vf'
      - "transpose=2"
    object_detection:
      interval: 1
      mask:
        - points:
          - x: 7
            y: 515
          - x: 152
            y: 453
    static_mjpeg_streams:
      small:
        width: 100
        height: 100
```

I moved it to the global object_detection and got no error.

edit: add `static_mjpeg_streams:`-config
