### ISSUE TITLE
Camera streaming question

### ISSUE THREAD

**Issue by yury-sannikov** [roflcoopter/viseron#308]
Hi @roflcoopter,

I'm playing with gstreamer in the viseron/camera/stream.py. 
![image](https://user-images.githubusercontent.com/6585448/145275466-b0e0c673-64a7-4f75-aa01-7f323d3f1e73.png)
It seems GStreamer is processing RTSP stream and uses hardware acceleration. However, I do not see any calls to the `read` or `pool` methods of the `Stream` class.

My config is pretty basic:
```

cameras:
  - name: Front door
    mqtt_name: viseron_front_door
    host: 192.168.5.100
    port: 554
    username: admin
    password: "123"
    path: /cam/realmonitor?channel=4&subtype=0
    codec: h264_nvmpi
    width: 1920
    height: 1080
    fps: 25
    pix_fmt: nv12
    logging:
      level: debug
    motion_detection:
      interval: 1
      trigger_detector: false
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: pottedplant
          confidence: 0.9
```

I didn't dig into it much, GStreamer eat up all the time, but maybe you can spot something that I didn't catch.
