### ISSUE TITLE
EdgeTPU USB device not found + getting VA-API to work on AMD processors?

### ISSUE THREAD

**Issue by jasonpstokes** [roflcoopter/viseron#313]
Hi, playing with viseron (cool project!) but can't get it to see my Coral USB? Followed through #173 but whilst my outputs looks OK, Viseron is not finding it? (even after adding the env variables) What am I doing wrong please?

```
************** Setting EdgeTPU permissions ***************
viseron    | Coral Vendor IDs:
viseron    | "1a6e",ATTRS{idProduct}=="089a"
viseron    | "18d1",ATTRS{idProduct}=="9302"
viseron    | No EdgeTPU USB device was found
```

docker-compose.yml
```yaml
services:
  viseron:
    container_name: viseron
    privileged: true
    image: roflcoopter/viseron:latest
    hostname: viseron
    restart: always
    shm_size: '320m'
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/docker/viseron:/config
      - /mnt/nas/viseron/recordings:/recordings
      - /dev/bus/usb:/dev/bus/usb
      - type: tmpfs
        target: /tmp
        tmpfs:
          size: '1gb'
    network_mode: bridge
    ports:
      - 0.0.0.0:8888:8888/tcp
    environment:
      - PUID=0
      - PGID=0
```

config.yaml
```yaml
mqtt:
 broker: 192.168.1.5
 port: 1883
 username: user
 password: pass

object_detection:
  type: edgetpu
  device: usb
  label_path: /config/labels.txt
  labels:
    - label: person
      confidence: 0.6
    - label: dog
      confidence: 0.6

recorder:
  segments_folder: /tmp

cameras:
  - name: Driveway
    mqtt_name: driveway
    stream_format: rtmp
    host: 192.168.1.71
    port: 1935
    path: /bcs/channel0_main.bcs?channel=0&stream=0&user=view&password=pass
    width: 2560
    height: 1920
    fps: 30
    codec: h264
    audio_codec: aac
    substream:
      stream_format: rtmp
      port: 1935
      path: /bcs/channel0_ext.bcs?channel=0&stream=2&user=view&password=pass
      width: 896
      height: 672
      fps: 5
      codec: h264
      # hwaccel_args:
      # - -hwaccel
      # - vaapi
      # - -hwaccel_device
      # - /dev/dri/renderD128
      # - -hwaccel_output_format
      # - yuv420p
      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - nobuffer+genpts+discardcorrupt
      - -flags
      - low_delay
      - -strict
      - experimental
      - -analyzeduration
      - 1000M
      - -probesize
      - 1000M
      - -rw_timeout
      - '5000000'
```

**Debian 11 Host**
`lsusb`
```
Bus 006 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 003: ID 051d:0002 American Power Conversion Uninterruptible Power Supply
Bus 007 Device 005: ID 0658:0200 Sigma Designs, Inc. Aeotec Z-Stick Gen5 (ZW090) - UZB
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 005 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 003: ID 18d1:9302 Google Inc.
Bus 003 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 002: ID 1a86:7523 QinHeng Electronics CH340 serial converter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**In Container**
`lsusb`
```
Bus 006 Device 001: ID 1d6b:0002
Bus 008 Device 001: ID 1d6b:0001
Bus 002 Device 001: ID 1d6b:0002
Bus 007 Device 003: ID 051d:0002 American Power Conversion Back-UPS RS 550G FW:857.L7 .I USB FW:L7
Bus 007 Device 005: ID 0658:0200
Bus 007 Device 001: ID 1d6b:0001
Bus 005 Device 001: ID 1d6b:0003
Bus 004 Device 001: ID 1d6b:0002
Bus 003 Device 003: ID 18d1:9302
Bus 003 Device 001: ID 1d6b:0003
Bus 001 Device 002: ID 1a86:7523  USB Serial
Bus 001 Device 001: ID 1d6b:0002
```

`ls -lh /dev/bus/usb`
```
total 0
drwxr-xr-x 2 root root  80 Jan 16 22:36 001
drwxr-xr-x 2 root root  60 Jan 16 22:36 002
drwxr-xr-x 2 root root  80 Jan 16 22:37 003
drwxr-xr-x 2 root root  60 Jan 16 22:36 004
drwxr-xr-x 2 root root  60 Jan 16 22:36 005
drwxr-xr-x 2 root root  60 Jan 16 22:36 006
drwxr-xr-x 2 root root 100 Jan 20 15:47 007
drwxr-xr-x 2 root root  60 Jan 16 22:36 008
```

`id abc`
```
uid=0(root) gid=0(root) groups=0(root)
```

...Also, is there a way to get VA-API with an AMD processor please? (e.g. AMD RX-427BB with AMD Radeon(tm) R7 Graphics)

```
viseron    | ****** Checking for hardware acceleration platforms ******
viseron    | OpenCL cannot be used
viseron    | VA-API cannot be used
viseron    | CUDA cannot be used
```

`ls -lh /dev/dri` (in container)
```
total 0
crw-rw---- 1 root video         226,   0 Jan 20 19:29 card0
crw-rw---- 1 root videood2RKCZr 226, 128 Jan 20 19:29 renderD128
```

`vainfo` (in container)
```
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_6
DRM_IOCTL_I915_GEM_APERTURE failed: No such file or directory
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [13]
param: 4, val: 0
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```
