### ISSUE TITLE
object_detection: suppression not supported

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#32]
Looks like the `suppression` key isn't used yet:

`extra keys not allowed @ data['object_detection']['labels'][5]['suppression']`

Config example:

```
object_detection:
  type: darknet
  interval: 2
  logging:
    level: debug
  labels:
    - label: person
      confidence: 0.5
    - label: bicycle
      confidence: 0.6
    - label: bird
      confidence: 0.2
      suppression: 0.01
```
