### ISSUE TITLE
no motion detection after updating to 1.5.0 (area: 2.0)

### ISSUE THREAD

**Issue by akohlsmith** [roflcoopter/viseron#40]
Every since updating to 1.5.0 and playing with my motion percentage, I don't see any motion detection at all.

```
logging:
  level: INFO

motion_detection:
  interval: 1
  trigger_detector: true
  timeout: true
  max_timeout: 600
  width: 960
  height: 720
  area: 2.0
  frames: 2
  logging:
    level: DEBUG
```

The motion detectors don't seem to fire; I was originally aiming for ~10%, but when I noticed nothing was working, I reduced it to 2% and still nothing.  2% of a 960x720 image is pretty small, isn't it?  (I also had a 640x480 image originally but wanted to bump it up a bit so the object detection had more to look at)
