### ISSUE TITLE
Failed to load component cameras: no component named 'viseron.components.cameras'

### ISSUE THREAD

**Issue by jonnyrider** [roflcoopter/viseron#416]
Hello,

Not sure if this is just because I'm doing something wrong that should be very simple, but I'm brand new to Viseron and using the latest dev build I'm getting the above error. My docker run command is below:

docker run --rm -v config:/recordings-v media:/config-v /etc/localtime:/etc/localtime:ro -v /dev/bus/usb:/dev/bus/usb --privileged --name viseron --device /dev/dri --device /dev/bus/usb roflcoopter/viseron:dev

Any help would be greatly appreciated!

**Comment by roflcoopter** [comment]
Do you have a config.yaml file? It seems you are using an old format which is not supported anymore.

**Comment by jonnyrider** [comment]
Yes, and I've definitely got the new file format.

I'm using home assistant OS, and have saved the config.yaml file in my config folder, and updated the command to the below:

docker run --rm -v media:/recordings-v config:/config-v /etc/localtime:/etc/localtime:ro -v /dev/bus/usb:/dev/bus/usb --privileged --name viseron --device /dev/dri --device /dev/bus/usb roflcoopter/viseron:dev

I'm not sure if this is the right place to put it, though!

**Comment by roflcoopter** [comment]
What does your config look like?

**Comment by jonnyrider** [comment]
```
mqtt:
  broker: 192.168.0.102
  port: 1883
  username: home
  password: xxxx

ffmpeg:
  camera:
    front:
       name: Front
       host: 192.168.0.121
       path: /videoMain
       username: xxxx
       password: xxxx
       protocol: rtsp
       

edgetpu:
  object_detector:
    cameras:
      front:
        fps: 1
        labels:
          - label: person
            confidence: 0.8
  image_classification:
    device: cpu
    cameras:
      front:
    labels:
      - person

background_subtractor:
  motion_detector:
    cameras:
      front:
        fps: 1

nvr:
  front:
  
logger:
  default_level: debug
  logs:
    viseron.components.ffmpeg: debug
    viseron.components.edgetpu: debug
  cameras:
    front: debug  
```

**Comment by jonnyrider** [comment]
Sorry for the screenshot, but here it is:

![image](https://user-images.githubusercontent.com/48350560/205668764-66aa863e-d4a8-474c-9784-d48962ca942c.png)

**Comment by roflcoopter** [comment]
If you go to the webinterface, and click the gear ion in the upper right corner, what does your config look like there?

Something is not right since that error means that Viseron is reading a config that looks something like this:

```yaml
cameras: <- Not valid as firsthand key
  ...

nvr:
  front:
  
logger:
  default_level: debug
  logs:
    viseron.components.ffmpeg: debug
    viseron.components.edgetpu: debug
  cameras:
    front: debug  
```
