### ISSUE TITLE
[FEATURE] Tiered Storage options

### ISSUE THREAD

**Issue by jamitupya** [roflcoopter/viseron#455]
It would be good to be able to archive data after x period of time and shuttle that data off to spinning disks vs ssd and NVMe.

I imagine something like a standard GFS implementation would be fine. 

At the moment I use a 1-2-3
- App stores data on /mnt/user/nvr/raw (ramdisk)
- Currently, I have a cron run to rsync to another storage pool (/mnt/user/nvr/archive) for archival and import into another tool to manage the videos long term <~this step sucks (encrypted spinning)
- From /mnt/user/nvr/archive I sync with rclone to 3 providers  (cloud)

Probably need to be smart about IO somehow (snapshots of events as thumbnails?), but it would be very helpful to have all the footage then available via an archivedfootage menu, maybe a timeline slider style navigation interface? Dunno lol.

**Comment by roflcoopter** [comment]
Yeah i like this idea, could prove to be a challenge with the archived footage tho depending on the storage solution

**Comment by bsyomov** [comment]
May be storing not only video and snapshots, but logs of motion detection and object detection is a good idea?
This will allow to build a timeline with events to navigate the video archive.

Now, as I understand it, this information can only be obtained by turning on the debug log, and additionally processing it?

**Comment by roflcoopter** [comment]
Yes you are right, events are currently not stored.
I am planning to implement 24/7 recordings with a timeline that highlights events in a good way

**Comment by jamitupya** [comment]
Nice, very helpful I think.

**Comment by jamitupya** [comment]
Rethinking on this, I think you don’t even need to worry about the storage medium, since we can just mount it as we see fit anyway I think we just need the “data mover” or “archival process” really to be built and let us nest the storage.

I’d like to be able to achieve:
(1) 0-24 hrs leave to /mnt/pool0 (RAM disk)
(2) 24hrs move to /mnt/pool1 (SSD) 
(3) 7d move to /mnt/pool2 (spinning) 
(4) 30d start priming non-event/motion recordings

I’d also like to be able to only keep events/motions/objects/people etc in their own “pools” if feasible as I can then mount those folders for other processing

**Comment by roflcoopter** [comment]
Just FYI, i am gonna start working on 24/7 recordings now and i think this will be a great addition to that

**Comment by roflcoopter** [comment]
I am thinking something like this:

```yaml
storage:
  recordings:
    create_event_clip: true # False will store short segments only. True will store AND concatenate segments into a single file. NOTE: Uses double storage
    type: continuous # continuous, events. Continous will save everything but highlight Events. Events are basically todays recordings, started by trigger_recorder
    tiers:
      - path: /mnt/ramdisk
        max_size: # If this target is hit, recordings/segments will be moved to the next tier
          gb: 1
          mb: 1024
        max_age: # If this target is hit, recordings/segments will be moved to the next tier
          days: 1
          hours: 0
          minutes: 0
      - path: /mnt/ssd
        min_size: # if max_age is hit, keep at least 1gb
          gb: 1
        max_size: # If this target is hit, recordings/segments will be moved to the next tier
          gb: 10
        max_age: # If this target is hit, recordings/segments will be moved to the next tier ONLY if size is larger than min_size
            days: 7
            hours: 0
            minutes: 0

  snapshots:
    tiers: # Default, applies to everything if not overridden
      - path: /mnt/ramdisk
        max_size:
          gb: 1
          mb: 1024
        max_age:
          days: 1
          hours: 0
          minutes: 0
      - path: /mnt/ssd
        min_size:
          gb: 1
        max_size:
          gb: 10
        max_age:
          days: 7
          hours: 0
          minutes: 0
    face_recognition: # Overrides default for snapshots of face recognition
      tiers: # Default, applies to everything if not overridden
        - path: /mnt/ssd
          max_size:
            mb: 500
          min_age:
            days: 1
          max_age:
            days: 5
            hours: 0
            minutes: 0
    object_detection: # Overrides default for snapshots of detected objects
      tiers: # Default, applies to everything if not overridden
        - path: /mnt/ssd
          max_size:
            gb: 1
          max_age:
            days: 1
            hours: 0
            minutes: 0
    # And other things like motion detection, license plate recognition, etc
```

This would allow for a simple configuration if you dont have the need for complex retention rules:
```yaml
# Retain everything for 7 days flat, taking no regards to storage space
storage:
  recordings:
    tiers:
      - path: /mnt/ssd
        max_age:
          days: 7
```
