### ISSUE TITLE
MJPEG Stream Camera in HA

### ISSUE THREAD

**Issue by jamitupya** [roflcoopter/viseron#457]
I'm struggling to get the MJPEG Stream of the cameras to work in Home Assistant.

According to the [Static Stream Doco](https://viseron.netlify.app/components-explorer/components/ffmpeg#static-streams) i believe i have the correct config:

```
ffmpeg:
  camera:
    ir_1_cars:
      name: Cars
      host: !secret ip1
      port: !secret port1
      path: !secret path1
      username: !secret user1
      password: !secret pass1
      recorder:
        lookback: 15
        idle_timeout: 15
        retain: 7
        thumbnail:
          save_to_disk: true
      substream:
        path: !secret spath1
        port: !secret port1
        width: 704
        height: 480
        fps: 15
      mjpeg_streams:
        ir_1_cars_stream:
          width: 3840
          height: 2160
          draw_objects: true
          draw_zones: false
          draw_object_mask: false
        ir_1_cars_stream_small:
          width: 704
          height: 480
          draw_objects: true
          draw_zones: false
          draw_object_mask: false
```

i then use the [mjpeg integration](https://www.home-assistant.io/integrations/mjpeg) with:
`http://ip:port/ir_1_cars/mjpeg-streams/ir_1_cars_stream_small` or
`http://ip:port/ir_1_cars/mjpeg-streams/ir_1_cars_stream`

resulting log item

`
viseron  | [2023-01-06 17:46:40] [WARNING ] [tornado.access] - 404 GET /ir_1_cars/mjpeg-streams/ir_1_cars_stream (x.x.x.x) 60065.01ms
`
any idea on what i'm doing wrong? the HA machine can access the NVR no issues, the only error i get in HA is "Failed to Connect"

edit: GitHub being stupid and screwing up formatting :S
