### ISSUE TITLE
compreface not working while using a custom model

### ISSUE THREAD

**Issue by illuminathor** [roflcoopter/viseron#471]
Hi, thank you for your masterpiece! 

I try to use my model (yolov3) and face recognition (compreface). By default configuration, it's working well. But when I'm using my custom model, the compreface doesn't work. Here is my config.  

```
ffmpeg:
  camera:
    camera_1:
      name: Camera 1
      host: 192.168.1.64
      port: 554
      path: /Streaming/Channels/101
      username: admin
      password: admin123
      width: 1920
      height: 1080
      fps: 30
      protocol: rtsp
      codec: h264
      rtsp_transport: tcp
      mjpeg_streams:
        my_stream:
          width: 1920
          height: 1080
          draw_objects: true
        objects:
          draw_objects: true
          draw_zones: true
          draw_motion: true
          draw_motion_mask: true
          draw_object_mask: true

## Then add an object detector
darknet:
  object_detector:

    # Using this model, the compreface doesn't work

    model_path: /config/ppe/yolov3-pp_final.weights
    model_config: /config/ppe/yolov3-pp.cfg
    label_path: /config/ppe/coco.names

    # Using this model and changing the label to 'person', the compreface works well

    # model_path: /detectors/models/darknet/yolov3.weights
    # model_config: /detectors/models/darknet/yolov3.cfg
    # label_path: /detectors/models/darknet/coco.names
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 5
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: safety_helmet
            confidence: 0.9
            trigger_recorder: true

compreface:
  face_recognition:
    host: 192.168.88.160
    port: 8000
    recognition_api_key: MY-API-KEY
    face_plugins: age,gender
    train: true
    cameras:
      camera_1:
    labels:
      - safety_helmet

## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1
```

![default model](https://user-images.githubusercontent.com/9016936/214323533-13fdafa9-af8e-4913-a515-76e78457baab.png)

![custom model](https://user-images.githubusercontent.com/9016936/214323669-c3c522fc-cd05-45a6-9a6d-e46cf1bfdf8a.png)

I'm guessing this could happen because the model I'm using only detects overhead objects, which are helmets. Unlike the default person label which detects up to the face. looking forward to your advice.

Thanks.
