### ISSUE TITLE
Startup darknet: No section: 'net'

### ISSUE THREAD

**Issue by lyncker** [roflcoopter/viseron#476]
Hi, I am running Viseron for almost 2 years now , today I updated to the last image and started to adjust the configs... 
But even with the generated config , I am not able to start the darknet object detector : 

```
configparser.NoSectionError: No section: 'net'
viseron    | [2023-01-29 13:27:58] [ERROR   ] [viseron.components] - Uncaught exception setting up component darknet: No section: 'net'
```

I cant find any documented section net and no issues here, but it seems to be something very basic .. can anyone give me a hint how to resolve this?

my config: 

```
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: garage
      host: 192.168.2.122
      port: 554
      path: /h264Preview_01_main
      fps: 30
      substream:
        path: /h264Preview_01_sub
        port: 554
        width: 640
        height: 480
        fps: 15
##Then add an object detector
darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
```

**Comment by roflcoopter** [comment]
Seems to be something wrong with the yolo cfg file.

Can you exec into the container and show me the contents of the file `/detectors/models/darknet/default.cfg`?

**Comment by lyncker** [comment]
hmm ok , I dont find this ... maybe there is something wrong with my docker container?!

the docker os command shows the this : 

```
CONTAINER ID   IMAGE                        COMMAND   CREATED        STATUS       PORTS                      NAMES
f7cbd1e376b7   roflcoopter/viseron:latest   "/init"   19 hours ago   Up 3 hours   127.0.0.1:8888->8888/tcp   viseron
```
If I exec into this container I find only the following inside the viseron folder: 

```
-rw-r--r-- 1 root root  16K Dec 30 16:24 __init__.py
-rw-r--r-- 1 root root  535 Dec 30 16:24 __main__.py
drwxr-xr-x 2 root root 4.0K Jan 29 12:26 __pycache__
drwxr-xr-x 1 root root 4.0K Jan 29 12:26 components
-rw-r--r-- 1 root root 2.5K Dec 30 16:24 config.py
-rw-r--r-- 1 root root 3.6K Dec 30 16:24 const.py
drwxr-xr-x 1 root root 4.0K Jan 29 12:26 domains
-rw-r--r-- 1 root root 2.9K Dec 30 16:24 exceptions.py
drwxr-xr-x 3 root root 4.0K Dec 30 15:44 frontend
drwxr-xr-x 1 root root 4.0K Jan 29 12:26 helpers
-rw-r--r-- 1 root root 5.0K Dec 30 16:24 states.py
-rw-r--r-- 1 root root  203 Dec 30 16:24 types.py
drwxr-xr-x 1 root root 4.0K Jan 29 12:26 watchdog
```
inside components , there is a darknet folder with this content : 

```
-rw-r--r-- 1 root root  15K Dec 30 16:24 __init__.py
drwxr-xr-x 2 root root 4.0K Jan 29 12:35 __pycache__
-rw-r--r-- 1 root root 1.9K Dec 30 16:24 const.py
-rw-r--r-- 1 root root 8.0K Dec 30 16:24 darknet.py
-rw-r--r-- 1 root root 2.0K Dec 30 16:24 object_detector.py
```

thanks for your help ...

**Comment by lyncker** [comment]
Ok I got it...
there was a missconfig with my ehternet !! 
With this update I changed my Rasp vom Wifi to Ethernet due to some connection problems ...
So the wifi was still acitve and the ethernet had no IP.. after fixing it the darknet error is gone ... 
at least maybe this issue is good for all with missconfig in their ethernet running in such an error ;)

**Comment by roflcoopter** [comment]
very interesting, good job on clearing it up!

**Comment by lyncker** [comment]
well , I am sorry, but tonight when I came back from work to continue configuring the problem came back... maybe I was to fast this morning, not sure If I just overlooked it ... 

Anyway I reinstalled the container again checked all the pathes but it did not change anything, could we continue with this issue... 
here again the output : 

```
Traceback (most recent call last):
  File "/src/viseron/components/__init__.py", line 130, in setup_component
    result = component_module.setup(self._vis, config)
  File "/src/viseron/components/darknet/__init__.py", line 125, in setup
    vis.data[COMPONENT] = DarknetDNN(vis, config[CONFIG_OBJECT_DETECTOR])
  File "/src/viseron/components/darknet/__init__.py", line 219, in __init__
    super().__init__(vis, config)
  File "/src/viseron/components/darknet/__init__.py", line 164, in __init__
    self._model_width = int(model_config.get("net", "width"))
  File "/usr/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'net'
[2023-01-30 20:41:12] [ERROR   ] [viseron.components] - Uncaught exception setting up component darknet: No section: 'net'
None
[2023-01-30 20:41:12] [ERROR   ] [viseron.components] - Setup of component darknet failed
[2023-01-30 20:41:12] [ERROR   ] [viseron.components] - Failed setup of component darknet
```

**Comment by roflcoopter** [comment]
Too bad, could you show the contents of `/detectors/models/darknet/` folder?

**Comment by lyncker** [comment]
well, it does not exist: 

```
root@c9437c5d9941:/detectors/models# ls
edgetpu
```

**Comment by roflcoopter** [comment]
Just pulled the latest image and it works correctly for me.
Do you have any volume mappings that might cause trouble?

**Comment by lyncker** [comment]
hmm no ... I have 50% space free, no net drives or something like that ... 
here is my docker command: 

`sudo docker run -p8888:8888 --rm --privileged -v /camera:/recordings -v /home/pi/viseron/conf:/config -v /etc/localtime:/etc/localtime:ro -v /opt/vc/lib:/opt/vc/lib --name viseron --device=/dev/video10:/dev/video10 --device=/dev/video11:/dev/video11 --device=/dev/video12:/dev/video12 --device /dev/bus/usb:/dev/bus/usb roflcoopter/viseron:latest`

**Comment by roflcoopter** [comment]
Try to run these commands:
```bash
docker image rm roflcoopter/viseron:latest
docker pull roflcoopter/viseron:latest
```

**Comment by lyncker** [comment]
the image can only been deleted if I delete the container before ;
```
sudo docker image rm roflcoopter/viseron:latest
Error response from daemon: conflict: unable to remove repository reference "roflcoopter/viseron:latest" (must force) - container 77c0a4fe2713 is using its reference                                                                        d image f36be5f336a9
sudo docker rm viseron
sudo docker image rm roflcoopter/viseron:latest
Untagged: roflcoopter/viseron:latest
Untagged: roflcoopter/viseron@sha256:44b78d9cc78050865929c5a50b02f0a44158a52e57e3749a9638e45b11834c30
Deleted: sha256:f36be5f336a9750da132f17c3abc5d24b835f8a1d0e6a9bf0160039d7a8d760c
Deleted: sha256:6b312069c2fd4490bb7e3c208d5c2a08cb7971463757fc15946e9cfc546f5750
Deleted: sha256:df8426051fd915bac785c3fd938c2f731bfb41481b9bc0b2901ea8b843e09d41
Deleted: sha256:cb51ae800d82483c6d3141b0fc638734d47d1f5258c455b7f210f59a9c5f7965
Deleted: sha256:3a266b94148fc77c7415b0c3caed9f3e9588218179191edba1cf7ccd65e2543c
Deleted: sha256:84b03b3c8c5858279716bdb54525bbe207cbb81b14622f0f6b64bb8876a0f22b
Deleted: sha256:3f1893d6b2c42a4ca7e19ff14dab278e30e802bb0b3f6d4a3c543596a3c0e16b
Deleted: sha256:63913967c8089c09a44185834cabce4dedc4e667ceab166efdf081c0ee8d5a48
Deleted: sha256:e61eb9af4afe2449d616a050fadf51cefd932334d2eb1080b5e81b5af62c8080
Deleted: sha256:05b16577b184844e0a7fba7631f12edd4c48c98e912ab3d3f6678f5bea32fbf8
Deleted: sha256:5c19b3a0ee888e2c8ff987494030334f7bcb6eee221643f08333796a5340ac51
Deleted: sha256:3973da0faae1a82adf2195c512fd55412b60f7cf42382babe79b9ca4237710b0
Deleted: sha256:40bc184430b8644f2fe3405d03755f03394db202e0e7365bfbdd072c384482a6
Deleted: sha256:5ffd37ebd31ff256708e4d589016f36208eda82844100d913c5044f85ed417a7
Deleted: sha256:67719c2140481fae46f2dda775beb0d53446f57f25aadb4b18a190e5abb056fa
Deleted: sha256:00bb1990256480b5b8cb7da4d8c6363a98e40ac9c02b4a6f4b347748189132b1
Deleted: sha256:afa91a71ae56c23935cf5535bf910ebda6b5aa6bec0c7df1df2a50d9778d7b9f
Deleted: sha256:91a2900e6ecc95765d1f5491352288c9c89e2daa1d0cf520aff34a35da1c819c
Deleted: sha256:327d1b17a65eb5a417b38aedd47fb96f0baf538035f6bcdc94048086708c222d
Deleted: sha256:1e71d29cff57ce6df9509bc91955350d8cc8a6f68272d3507a00ecd3f7368593
Deleted: sha256:cda51051fc4d65f9c46a4ed4d02a9bc8c82dbf08efb7223f6afee4c7c25dbebe
Deleted: sha256:af771926610e9f9cfb6fd44971bcf983fa3c9757fa794c0b112f94253368b608
Deleted: sha256:52bb34000c31fe351c0df4250e3e50b9479699e9a3e1063caff624ced179960a
Deleted: sha256:98447d7e063597f03273ecac9c031e54ee9cbc73a1cfbb3e8e055461ae1fae27
Deleted: sha256:4fcc877bbdc14c60acf2ae5adff29d67e07979e656b0fc71b5b492a217ae84ab
Deleted: sha256:9f61ef2abd5d85fba23ead17e1aafe78aef32ce38f48af8de0cefb2694d68d31
sudo docker pull roflcoopter/viseron:latest
```
After this, the new image was installed but the error persist...

maybe there is something wrong with my compose.conf ? 

```
version: "2.4"
services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    restart: unless-stopped
    volumes:
      - /home/pi/viseron/cam:/recordings
      - /home/pi/viseron/conf:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    ports:
       - "127.0.0.1:8888:8888"
```

**Comment by roflcoopter** [comment]
My guess is that you have an old docker volume that is causing trouble.

You could try top clear everything out bu running `docker system prune --all --volumes`.
Be aware that it will remove any unused images and/or volumes

**Comment by krabbi** [comment]
Same for me, I've tried to install `roflcoopter/viseron:latest` and `roflcoopter/viseron:dev`, both had same result
`/detectors/models/` contains only `edgetpu`
I've tried clear everything as @roflcoopter proposed and it didn't help

my docker-compose
```
version: "2.4"

services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    volumes:
      - /Users/alex/viseron/recordings:/recordings
      - /Users/alex/viseron:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
```

I'm trying to run it on M1 mac
