### ISSUE TITLE
Error while decoding stream #0:0: Resource temporarily unavailable

### ISSUE THREAD

**Issue by simon511000** [roflcoopter/viseron#477]
First, thank you very much for your work on Viseron

When I try to put my camera (RTSP) on viseron, I have an infinite loading with this error message:

```
viseron  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
viseron  | [s6-init] ensuring user provided files have correct perms...exited 0.
viseron  | [fix-attrs.d] applying ownership & permissions fixes...
viseron  | [fix-attrs.d] done.
viseron  | [cont-init.d] executing container initialization scripts...
viseron  | [cont-init.d] 10-adduser: executing... 
viseron  | ************************ UID/GID *************************
viseron  | User uid:    0
viseron  | User gid:    0
viseron  | ************************** Done **************************
viseron  | [cont-init.d] 10-adduser: exited 0.
viseron  | [cont-init.d] 20-gid-video-device: executing... 
viseron  | [cont-init.d] 20-gid-video-device: exited 0.
viseron  | [cont-init.d] 30-edgetpu-permission: executing... 
viseron  | ************** Setting EdgeTPU permissions ***************
viseron  | Coral Vendor IDs:
viseron  | "1a6e"
viseron  | "18d1"
viseron  | No EdgeTPU USB device was found
viseron  | ************************** Done **************************
viseron  | [cont-init.d] 30-edgetpu-permission: exited 0.
viseron  | [cont-init.d] 40-set-env-vars: executing... 
viseron  | ****** Checking for hardware acceleration platforms ******
viseron  | OpenCL cannot be used
viseron  | VA-API cannot be used
viseron  | CUDA cannot be used
viseron  | *********************** Done *****************************
viseron  | [cont-init.d] 40-set-env-vars: exited 0.
viseron  | [cont-init.d] 50-check-if-rpi: executing... 
viseron  | ********** Checking if we are running on an RPi **********
viseron  | Running on an RPi4
viseron  | *********************** Done *****************************
viseron  | [cont-init.d] 50-check-if-rpi: exited 0.
viseron  | [cont-init.d] 55-check-if-jetson: executing... 
viseron  | ****** Checking if we are running on a Jetson Board ******
viseron  | Not running on any supported Jetson board
viseron  | *********************** Done *****************************
viseron  | [cont-init.d] 55-check-if-jetson: exited 0.
viseron  | [cont-init.d] 60-ffmpeg-path: executing... 
viseron  | ****************** Getting FFmpeg path *******************
viseron  | FFmpeg path: /home/abc/bin/ffmpeg
viseron  | *********************** Done *****************************
viseron  | [cont-init.d] 60-ffmpeg-path: exited 0.
viseron  | [cont-init.d] 70-gstreamer-path: executing... 
viseron  | ***************** Getting GStreamer path *****************
viseron  | GStreamer path: /usr/bin/gst-launch-1.0
viseron  | *********************** Done *****************************
viseron  | [cont-init.d] 70-gstreamer-path: exited 0.
viseron  | [cont-init.d] done.
viseron  | [services.d] starting services
viseron  | [services.d] done.
viseron  | [2023-01-31 07:03:10] [INFO    ] [viseron.core] - -------------------------------------------
viseron  | [2023-01-31 07:03:10] [INFO    ] [viseron.core] - Initializing Viseron
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up component data_stream
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setup of component data_stream took 0.0 seconds
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up component webserver
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setup of component webserver took 0.0 seconds
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up component nvr
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up component mqtt
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setup of component nvr took 0.0 seconds
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up component ffmpeg
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setup of component ffmpeg took 0.0 seconds
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up component mog2
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setup of component mog2 took 0.0 seconds
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setup of component mqtt took 0.0 seconds
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up domain camera for component ffmpeg with identifier garage
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up domain motion_detector for component mog2 with identifier garage
viseron  | [2023-01-31 07:03:11] [INFO    ] [viseron.components] - Setting up domain nvr for component nvr with identifier garage
viseron  | [2023-01-31 07:03:14] [WARNING ] [viseron.components.ffmpeg.stream.garage] - Container mp4 does not support pcm_alaw audio codec, using mkv instead. Consider changing extension in your config.
viseron  | [2023-01-31 07:03:14] [INFO    ] [viseron.components] - Setup of domain camera for component ffmpeg with identifier garage took 2.5 seconds
viseron  | [2023-01-31 07:03:14] [INFO    ] [viseron.components] - Setup of domain motion_detector for component mog2 with identifier garage took 0.0 seconds
viseron  | [2023-01-31 07:03:14] [INFO    ] [viseron.components.nvr.nvr.garage] - Object detector is disabled
viseron  | [2023-01-31 07:03:14] [INFO    ] [viseron.components.nvr.nvr.garage] - NVR for camera Garage initialized
viseron  | [2023-01-31 07:03:14] [INFO    ] [viseron.components] - Setup of domain nvr for component nvr with identifier garage took 0.0 seconds
viseron  | [2023-01-31 07:03:14] [INFO    ] [viseron.core] - Viseron initialized in 3.8 seconds
viseron  | [2023-01-31 07:03:25] [ERROR   ] [viseron.components.ffmpeg.stream.garage] - Error while decoding stream #0:0: Resource temporarily unavailable
```

Here is my config :
```
ffmpeg:
  camera:
    garage:
      name: Garage
      host: 192.168.1.58
      port: 554
      path: /stream1
      username: *****
      password: *****
      width: 1920
      height: 1080

mqtt:
  broker: localhost
  port: 1883
  username: *****
  password: *****
  home_assistant:

nvr:
  garage:
```

and my docker compose file : 
```
version: "2.4"
services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    network_mode: host
    volumes:
      - ./data/recordings:/recordings
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video11
      - /dev/video12:/dev/video12
      - /dev/bus/usb:/dev/bus/usb
    ports:
      - 8888:8888
    privileged: true
```

I think it's a problem of viseron and not of my camera because it works perfectly on frigate with this config:
```
mqtt:
  host: localhost
  port: 1883
  user: *****
  password: *****

cameras:
  garage:
    ffmpeg:
      inputs:
        - path: rtsp://*****:*****@192.168.1.58:554/stream1
    rtmp:
      enabled: True
    detect:
      width: 1920
      height: 1080
```
