### ISSUE TITLE
Recordings not getting saved

### ISSUE THREAD

**Issue by justdummyuser** [roflcoopter/viseron#478]
Hi, 

New to Viseron, starting with default configuration file in GUI. Testing with NVIDIA CUDA image and 2 cameras. Object detection seems to be working but recordings are not getting saved. Went through docs but still couldnt figure out. Getting below error -

```
viseron  | [2023-02-04 18:46:13] [INFO    ] [viseron.components.ffmpeg.recorder.camera_1] - Starting recorder
viseron  | [2023-02-04 18:46:14] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 9
viseron  | [2023-02-04 18:46:15] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 8
viseron  | [2023-02-04 18:46:16] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 7
viseron  | [2023-02-04 18:46:17] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 6
viseron  | [2023-02-04 18:46:18] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 5
viseron  | [2023-02-04 18:46:19] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 4
viseron  | [2023-02-04 18:46:20] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 3
viseron  | [2023-02-04 18:46:21] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 2
viseron  | [2023-02-04 18:46:22] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 1
viseron  | [2023-02-04 18:46:23] [INFO    ] [viseron.components.nvr.nvr.camera_1] - Stopping recording in: 0
viseron  | [2023-02-04 18:46:23] [INFO    ] [viseron.components.ffmpeg.recorder.camera_1] - Stopping recorder
viseron  | /recordings/camera_1/2023-02-04/18:46:13.mp4: Invalid argument
viseron  | [2023-02-04 18:46:28] [ERROR   ] [viseron.components.ffmpeg.recorder.camera_1] - Failed to concatenate segments: Command '['ffmpeg', '-hide_banner', '-loglevel', 'error', '-y', '-protocol_whitelist', 'file,pipe', '-f', 'concat', '-safe', '0', '-i', '-', '-c:v', 'h264', '-c:a', 'copy', '-movflags', '+faststart', '/recordings/camera_1/2023-02-04/18:46:13.mp4']' returned non-zero exit status 1.
```

Docker Compose -

```
version: "2.4"

services:
  viseron:
    image: roflcoopter/amd64-cuda-viseron:latest
    container_name: viseron
    restart: unless-stopped
    privileged: true
    volumes:
      - /media/data/viseronrec:/recordings
      - ~/viseron/config.yml:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    runtime: nvidia
```

Config.yml -

```
ffmpeg:
  camera:
    camera_1:  
      name: Front_View
      host: 192.168.X.X
      port: 554
      path: /Streaming/Channels/102
      username: XXXX
      password: XXXX
      stream_format: rtsp
      fps: 6
      recorder:
        codec: h264

    camera_2:   
      name: Back_View
      host: 192.168.X.X
      port: 554
      path: /Streaming/Channels/102
      username: XXXX
      password: XXXX
      stream_format: rtsp
      fps: 6
      recorder:
        codec: h264

darknet:
  object_detector:
    cameras:
      camera_1:  
        fps: 1
        scan_on_motion_only: false  
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

      camera_2:  
        fps: 1
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

mog2:
  motion_detector:
    cameras:
      camera_2: 
        fps: 1

nvr:
  camera_1: 
  camera_2: 

```

Am i making any mistake?
