### ISSUE TITLE
Error: Failed to Retrieve Result for Object Detector

### ISSUE THREAD

**Issue by tokenwizard** [roflcoopter/viseron#486]
I've set up my docker-compose.yml with the USB Bus for my Coral device and it is being correctly recognized at startup, per the console messages:
![image](https://user-images.githubusercontent.com/24832561/218500763-1cee147f-57fe-43b1-ad2c-3ec3f53ed271.png)

I have also added a few cameras to the config file, and the snapshots and live views are working for all of them.
However, in the console I notice a lot of errors that make me think the object detection/recorder is not going to work reliably:
![image](https://user-images.githubusercontent.com/24832561/218501060-4583b6cc-14e5-489d-9cc8-f21c0ee347ae.png)

These object detector errors repeat indefinitely. 

Any thoughts on these errors?

Here is my docker-compose.yml:

```
version: "3.7"
services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    volumes:
      - ./recordings:/recordings
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    devices:
      - /dev/bus/usb/003
```

And here is my config.yaml:

```
# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed he>
# See the documentation for the full list of configuration options.

## Start by adding some cameras
ffmpeg:
  camera:
    1_front_ptz:  # This value has to be unique across all cameras
      name: "Front Yard PTZ"
      host: 192.168.12.87
      port: 554
      path: /1
#      username: 
#      password: 

    2_front_left:  # This value has to be unique across all cameras
      name: "Front Left"
      host: 192.168.0.22
      port: 554
      path: /stream0
      username: <redacted>
      password: <redacted>
      width: 1920
      height: 1080
      fps: 4

    3_front_right:
      name: "Front Right"
      host: 192.168.0.27
      port: 554
      path: /stream0
      username: <redacted>
      password: <redacted>
      width: 1920
      height: 1080
      fps: 4

#    4_street_left:
#      name: "Street Left"
#      host: 192.168.12.85
#      port: 554
#      path: /0/video1
#      username: <redacted>
#      password: <redacted>
#      width: 1920
#      height: 1080
#      fps: 4

    5_street_right:
      name: "Street Right"
      host: 192.168.12.86
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      username: <redacted>
      password: <redacted>
      width: 1920
      height: 1080
      fps: 4

## Then add an object detector
darknet:
  object_detector:
    cameras:
     1_front_ptz:  
        fps: 2
        scan_on_motion_only: false  
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

     2_front_left:  
        fps: 2
        scan_on_motion_only: false  
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
     3_front_right:  
        fps: 2
        scan_on_motion_only: false  
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
     5_street_right:  
        fps: 2
        scan_on_motion_only: false  
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

    
## You can also use motion detection
#mog2:
#  motion_detector:
#    cameras:
#      camera_2:  # Attach detector to the configured camera_2 above
#        fps: 1


## To tie everything together we need to configure one more component.
nvr:
  1_front_ptz
  2_front_left
  3_front_right
  4_street_left
  5_street_right

# Now you can restart Viseron and you should be good to go!

```

**Comment by roflcoopter** [comment]
Thanks for trying Viseron!

In order to use the Coral, you need to be using the `edgetpu` component.
`darknet` uses your CPU (or GPU if you have one)

It should be as simple as swapping out `darknet` for `edgetpu` like this:
```yaml
edgetpu:
  object_detector:
    cameras:
     1_front_ptz:  
        fps: 2
        scan_on_motion_only: false  
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
```
