### ISSUE TITLE
Distribute utilization across multiple GPUs

### ISSUE THREAD

**Issue by mafifafm** [roflcoopter/viseron#491]
Hi,
We have tried to use Viseron using two NVIDIA RTX 3090 GPUs using Darknet as object detection. The result is viseron utilization only using one GPU. We are using 32 RTSP Stream from the same URL (rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4) as camera. The following picture is a screenshot of the GPU utilization used using `nvtop`.
![WhatsApp Image 2023-02-23 at 22 06 57](https://user-images.githubusercontent.com/54896668/220952399-eed89204-55c1-45b9-adb3-de80e7bb2de2.jpeg)

The image below is the GPUs utilization using `nvidia-smi` command.
![WhatsApp Image 2023-02-23 at 22 24 54](https://user-images.githubusercontent.com/54896668/220953861-6c1f4616-440c-40df-9853-fba654e6b456.jpeg)

To install the Viseron on docker, we are using docker compose with the following script.

```
version: "2.4"

services:
  viseron:
    image: roflcoopter/amd64-cuda-viseron:latest
    container_name: viseron
    volumes:
      - {recordings path}:/recordings
      - {config path}:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:8888
    runtime: nvidia
    environments:
      - NVIDIA_VISIBLE_DEVICES=all
```

Is the mechanism of Viseron prioritized using one of the GPUs until the utility is full and then using other units? Or is there something wrong with our configuration?
