### ISSUE TITLE
Consolidate duplicate event recordings

### ISSUE THREAD

**Issue by netpro25** [roflcoopter/viseron#494]
Thanks for your great work on Viseron. I've just started to set it up with a test camera and noticed that I'm seeing duplicate recordings for the same time frame showing the events. Is there a way to have Viseron combine all these into a single clip? Is my config a miss?

<img width="1662" alt="image" src="https://user-images.githubusercontent.com/14352695/222545061-184bbdb1-9277-4aa5-b925-85b3a63bab5f.png">

```yaml
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Drive
      host: 192.168.0.204
      port: 554
      path: /cam/realmonitor?channel=1&subtype=0
      fps: 9
      recorder:
        idle_timeout: 1
        codec: h264
      username: admin
      password: supersecret

darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: dog
            confidence: 0.7
            trigger_recorder: false
          - label: person
            confidence: 0.75
            trigger_recorder: true
          - label: car
            confidence: .7
            trigger_recorder: true
            require_motion: true
          - label: truck
            confidence: .7
            trigger_recorder: true
            require_motion: true            

mog2:
  motion_detector:
    cameras:
      camera_1:
        fps: 1

nvr:
  camera_1:  # Run NVR for camera_1

mqtt:
  broker: mosquitto
  port: 1883
  username: homeassistant
  password: supersecret
  home_assistant:
```
