### ISSUE TITLE
2.1.1 only saving latest recordings

### ISSUE THREAD

**Issue by Lunuit** [roflcoopter/viseron#520]
Running that 2.1.1 if i view recordings it will only show the latest recordings not previous ones.
previous recordings are still being written to disk I just can't view them through the gui

heres my config: 
```
ffmpeg:
  camera:
    camera_1:
      name: Front Door
      host: 172.21.5.1
      port: 554
      path: /
      username: admin
      password: ***
      fps: 30
    
    camera_3:
      name: W Garage
      host: 172.21.5.3
      port: 554
      path: /h264Preview_01_sub
      username: admin
      password: ***
      fps: 15


    camera_5:
      name: E Back Yard
      host: 172.21.5.5
      port: 554
      path: /h264Preview_01_main
      username: admin
      password: ***
      fps: 30

darknet:
  object_detector:
    cameras:
      camera_1:
        fps: 3
        scan_on_motion_only: false
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
      camera_5: 
        fps: 3
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true

mog2:
  motion_detector:
    cameras:
      camera_1: 
        fps: 2
      camera_3:
        fps: 2
        trigger_recorder: true
      camera_5:
        fps: 2


nvr:
  camera_1: 
  camera_3:
  camera_5:
```
