### ISSUE TITLE
Mask Coordinates for Darknet not working as expected

### ISSUE THREAD

**Issue by tokenwizard** [roflcoopter/viseron#544]
I'm trying to follow along the documentation, and I think this is what I'm supposed to plug in for the mask coordinates. 

The Documentation does not show the mask/coordinates pieces within the overall config file, so I'm not sure if my placement is appropriate, but the Configuration page does not show any errors. 

I used the image-map.net link and drew a rectangle bounding box that spit out these coordinates and then plugged them into the config. 

![image](https://user-images.githubusercontent.com/24832561/231539978-9bdd2bf0-0377-498c-a981-6868306008a4.png)

When I restart, I am getting an error related to these values and Darknet fails to load:

![image](https://user-images.githubusercontent.com/24832561/231540197-a5aae719-f727-4568-bbae-994d897919f5.png)

**Comment by roflcoopter** [comment]
Yeah this could be a bit more clear in the docs.

You need to use the "poly" option when creating the mask, not the "rect" option.
Viseron needs at least 3 mask points.

Will make sure to describe this better.

**Comment by tokenwizard** [comment]
I've updated my mask coordinates like so:
![image](https://user-images.githubusercontent.com/24832561/231814283-3d16be57-13f4-4061-acd1-d55013bde31b.png)

But I'm still getting this error at startup:
![image](https://user-images.githubusercontent.com/24832561/231814399-22e5afd2-a60f-4c8c-aa55-e06d0e6fad15.png)

**Comment by roflcoopter** [comment]
the value of mask has to be a list, like so:
```yaml
darknet:
  object_detector:
    cameras:
      camera_1:
        ...
        mask:
          - coordinates:
              - x: 400
                y: 200
              - x: 1000
                y: 200
              - x: 1000
                y: 750
              - x: 400
                y: 750
```

If you paste your config between triple backticks (```) i can help you fix the format.
Will add an example config to the docs as well for clarity.

**Comment by tokenwizard** [comment]
Here is the detector-related settings. The "streetleft" is the camera that has the mask.

```## Then add an object detector
darknet:
  object_detector:
    cameras:
      1_driveway:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: true  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.70
            trigger_recorder: true
          - label: cat
            confidence: 0.70
            trigger_recorder: true

      2_frontleft:  # Attach detector to the configured camera_2 above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
          - label: cat
            confidence: 0.70
            trigger_recorder: true        

      3_frontright:  # Attach detector to the configured camera_2 above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
          - label: cat
            confidence: 0.70
            trigger_recorder: true     

      4_streetleft:  # Attach detector to the configured camera_2 above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
          - label: cat
            confidence: 0.70
            trigger_recorder: true 
        mask: 
          coordinates:
            - x: 1911
              y: 734
            - x: 1727
              y: 795
            - x: 1660
              y: 1056
            - x: 1904
              y: 1063

      5_streetright:  # Attach detector to the configured camera_2 above
        fps: 1
        scan_on_motion_only: true
        labels:
          - label: person
            confidence: 0.75
            trigger_recorder: true
          - label: cat
            confidence: 0.70
            trigger_recorder: true 

      6_porch:  # Attach detector to the configured camera_1 above
        fps: 1
        scan_on_motion_only: true  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.70
            trigger_recorder: true
          - label: cat
            confidence: 0.70
            trigger_recorder: true
```

**Comment by gofaster** [comment]
I think there needs to be a dash in front of  `coordinates` to indicate a list .

```
        mask: 
          - coordinates:
            - x: 1911
              y: 734
            - x: 1727
              y: 795
            - x: 1660
              y: 1056
            - x: 1904
              y: 1063
```
