### ISSUE TITLE
Security Camera with green distortion

### ISSUE THREAD

**Issue by Dvalin21** [roflcoopter/viseron#597]
![Security Camera1](https://user-images.githubusercontent.com/7469013/236602474-78f2c135-b9a2-4273-9f18-f00eb386aa56.jpg)

I just added this new camera
[BESDER](https://www.aliexpress.us/item/3256804881846727.html?spm=a2g0o.order_list.order_list_main.52.21ef1802WHoLU1&gatewayAdapt=glo2usa)
Resolution 3632x1080 H265

However I get this green bar (possibly ffmpeg) when I connect this camera. I don't see any logs. Thanks!

**Comment by fanningert** [comment]
Test adding width and hight to the camera settings. But check the correct resultion with ffprobe and use the correct size values. I had the same problem, because one of my camera has a strange resolution "1920x1072" and in my first try I set the size to "1920x1080". The result was the same effect like you are having.
```
ffmpeg:
  camera:
    camgarage01:
      name: camgarage01
      host: xxx
      port: xxx
      path: xxx
      protocol: rtsp
      width: 3632
      height: 1080
```
