### ISSUE TITLE
Setting up streams from motion eye (Config help)

### ISSUE THREAD

**Issue by JoeGandy** [roflcoopter/viseron#6]
Hey, Might be an obvious one
Description of streaming url from motioneye:

> Streaming URL provides MJPEG streaming. It can be used as a source for other applications that deal with video streams and know how to handle MJPEGs, or it can be used as the src attribute of an <img> HTML tag.

I'm given the url in the format `http://192.168.1.111:8082`

Initial config for testing:

```
# See the README for the full list of configuration options.
cameras:
  - name: front_room
    host: 192.168.1.111
    port: 6082
    path: /
    width: 640
    height: 360
    fps: 15
    motion_detection:
      interval: 1
      trigger: false
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.8
```

Then I get 
> [2020-09-04 08:20:01] [lib.camera.front_room ] [ERROR ] - Error starting decoder pipe! rtsp://None:None@192.168.1.111:6082/: Invalid data found when processing input

in the docker logs

Do you have any advice for setting this up?
