### ISSUE TITLE
UnboundLocalError: local variable 'stream_codec' referenced before assignment

### ISSUE THREAD

**Issue by danobot** [roflcoopter/viseron#60]
Facing this issue in docker on a new installation. Logs show `UnboundLocalError: local variable 'stream_codec' referenced before assignment` error which seems strange because its such an obvious programming issue.

```
  viseron:
    container_name: viseron
    restart: unless-stopped
    privileged: true
    shm_size: '1g' 
    image: roflcoopter/viseron
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/Viseron:/config
      - /mnt/disks/Unprotected_Data/viseron_footage:/recordings
    ports:
      - "6354:5000"
```

```
viseron       | 2020-10-12T13:48:48.614216364Z [2020-10-12 21:48:48] [root                    ] [INFO    ] - -------------------------------------------
viseron       | 2020-10-12T13:48:48.614253118Z [2020-10-12 21:48:48] [root                    ] [INFO    ] - Initializing...
viseron       | 2020-10-12T13:48:48.614263307Z [2020-10-12 21:48:48] [root                    ] [DEBUG   ] - Starting cleanup scheduler
viseron       | 2020-10-12T13:48:48.692631260Z [2020-10-12 21:48:48] [root                    ] [DEBUG   ] - Running initial cleanup
viseron       | 2020-10-12T13:48:48.692662929Z [2020-10-12 21:48:48] [lib.cleanup             ] [DEBUG   ] - Running cleanup
viseron       | 2020-10-12T13:48:48.696407354Z [2020-10-12 21:48:48] [lib.detector            ] [DEBUG   ] - Initializing object detector darknet
viseron       | 2020-10-12T13:48:49.368802094Z [2020-10-12 21:48:49] [lib.detector            ] [DEBUG   ] - Object detector initialized
viseron       | 2020-10-12T13:48:49.369012883Z [2020-10-12 21:48:49] [root                    ] [INFO    ] - Initializing NVR threads
viseron       | 2020-10-12T13:48:49.369560515Z [2020-10-12 21:48:49] [lib.nvr.amcrest         ] [DEBUG   ] - Initializing NVR thread
viseron       | 2020-10-12T13:48:49.369775890Z [2020-10-12 21:48:49] [lib.camera.amcrest      ] [DEBUG   ] - Initializing ffmpeg RTSP pipe
viseron       | 2020-10-12T13:48:49.379443323Z Traceback (most recent call last):
viseron       | 2020-10-12T13:48:49.379457711Z   File "viseron.py", line 177, in <module>
viseron       | 2020-10-12T13:48:49.380221172Z     Viseron()
viseron       | 2020-10-12T13:48:49.380230946Z   File "viseron.py", line 69, in __init__
viseron       | 2020-10-12T13:48:49.380267081Z     mqtt_queue=mqtt_queue,
viseron       | 2020-10-12T13:48:49.380273730Z   File "/src/viseron/lib/nvr.py", line 153, in __init__
viseron       | 2020-10-12T13:48:49.381212270Z     self.camera = FFMPEGCamera(config, frame_buffer)
viseron       | 2020-10-12T13:48:49.381222604Z   File "/src/viseron/lib/camera.py", line 127, in __init__
viseron       | 2020-10-12T13:48:49.381579509Z     self.start_decoder()
viseron       | 2020-10-12T13:48:49.381591819Z   File "/src/viseron/lib/camera.py", line 157, in start_decoder
viseron       | 2020-10-12T13:48:49.381696532Z     self.stream_codec = stream_codec
viseron       | 2020-10-12T13:48:49.381707837Z UnboundLocalError: local variable 'stream_codec' referenced before assignment
viseron       | 2020-10-12T13:48:51.588790320Z [2020-10-12 21:48:51] [root                    ] [INFO    ] - -------------------------------------------
viseron       | 2020-10-12T13:48:51.588811224Z [2020-10-12 21:48:51] [root                    ] [INFO    ] - Initializing...
viseron       | 2020-10-12T13:48:51.588833235Z [2020-10-12 21:48:51] [root                    ] [DEBUG   ] - Starting cleanup scheduler
viseron       | 2020-10-12T13:48:51.645534887Z [2020-10-12 21:48:51] [root                    ] [DEBUG   ] - Running initial cleanup
viseron       | 2020-10-12T13:48:51.645554866Z [2020-10-12 21:48:51] [lib.cleanup             ] [DEBUG   ] - Running cleanup
viseron       | 2020-10-12T13:48:51.646938350Z [2020-10-12 21:48:51] [lib.detector            ] [DEBUG   ] - Initializing object detector darknet
viseron       | 2020-10-12T13:48:51.770931812Z [2020-10-12 21:48:51] [lib.detector            ] [DEBUG   ] - Object detector initialized
viseron       | 2020-10-12T13:48:51.771180352Z [2020-10-12 21:48:51] [root                    ] [INFO    ] - Initializing NVR threads
viseron       | 2020-10-12T13:48:51.771394086Z [2020-10-12 21:48:51] [lib.nvr.amcrest         ] [DEBUG   ] - Initializing NVR thread
viseron       | 2020-10-12T13:48:51.771720663Z [2020-10-12 21:48:51] [lib.camera.amcrest      ] [DEBUG   ] - Initializing ffmpeg RTSP pipe
```

Config.yml
```yaml

# See the README for the full list of configuration options.
cameras:
  - name: Amcrest
    host: 10.1.1.9
    port: 554
    username: *****
    password: ******
    path: /cam/realmonitor?channel=1&subtype=0
    width: 1920
    height: 1080
    stream_format: rtsp
    publish_image: true
    fps: 20
recorder:
  lookback: 10
  timeout: 10
  retain: 7
  folder: /recordings
motion_detection:
  interval: 1
  trigger_detector: true
  timeout: true
  max_timeout: 30
  width: 300
  height: 300
  area: 0.1
  frames: 3
logging:
  level: debug

# MQTT is optional
# mqtt:
#  broker: tower.local
#  port: 1886
#  client_id: viseron
#  username: hassbian
#  password: "3435"
```
