### ISSUE TITLE
FFMPEG [2023-05-23 11:25:52] [ERROR   ] [viseron.components.ffmpeg.stream.viseron_camera] - Retrying None in 4.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 30s.

### ISSUE THREAD

**Issue by Abkob** [roflcoopter/viseron#609]
[2023-05-23 11:25:52] [ERROR   ] [viseron.components.ffmpeg.stream.viseron_camera] - Retrying None in 4.0 seconds as it raised FFprobeTimeout: FFprobe command timed out after 30s. 
I am trying to connect camera :
ffmpeg:
  camera:
    viseron_camera:
      name: Camera 1
      host: 192.168.1.XX
      port: 554
      path: /profile1
      username: admin
      password: adminXX     **BUT ITS NOT WOKRING KEEPS GIVING THE SAME **ERROR****

**Comment by roflcoopter** [comment]
You can bypass the FFprobe step by specifying `width`, `height`, `fps`, `codec` and `audio_codec`.
Lets say your camera is 1920x1080@6 fps with h264 codec and no audio, the config looks like this:

```yaml
ffmpeg:
  camera:
    viseron_camera:
      name: Camera 1
      host: 192.168.1.XX
      port: 554
      path: /profile1
      username: admin
      password: adminXX
      width: 1920
      height: 1080
      fps: 6
      codec: h264
      audio_codec: null
```
