### ISSUE TITLE
Not recording any clips to /recordings

### ISSUE THREAD

**Issue by danobot** [roflcoopter/viseron#62]
It is not recording motion/object detection clips to the `/recordings` directory in docker, the volume mapping exists and I tried with both `privileged` and unprivileged.

Docker compose:
```
 viseron:
    container_name: viseron
    restart: unless-stopped
    # privileged: true
    shm_size: '1g' 
    image: roflcoopter/viseron:1.6.1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/user/appdata/Viseron:/config
      - /mnt/disks/Unprotected_Data/viseron_footage:/recordings
```

Config
```

# See the README for the full list of configuration options.
cameras:
  - name: Amcrest
    host: 10.1.1.9
    port: 554
    username: *****
    password: *****
    path: /cam/realmonitor?channel=1&subtype=0
    width: 1920
    height: 1080
    stream_format: rtsp
    # rtsp_transport: http
    # ffmpeg_loglevel: debug

    publish_image: true
    # fps: 20
    logging:
      level: debug
recorder:
  lookback: 2
  timeout: 10
  retain: 7
  folder: /recordings
  logging:
    level: debug
motion_detection:
  interval: 0.5
  # trigger_detector: True
  timeout: true
  max_timeout: 30
  width: 300
  height: 300
  area: 0.1
  frames: 1
object_detection:
  type: darknet
  interval: 6
  labels:
    - label: person
      confidence: 0.5
      height_min: 0.1481
      height_max: 0.7
      width_min: 0.0598
      width_max: 0.36
    - label: truck
      confidence: 0.8  
post_processors:
  face_recognition:
    type: dlib
    expire_after: 10
  logging:
    level: debug  
logging:
  level: debug

```

Logs:
```
WARNING: Some networks were defined but are not used by any service: public
Attaching to viseron
viseron       | 2020-10-16T14:58:47.630917695Z [2020-10-16 22:58:47] [root                    ] [INFO    ] - -------------------------------------------
viseron       | 2020-10-16T14:58:47.630946336Z [2020-10-16 22:58:47] [root                    ] [INFO    ] - Initializing...
viseron       | 2020-10-16T14:58:47.630961560Z [2020-10-16 22:58:47] [root                    ] [DEBUG   ] - Starting cleanup scheduler
viseron       | 2020-10-16T14:58:47.713955694Z [2020-10-16 22:58:47] [root                    ] [DEBUG   ] - Running initial cleanup
viseron       | 2020-10-16T14:58:47.713977819Z [2020-10-16 22:58:47] [lib.cleanup             ] [DEBUG   ] - Running cleanup
viseron       | 2020-10-16T14:58:47.717161161Z [2020-10-16 22:58:47] [lib.detector            ] [DEBUG   ] - Initializing object detector darknet
viseron       | 2020-10-16T14:58:48.285903470Z [2020-10-16 22:58:48] [lib.detector            ] [DEBUG   ] - Object detector initialized
viseron       | 2020-10-16T14:58:48.286152018Z [2020-10-16 22:58:48] [lib.post_processors     ] [DEBUG   ] - Initializing post processor face_recognition
viseron       | 2020-10-16T14:58:50.786464224Z [2020-10-16 22:58:50] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Initializing dlib
viseron       | 2020-10-16T14:58:50.786492650Z [2020-10-16 22:58:50] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Training faces...
viseron       | 2020-10-16T14:58:50.786812081Z [2020-10-16 22:58:50] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Training face daniel
viseron       | 2020-10-16T14:58:52.062254705Z [2020-10-16 22:58:52] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Training complete
viseron       | 2020-10-16T14:58:52.062427904Z [2020-10-16 22:58:52] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - dlib initialized
viseron       | 2020-10-16T14:58:52.062732492Z [2020-10-16 22:58:52] [lib.post_processors     ] [DEBUG   ] - Post processor face_recognition initialized
viseron       | 2020-10-16T14:58:52.062752251Z [2020-10-16 22:58:52] [root                    ] [INFO    ] - Initializing NVR threads
viseron       | 2020-10-16T14:58:52.063289787Z [2020-10-16 22:58:52] [lib.nvr.amcrest         ] [DEBUG   ] - Initializing NVR thread
viseron       | 2020-10-16T14:58:52.063335303Z [2020-10-16 22:58:52] [lib.camera.amcrest      ] [DEBUG   ] - Initializing ffmpeg RTSP pipe
viseron       | 2020-10-16T14:58:52.063420559Z [2020-10-16 22:58:52] [lib.camera.amcrest      ] [DEBUG   ] - Getting stream information for rtsp://admin:danielx95@10.1.1.9:554/cam/realmonitor?channel=1&subtype=0
viseron       | 2020-10-16T14:59:00.001719355Z [2020-10-16 22:59:00] [lib.camera.amcrest      ] [DEBUG   ] - Resolution: 1920x1080 @ 20.0 FPS
viseron       | 2020-10-16T14:59:00.001859377Z [2020-10-16 22:59:00] [lib.camera.amcrest      ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -rtsp_transport tcp -i rtsp://****:****@10.1.1.9:554/cam/realmonitor?channel=1&subtype=0 -f rawvideo -pix_fmt nv12 pipe:1
viseron       | 2020-10-16T14:59:00.002193886Z [2020-10-16 22:59:00] [lib.motion.amcrest      ] [DEBUG   ] - Initializing motion detector
viseron       | 2020-10-16T14:59:00.002248209Z [2020-10-16 22:59:00] [lib.motion.amcrest      ] [DEBUG   ] - Motion detector initialized
[2020-10-16 22:59:00] [lib.camera.amcrest] [DEBUG   ] - Starting decoder thread, message repeated 2 times
viseron       | 2020-10-16T14:59:00.003069636Z [2020-10-16 22:59:00] [lib.nvr.amcrest         ] [DEBUG   ] - Starting camera
viseron       | 2020-10-16T14:59:00.003248921Z [2020-10-16 22:59:00] [lib.camera.amcrest      ] [DEBUG   ] - Starting capture thread
viseron       | 2020-10-16T14:59:00.003407248Z [2020-10-16 22:59:00] [lib.recorder.amcrest    ] [DEBUG   ] - Initializing ffmpeg recorder
viseron       | 2020-10-16T14:59:00.003498986Z [2020-10-16 22:59:00] [lib.camera.amcrest      ] [DEBUG   ] - Performing a sanity check on the ffmpeg command
viseron       | 2020-10-16T14:59:00.003617821Z [2020-10-16 22:59:00] [lib.recorder.amcrest    ] [DEBUG   ] - FFMPEG encoder command: ffmpeg -hide_banner -loglevel error -f rawvideo -pix_fmt nv12 -s:v <width>x<height> -r <fps> -i pipe:0 -y <file>
viseron       | 2020-10-16T14:59:00.003694063Z [2020-10-16 22:59:00] [lib.nvr.amcrest         ] [DEBUG   ] - NVR thread initialized
viseron       | 2020-10-16T14:59:00.003940843Z [2020-10-16 22:59:00] [lib.nvr.amcrest         ] [DEBUG   ] - Waiting for first frame
viseron       | 2020-10-16T14:59:00.004092922Z [2020-10-16 22:59:00] [root                    ] [INFO    ] - Initialization complete
viseron       | 2020-10-16T14:59:06.513845552Z [2020-10-16 22:59:06] [lib.camera.amcrest      ] [DEBUG   ] - Running object detection at 6.0s interval, every 120 frame(s)
viseron       | 2020-10-16T14:59:06.513920023Z [2020-10-16 22:59:06] [lib.camera.amcrest      ] [DEBUG   ] - Running motion detection at 0.5s interval, every 10 frame(s)
viseron       | 2020-10-16T14:59:09.815235291Z [2020-10-16 22:59:09] [lib.nvr.amcrest         ] [DEBUG   ] - First frame received
viseron       | 2020-10-16T14:59:39.310073054Z [2020-10-16 22:59:39] [lib.nvr.amcrest.motion  ] [DEBUG   ] - Consecutive frames with motion: 1, max area size: 0.30167
viseron       | 2020-10-16T14:59:39.310121548Z [2020-10-16 22:59:39] [lib.nvr.amcrest.motion  ] [DEBUG   ] - Motion detected
viseron       | 2020-10-16T14:59:39.310202362Z [2020-10-16 22:59:39] [lib.nvr.amcrest         ] [DEBUG   ] - Starting object detector
viseron       | 2020-10-16T14:59:39.444672860Z [2020-10-16 22:59:39] [lib.nvr.amcrest.motion  ] [DEBUG   ] - Consecutive frames with motion: 2, max area size: 0.23514
viseron       | 2020-10-16T14:59:39.932533631Z [2020-10-16 22:59:39] [lib.nvr.amcrest.motion  ] [DEBUG   ] - Motion stopped
viseron       | 2020-10-16T14:59:39.932566428Z [2020-10-16 22:59:39] [lib.nvr.amcrest         ] [DEBUG   ] - Not recording, pausing object detector
viseron       | 2020-10-16T14:59:39.973947946Z [2020-10-16 22:59:39] [lib.nvr.amcrest.object  ] [DEBUG   ] - Objects: []

```

Volume:
![image](https://user-images.githubusercontent.com/7984567/96274699-69265c00-1003-11eb-8539-5df31f1cf0d5.png)

I have studied the configuration but cannot get this to work at all, what am I missing?

**Comment by roflcoopter** [comment]
From the log output it seems to stop scanning for objects because there is not enough motion.

Can you try to set ’’’trigger_detector: false’’’, and remove max/min height for the label and see if you get any detections?

**Comment by danobot** [comment]
```
object_detection:
  type: darknet
  interval: 6
  labels:
    - label: car
      confidence: 0.5
    - label: person
      confidence: 0.5
    - label: truck
      confidence: 0.8  
post_processors:
  face_recognition:
    type: dlib
    expire_after: 10
  logging:
    level: debug  
logging:
  level: debug
```


Logs
```
WARNING: Some networks were defined but are not used by any service: public
Attaching to viseron
viseron       | 2020-10-17T08:27:20.117373633Z [2020-10-17 16:27:20] [root                    ] [INFO    ] - -------------------------------------------
viseron       | 2020-10-17T08:27:20.117404984Z [2020-10-17 16:27:20] [root                    ] [INFO    ] - Initializing...
viseron       | 2020-10-17T08:27:20.117462640Z [2020-10-17 16:27:20] [root                    ] [DEBUG   ] - Starting cleanup scheduler
viseron       | 2020-10-17T08:27:20.218283783Z [2020-10-17 16:27:20] [root                    ] [DEBUG   ] - Running initial cleanup
viseron       | 2020-10-17T08:27:20.218310491Z [2020-10-17 16:27:20] [lib.cleanup             ] [DEBUG   ] - Running cleanup
viseron       | 2020-10-17T08:27:20.228379536Z [2020-10-17 16:27:20] [lib.detector            ] [DEBUG   ] - Initializing object detector darknet
viseron       | 2020-10-17T08:27:20.938562204Z [2020-10-17 16:27:20] [lib.detector            ] [DEBUG   ] - Object detector initialized
viseron       | 2020-10-17T08:27:20.938804606Z [2020-10-17 16:27:20] [lib.post_processors     ] [DEBUG   ] - Initializing post processor face_recognition
viseron       | 2020-10-17T08:27:22.857389188Z [2020-10-17 16:27:22] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Initializing dlib
viseron       | 2020-10-17T08:27:22.857410389Z [2020-10-17 16:27:22] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Training faces...
viseron       | 2020-10-17T08:27:22.857609141Z [2020-10-17 16:27:22] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Training face daniel
viseron       | 2020-10-17T08:27:24.069699742Z [2020-10-17 16:27:24] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - Training complete
viseron       | 2020-10-17T08:27:24.069776254Z [2020-10-17 16:27:24] [lib.post_processors.face_recognition.dlib] [DEBUG   ] - dlib initialized
viseron       | 2020-10-17T08:27:24.070156824Z [2020-10-17 16:27:24] [lib.post_processors     ] [DEBUG   ] - Post processor face_recognition initialized
viseron       | 2020-10-17T08:27:24.070247590Z [2020-10-17 16:27:24] [root                    ] [INFO    ] - Initializing NVR threads
viseron       | 2020-10-17T08:27:24.070584511Z [2020-10-17 16:27:24] [lib.nvr.amcrest         ] [DEBUG   ] - Initializing NVR thread
viseron       | 2020-10-17T08:27:24.070839980Z [2020-10-17 16:27:24] [lib.camera.amcrest      ] [DEBUG   ] - Initializing ffmpeg RTSP pipe
viseron       | 2020-10-17T08:27:24.070937293Z [2020-10-17 16:27:24] [lib.camera.amcrest      ] [DEBUG   ] - Getting stream information for rtsp://admin:danielx95@10.1.1.9:554/cam/realmonitor?channel=1&subtype=0
viseron       | 2020-10-17T08:27:30.171409326Z [2020-10-17 16:27:30] [lib.camera.amcrest      ] [DEBUG   ] - Resolution: 1920x1080 @ 20.0 FPS
viseron       | 2020-10-17T08:27:30.171589522Z [2020-10-17 16:27:30] [lib.camera.amcrest      ] [DEBUG   ] - FFMPEG decoder command: ffmpeg -hide_banner -loglevel fatal -avoid_negative_ts make_zero -fflags nobuffer -flags low_delay -strict experimental -fflags +genpts -stimeout 5000000 -use_wallclock_as_timestamps 1 -vsync 0 -rtsp_transport tcp -i rtsp://admin:danielx95@10.1.1.9:554/cam/realmonitor?channel=1&subtype=0 -f rawvideo -pix_fmt nv12 pipe:1
viseron       | 2020-10-17T08:27:30.171840969Z [2020-10-17 16:27:30] [lib.motion.amcrest      ] [DEBUG   ] - Initializing motion detector
viseron       | 2020-10-17T08:27:30.171904698Z [2020-10-17 16:27:30] [lib.motion.amcrest      ] [DEBUG   ] - Motion detector initialized
[2020-10-17 16:27:30] [lib.camera.amcrest] [DEBUG   ] - Starting decoder thread, message repeated 2 times
viseron       | 2020-10-17T08:27:30.172774601Z [2020-10-17 16:27:30] [lib.nvr.amcrest         ] [DEBUG   ] - Starting camera
viseron       | 2020-10-17T08:27:30.172961728Z [2020-10-17 16:27:30] [lib.camera.amcrest      ] [DEBUG   ] - Starting capture thread
viseron       | 2020-10-17T08:27:30.173250684Z [2020-10-17 16:27:30] [lib.recorder.amcrest    ] [DEBUG   ] - Initializing ffmpeg recorder
viseron       | 2020-10-17T08:27:30.173355706Z [2020-10-17 16:27:30] [lib.camera.amcrest      ] [DEBUG   ] - Performing a sanity check on the ffmpeg command
viseron       | 2020-10-17T08:27:30.173503610Z [2020-10-17 16:27:30] [lib.recorder.amcrest    ] [DEBUG   ] - FFMPEG encoder command: ffmpeg -hide_banner -loglevel error -f rawvideo -pix_fmt nv12 -s:v <width>x<height> -r <fps> -i pipe:0 -y <file>
viseron       | 2020-10-17T08:27:30.173584957Z [2020-10-17 16:27:30] [lib.nvr.amcrest         ] [DEBUG   ] - NVR thread initialized
viseron       | 2020-10-17T08:27:30.173804776Z [2020-10-17 16:27:30] [lib.nvr.amcrest         ] [DEBUG   ] - Waiting for first frame
viseron       | 2020-10-17T08:27:30.173905980Z [2020-10-17 16:27:30] [root                    ] [INFO    ] - Initialization complete
viseron       | 2020-10-17T08:28:08.776198444Z [2020-10-17 16:28:08] [lib.camera.amcrest      ] [DEBUG   ] - Running object detection at 6.0s interval, every 120 frame(s)
viseron       | 2020-10-17T08:28:08.776224180Z [2020-10-17 16:28:08] [lib.camera.amcrest      ] [DEBUG   ] - Running motion detection at 0.5s interval, every 10 frame(s)
viseron       | 2020-10-17T08:28:47.298021967Z [2020-10-17 16:28:47] [lib.nvr.amcrest         ] [DEBUG   ] - First frame received
viseron       | 2020-10-17T08:28:48.128489722Z Exception in thread Thread-3:
viseron       | 2020-10-17T08:28:48.128513639Z Traceback (most recent call last):
viseron       | 2020-10-17T08:28:48.128517628Z   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
viseron       | 2020-10-17T08:28:48.128520829Z     self.run()
viseron       | 2020-10-17T08:28:48.128530429Z   File "/src/viseron/lib/nvr.py", line 506, in run
viseron       | 2020-10-17T08:28:48.128534836Z     self.filter_fov(processed_object_frame)
viseron       | 2020-10-17T08:28:48.128537456Z   File "/src/viseron/lib/nvr.py", line 383, in filter_fov
viseron       | 2020-10-17T08:28:48.128540170Z     self.labels_in_fov = labels_in_fov
viseron       | 2020-10-17T08:28:48.128543109Z   File "/src/viseron/lib/nvr.py", line 412, in labels_in_fov
viseron       | 2020-10-17T08:28:48.128546035Z     self._mqtt.devices,
viseron       | 2020-10-17T08:28:48.128548534Z   File "/src/viseron/lib/helpers.py", line 256, in report_labels
viseron       | 2020-10-17T08:28:48.128551165Z     mqtt_devices[label].publish(True, attributes)
viseron       | 2020-10-17T08:28:48.128553760Z KeyError: 'car'
viseron       | 2020-10-17T08:28:48.128556352Z 
viseron       | 2020-10-17T08:28:48.128637585Z [2020-10-17 16:28:48] [root                    ] [INFO    ] - Exiting
```
I added `car` to the object detection because the motion detection seemed to trigger every time a car drove past my house. Even though `car` is definitely a trained model in darknet, it created the above error. (validated using `docker exec -it viseron cat /detectors/models/darknet/coco.names`)
