### ISSUE TITLE
Post processing config causing non-start?

### ISSUE THREAD

**Issue by sblfc** [roflcoopter/viseron#65]
Hello,

My config normally works however when I add:

```
post_processors:
  face_recognition:
    type: dlib
    expire_after: 10
    model: hog
    face_recognition_path: /config/face_recognition
  logging:
    level: debug
```

I crash at 

[2020-10-20 23:23:38] [root                    ] [INFO    ] - -------------------------------------------
[2020-10-20 23:23:38] [root                    ] [INFO    ] - Initializing...
[2020-10-20 23:23:38] [root                    ] [DEBUG   ] - Starting cleanup scheduler
[2020-10-20 23:23:38] [root                    ] [DEBUG   ] - Running initial cleanup
[2020-10-20 23:23:38] [lib.cleanup             ] [DEBUG   ] - Running cleanup
[2020-10-20 23:23:38] [lib.cleanup             ] [DEBUG   ] - Items in /recordings/2020-10-20: 1
[2020-10-20 23:23:38] [lib.mqtt                ] [INFO    ] - Initializing MQTT connection
[2020-10-20 23:23:38] [lib.detector            ] [DEBUG   ] - Initializing object detector edgetpu
[2020-10-20 23:23:42] [lib.detectors.edgetpu   ] [DEBUG   ] - Using USB EdgeTPU
[2020-10-20 23:23:42] [lib.detector            ] [DEBUG   ] - Object detector initialized
[2020-10-20 23:23:42] [lib.post_processors     ] [DEBUG   ] - Initializing post processor face_recognition

Is there any way to get a log of why it's crashing or does anyone have any idea as to why?

My face files

config/face_recognition/faces/person1/0.jpg
config/face_recognition/faces/person1/1.jpg
config/face_recognition/faces/person1/2.jpg
...

Edit:
Full Config
```
 logging:
  level: debug
  
  
cameras:
  - name: Front door
    mqtt_name: viseron_front_door
    host: 192.168.1.171
    port: 8554
    username: root
    password: (willbechanged)
    path: /unicast
    width: 1920
    height: 1080
    fps: 6 
    motion_detection:
      interval: 1
      trigger_detector: true
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: pottedplant
          confidence: 0.9
      
object_detection:
  interval: 1
  type: edgetpu
  model_path: /detectors/models/edgetpu/model.tflite
  label_path: /detectors/models/edgetpu/labels.txt
  labels:
    - label: person
      confidence: 0.9
    - label: pottedplant
      confidence: 0.9
          
post_processors:
  logging:
    level: debug 
  face_recognition:
    type: dlib
   # expire_after: 10
   # model: hog
   # face_recognition_path: /config/face_recognition
  logging:
    level: debug 
```

**Comment by roflcoopter** [comment]
Is this the full log output? If it crashes i would expect a stacktrace.

Could you edit your post and wrap your full config in a codeblock just as you did with your ```post_processors:``` config?

**Comment by sblfc** [comment]
Hello,

I have done that, here is my full config that works perfectly : 
```
mqtt:
  broker: brokeripwashere
  port: portwashere
  username: mqttuserhere
  password: mqttpasswordhere
  
logging:
  level: debug
  
  
cameras:
  - name: Front door
    mqtt_name: viseron_front_door
    host: ipwashere
    port: portwashere
    username: userwashere
    password: passwashere
    path: pathwashere
    width: 1920
    height: 1080
    fps: 6 
    motion_detection:
      interval: 1
      trigger_detector: true
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: pottedplant
          confidence: 0.9
      
object_detection:
  interval: 1
  type: edgetpu
  model_path: /detectors/models/edgetpu/model.tflite
  label_path: /detectors/models/edgetpu/labels.txt
  labels:
    - label: person
      confidence: 0.9
    - label: pottedplant
      confidence: 0.9```

Here is my log that crashes : 

```
```
mqtt:
  broker: brokeripwashere
  port: portwashere
  username: mqttuserhere
  password: mqttpasswordhere
  
logging:
  level: debug
  
  
cameras:
  - name: Front door
    mqtt_name: viseron_front_door
    host: ipwashere
    port: portwashere
    username: userwashere
    password: passwashere
    path: pathwashere
    width: 1920
    height: 1080
    fps: 6 
    motion_detection:
      interval: 1
      trigger_detector: true
    object_detection:
      interval: 1
      labels:
        - label: person
          confidence: 0.9
        - label: pottedplant
          confidence: 0.9
      
object_detection:
  interval: 1
  type: edgetpu
  model_path: /detectors/models/edgetpu/model.tflite
  label_path: /detectors/models/edgetpu/labels.txt
  labels:
    - label: person
      confidence: 0.9
    - label: pottedplant
      confidence: 0.9
          
post_processors:
  face_recognition:
    type: dlib
    expire_after: 10
  logging:
    level: debug

Here is the output: 
```tensorflow@tensorflow:~$ sudo docker run --rm -v /home/tensorflow/roflcoopter/rec:/recordings -v /home/tensorflow/roflcoopter:/config -v /etc/localtime:/etc/localtime:ro -v /dev/bus/usb:/dev/bus/usb --privileged --name viseron roflcoopter/viseron:latest
[2020-10-21 10:03:54] [root                    ] [INFO    ] - -------------------------------------------
[2020-10-21 10:03:54] [root                    ] [INFO    ] - Initializing...
[2020-10-21 10:03:54] [root                    ] [DEBUG   ] - Starting cleanup scheduler
[2020-10-21 10:03:54] [root                    ] [DEBUG   ] - Running initial cleanup
[2020-10-21 10:03:54] [lib.cleanup             ] [DEBUG   ] - Running cleanup
[2020-10-21 10:03:54] [lib.cleanup             ] [DEBUG   ] - Items in /recordings/2020-10-20: 1
[2020-10-21 10:03:54] [lib.mqtt                ] [INFO    ] - Initializing MQTT connection
[2020-10-21 10:03:54] [lib.detector            ] [DEBUG   ] - Initializing object detector edgetpu
[2020-10-21 10:03:58] [lib.detectors.edgetpu   ] [DEBUG   ] - Using USB EdgeTPU
[2020-10-21 10:03:58] [lib.detector            ] [DEBUG   ] - Object detector initialized
[2020-10-21 10:03:58] [lib.post_processors     ] [DEBUG   ] - Initializing post processor face_recognition
tensorflow@tensorflow:~$

```

Please let me know if theres any more info you might need?

Thanks for your your time!
