### ISSUE TITLE
Stream URL doesnt parse correctly

### ISSUE THREAD

**Issue by humanusdeus** [roflcoopter/viseron#653]
Im unable to set up a rtsp stream with a simple configuration
```
ffmpeg:
  camera:
    test:
      name: camera10
      host: nas
      port: 8554
      path: stream-10
```
The docker logs throw the following errors, it seems that Viseron doesnt parse the URL string correctly and it skips the slash after the port number, I tried to write the path property several ways already appending the slash "/stream-10" but it does the same:
`viseron    | [2023-07-26 12:33:06] [ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - rtsp://nas:8554stream-10: Server returned 400 Bad Request`

`viseron    | [2023-07-26 12:33:06] [ERROR   ] [viseron.components] - Domain camera for component ffmpeg is not ready. Retrying in 70 seconds. Error: FFprobe could not connect to stream. Output: {'error': {'code': -808465656, 'string': 'Server returned 400 Bad Request'}}`
