### ISSUE TITLE
Failed to retrieve result for object_detector - Frame is 2.8047475814819336 seconds old. Discarding

### ISSUE THREAD

**Issue by vchrizz** [roflcoopter/viseron#686]
Hello,

after some time running viseron fine and everything seems to work nicely I noticed that I have to restart it every few days because it stops detecting (and recording on object detection).

Mostly the issue happens after about 2-3 days after (re)start of viseron. I tried to log everything to find the cause but am unsuccessful to find an obvious problem.

I thought, maybe it is because the connection to the camera was interrupted, but no, even if I interrupt the connection to the camera on purpose (after a restart of viseron), the connection is re-established again, so this seems not to be the issue.

What could be the reason, that it suddently stops detecting objects and seemingly runs in that loop not detecting objects anymore?

current configuration (commented lines removed):
```
ffmpeg:
  camera:
    camera_2:
      name: MyCam2
      host: 10.29.85.251
      port: 554
      path: /s0
      width: 1920
      height: 1080
      fps: 25
      codec: h264
      audio_codec: aac
      stream_format: rtsp
      ffprobe_loglevel: debug

darknet:
  object_detector:
    cameras:
      camera_2:
        fps: 1
        scan_on_motion_only: false
        labels:
          - label: person
            confidence: 0.7
            trigger_recorder: true

mog2:
  motion_detector:
    cameras:
      camera_2:
        fps: 1

nvr:
  camera_2:

edgetpu:
  object_detector:
    device: usb
    cameras:
      camera_2:
        fps: 5
        labels:
          - label: person
            confidence: 0.7
            trigger_recorder: true
          - label: bird
            confidence: 0.7
            trigger_recorder: true
          - label: door
            confidence: 0.7
            trigger_recorder: true
          - label: cell phone
            confidence: 0.7
            trigger_recorder: true
          - label: laptop
            confidence: 0.7
            trigger_recorder: true
  image_classification:
    device: cpu
    cameras:
      camera_2:
    labels:
      - person

logger:
  logs:
    viseron.components.ffmpeg: debug
    viseron.components.darknet: debug
    viseron.components.nvr: debug
    viseron.components.edgetpu: debug
```

log with last successfull recording - after that, the log shows only those failed and old frame messages for days, no matter if there is movement or not:
```
ESC[80DESC[1AESC[KESC[36m[2023-11-07 15:20:27] [DEBUG   ] [viseron.components.edgetpu.object_detector.camera_2] - Objects: [], message repeated 4 timesESC[0m
ESC[80DESC[1AESC[KESC[36m[2023-11-07 15:20:27] [DEBUG   ] [viseron.components.edgetpu.object_detector.camera_2] - Objects: [], message repeated 5 timesESC[0m
ESC[32m[2023-11-07 15:20:27] [INFO    ] [viseron.components.nvr.nvr.camera_2] - Stopping recording in: 0ESC[0m
ESC[32m[2023-11-07 15:20:27] [INFO    ] [viseron.components.ffmpeg.recorder.camera_2] - Stopping recorderESC[0m
ESC[36m[2023-11-07 15:20:27] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Pausing segment cleanupESC[0m
ESC[36m[2023-11-07 15:20:27] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Concatenating segmentsESC[0m
ESC[36m[2023-11-07 15:20:28] [DEBUG   ] [viseron.components.edgetpu.object_detector.camera_2] - Objects: []ESC[0m
ESC[36m[2023-11-07 15:20:28] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Not recording, pausing object detectorESC[0m
ESC[36m[2023-11-07 15:20:28] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - /segments/camera_2/20231107152025.mp4 is locked. Trying again in 1 secondESC[0m
ESC[80DESC[1AESC[KESC[36m[2023-11-07 15:20:29] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - /segments/camera_2/20231107152025.mp4 is locked. Trying again in 1 second, message repeated 2 timesESC[0m
ESC[36m[2023-11-07 15:20:32] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Segment information: {'20231107151925.mp4': {'start_time': 1699366765.0, 'end_time': 1699366770.035}, '20231107151945.mp4': {'start_time': 1699366785.0, 'end_time': 1699366789.998}, '20231107151955.mp4': {'start_time': 1699366795.0, 'end_time': 1699366799.998}, '20231107151940.mp4': {'start_time': 1699366780.0, 'end_time': 1699366784.999}, '20231107152015.mp4': {'start_time': 1699366815.0, 'end_time': 1699366819.998}, '20231107152005.mp4': {'start_time': 1699366805.0, 'end_time': 1699366809.995}, '20231107152025.mp4': {'start_time': 1699366825.0, 'end_time': 1699366829.998}, '20231107151930.mp4': {'start_time': 1699366770.0, 'end_time': 1699366774.992}, '20231107152010.mp4': {'start_time': 1699366810.0, 'end_time': 1699366814.999}, '20231107151950.mp4': {'start_time': 1699366790.0, 'end_time': 1699366795.004}, '20231107151915.mp4': {'start_time': 1699366755.0, 'end_time': 1699366759.949}, '20231107152000.mp4': {'start_time': 1699366800.0, 'end_time': 1699366804.998}, '20231107152020.mp4': {'start_time': 1699366820.0, 'end_time': 1699366824.996}, '20231107151935.mp4': {'start_time': 1699366775.0, 'end_time': 1699366779.998}, '20231107151920.mp4': {'start_time': 1699366760.0, 'end_time': 1699366764.998}}ESC[0m
ESC[36m[2023-11-07 15:20:32] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Start event: 1699366767.2882, segment: 20231107151925.mp4ESC[0m
ESC[36m[2023-11-07 15:20:32] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - End event: 1699366827.801433, segment: 20231107152025.mp4ESC[0m
ESC[36m[2023-11-07 15:20:32] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Concatenation command: ffmpeg -hide_banner -loglevel error -y -protocol_whitelist file,pipe -f concat -safe 0 -i - -c:v copy -c:a copy -movflags +faststart /recordings/camera_2/2023-11-07/15:19:32.mp4ESC[0m
ESC[36m[2023-11-07 15:20:32] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Segment script:
file 'file:/segments/camera_2/20231107151925.mp4'
inpoint 2
file 'file:/segments/camera_2/20231107151930.mp4'
file 'file:/segments/camera_2/20231107151935.mp4'
file 'file:/segments/camera_2/20231107151940.mp4'
file 'file:/segments/camera_2/20231107151945.mp4'
file 'file:/segments/camera_2/20231107151950.mp4'
file 'file:/segments/camera_2/20231107151955.mp4'
file 'file:/segments/camera_2/20231107152000.mp4'
file 'file:/segments/camera_2/20231107152005.mp4'
file 'file:/segments/camera_2/20231107152010.mp4'
file 'file:/segments/camera_2/20231107152015.mp4'
file 'file:/segments/camera_2/20231107152020.mp4'
file 'file:/segments/camera_2/20231107152025.mp4'
outpoint 2ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107151925.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107151930.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107151935.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107151940.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107151945.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107151950.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107151955.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107152000.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107152005.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107152010.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107152015.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Removing segment: 20231107152020.mp4ESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Segments concatenatedESC[0m
ESC[36m[2023-11-07 15:20:33] [DEBUG   ] [viseron.components.ffmpeg.recorder.camera_2] - Resuming segment cleanupESC[0m
ESC[36m[2023-11-07 15:20:53] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Starting object detectorESC[0m
ESC[31m[2023-11-07 15:20:57] [ERROR   ] [viseron.components.nvr.nvr.camera_2] - Failed to retrieve result for object_detectorESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.8047475814819336 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.6019608974456787 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.4003658294677734 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.1697137355804443 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.001023769378662 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.8022689819335938 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.6007075309753418 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.4089319705963135 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.1352176666259766 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:20:57] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.0092625617980957 seconds old. DiscardingESC[0m
ESC[31m[2023-11-07 15:21:00] [ERROR   ] [viseron.components.nvr.nvr.camera_2] - Failed to retrieve result for object_detectorESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 3.6135902404785156 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 3.4195125102996826 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 3.170807361602783 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.994887113571167 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.8197498321533203 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.6199915409088135 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.4186768531799316 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.155716896057129 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 2.0229897499084473 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.8272793292999268 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.6247384548187256 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.4283666610717773 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.1668827533721924 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:00] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 1.0335273742675781 seconds old. DiscardingESC[0m
ESC[31m[2023-11-07 15:21:03] [ERROR   ] [viseron.components.nvr.nvr.camera_2] - Failed to retrieve result for object_detectorESC[0m
ESC[36m[2023-11-07 15:21:03] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 3.6324892044067383 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:03] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 3.4340617656707764 seconds old. DiscardingESC[0m
ESC[36m[2023-11-07 15:21:03] [DEBUG   ] [viseron.components.nvr.nvr.camera_2] - Frame is 3.1824557781219482 seconds old. DiscardingESC[0m

```
