### ISSUE TITLE
Requested feature to use a `custom_model` per camera?

### ISSUE THREAD

**Issue by wjbridge** [roflcoopter/viseron#700]
First off, let me say that this opensouce project is amazing! This has streamlined my AI processing integration with HA a ton! I was experimenting with the Codeproject AI block. I have one camera that I want to detect a `cat` object and another camera that I want to detect a `postal package` so I can get a notification.

Using the default dataset `coco`, I can detect the `cat` as this model has been trained to do this. I separately trained a custom model to detect postal packages but I realized that you can't configure Viseron to use this model for a particular camera. I know I can train a custom model with all objects but I don't have the hw resources to do this easily. This led me to the question if it would be possible to map the `custom_model` to a camera for the `codeprojectai` component?

Proposed Config:

``` yaml
codeprojectai:
  host: !secret host
  port: !secret port
  object_detector:
    cameras:
      basement_cat:  # Attach detector to the configured camera_1 above
        fps: 1
        custom_model: ip_general
        scan_on_motion_only: true  # Scan for objects even when there is no motion
        zones:
          - name: cat_litter_box
            coordinates:
              - x: 134
                y: 504
              - x: 794
                y: 488
              - x: 794
                y: 1080
              - x: 134
                y: 1080
            labels:
              - label: cat
                confidence: 0.75
                trigger_recorder: true
      front_door_package:
        fps: 1
        custom_model: parcel
        scan_on_motion_only: true  # Scan for objects even when there is no motion
        labels:
          - label: parcel
            confidence: 0.7
            trigger_recorder: true
```
