### ISSUE TITLE
Happy with Viseron but...

### ISSUE THREAD

**Issue by BliXem1** [roflcoopter/viseron#710]
Is there a way to do add two detectors? I did use Codeproject.AI for objects and license plates. I don't want to lose the license plate function within Home Assistant, but the CPU load is too high at this moment. So I want to go back to Darknet for object detection but I don't want to lose the license plate because it will open the garagedoor for me when it detects my licenseplate.

Yes, there are other ways but I want to have it locally and not in the cloud.

**Comment by roflcoopter** [comment]
You can simply use `darknet` as the object detector and `codeprojectai` for the licenseplate, small config example:

```yaml
darknet:
  object_detector:
    cameras:
      camera_1:
        labels:
          - label: person
            confidence: 0.8
  ...

codeprojectai:
  ...
  license_plate_recognition:
    min_confidence: 0.4
    known_plates:
      - ASDFGH
    cameras:
      camera_1:
    labels:
      - person
```

Config example isnt complete but i think you get the point!
