### ISSUE TITLE
Help setup motion detection recording

### ISSUE THREAD

**Issue by smolattack** [roflcoopter/viseron#722]
I have no idea how NVRs work. I managed to get my camera to work in viseron but I don't know what I need to do to make it record on any kind of motion. I don't need any object detection. Cameras will be in a dark-ish loft and I'm just trying to see where rats are coming from.

The following config allows me to see a live feed from a camera but I see no recordings. Am I missing something?

```yml
ffmpeg:
  camera:
    bullet:  # This value has to be unique across all cameras
      name: bullet
      host: 172.16.200.201
      port: 554
      path: /media/video1
      fps: 25


mog2:
  motion_detector:
    cameras:
      bullet:  # Attach detector to the configured camera_2 above
        fps: 5


nvr:
  bullet: 
```

**Comment by roflcoopter** [comment]
By default motion does not trigger recordings. By using `trigger_recorder: true` you can accomplish this tho

```yaml
ffmpeg:
  camera:
    bullet:  # This value has to be unique across all cameras
      name: bullet
      host: 172.16.200.201
      port: 554
      path: /media/video1
      fps: 25


mog2:
  motion_detector:
    cameras:
      bullet:  # Attach detector to the configured camera_2 above
        fps: 5
        trigger_recorder: true


nvr:
  bullet: 
```

You might need to play around with `area` as well to make it more sensitive. You can find more info on this in the component docs: https://viseron.netlify.app/components-explorer/components/mog2
