### ISSUE TITLE
[3.0.0b3] Segments get moved through Tiers before being deleted

### ISSUE THREAD

**Issue by w-marco** [roflcoopter/viseron#742]
Hi!

I am using Viseron 3.0.0b3 with Storage Tiers. I have a RAM-Disk as a first tier (/cache) and then my NFS mount as the second tier (/viseron).
My Viseron is configured to only record when the Coral TPU detects certain objects, everything else is discarded.

This is my storage configuration:

```
storage:
  recorder:
    tiers:
      - path: /cache
        move_on_shutdown: true
        events:
          max_age:
            minutes: 10
      - path: /viseron
        move_on_shutdown: false
        events:
          max_age:
            days: 21
  snapshots:
    tiers:
      - path: /cache
        move_on_shutdown: true
        max_age:
          minutes: 10
      - path: /viseron
        move_on_shutdown: false
        max_age:
          days: 21
```

Segments from the camera are created as .m4s files in /cache/segments/camera/abc.m4s. But then, they're not directly deleted from /cache, but they move to /viseron and are then deleted immediately after. This unnecessarily creates write operations on the NFS. Can't segments that do not end up in a recording be deleted directly at Tier 0 instead of moving through the tiers and then being deleted?
