### ISSUE TITLE
Error calling deepstack

### ISSUE THREAD

**Issue by tdashmike** [roflcoopter/viseron#783]
I can't figure out why it can't connect to deepstack. If I change the ip to a wrong one it will say something different so it looks like it's connecting but there are errors. I have also tried disabling the API key and it is the same. The website for deepstack loads when I go to the IP.

**Error:**
`[ERROR   ] [viseron.components.deepstack.object_detector] - Error calling deepstack: Timeout connecting to Deepstack, the current timeout is 10 seconds, try increasing this value`

**Compose:**
```
services:
  deepstack:
    container_name: deepstack
    restart: unless-stopped
    image: deepquestai/deepstack
    volumes:
      - "/storage/Deepstack:/datastore"
    ports:
      - "5500:5000"
    environment:
      - API-KEY=2345
      - VISION-DETECTION=True
      - VISION-FACE=True
```

**Config:**
```
deepstack:
  host: 192.168.1.5
  port: 5500
  api_key: 2345
  object_detector:
#    dnn_backend: openvino
#    dnn_target: opencl
    cameras:
      frontdoor:
        scan_on_motion_only: true
        fps: 1
        max_frame_age: 3
        labels:
          - label: person
            confidence: 0.7
            trigger_recorder: true
          - label: cat
            confidence: 0.7
            trigger_recorder: true
          - label: dog
            confidence: 0.7
            trigger_recorder: true
```
