### ISSUE TITLE
Black Record file

### ISSUE THREAD

**Issue by lio00lio** [roflcoopter/viseron#832]
Hi all,

I just implemented Viseron on my system. I use casaOS for the hostOS (Debian 12).

I have 5 cameras configured but all records files are completely black.

Config:
```
ffmpeg:
  camera:
    camera_1:
        name: camera_1
        host: HostIP
        port: 554
        path: /Preview_01_main
        fps: 20
        username: username
        password: password
        substream:
            port: 554
            path: /Preview_01_sub
            fps: 10

    camera_2:
        name: camera_2
        host: HostIP
        port: 554
        path: /Preview_01_main
        fps: 20
        username: username
        password: password
        substream:
            port: 554
            path: /Preview_01_sub
            fps: 10

    camera_3:
        name: camera_3
        host: HostIP
        port: 554
        path: /Preview_01_main
        fps: 20
        username: username
        password: password
        substream:
            port: 554
            path: /Preview_01_sub
            fps: 10

    camera_4:
        name: camera_4
        host: HostIP
        port: 554
        path: /Preview_01_main
        fps: 20
        username: username
        password: password
        substream:
            port: 554
            path: /Preview_01_sub
            fps: 10

    camera_5:
        name: camera_5
        host: HostIP
        port: 554
        path: /Preview_01_main
        fps: 20
        username: username
        password: password
        substream:
            port: 554
            path: /Preview_01_sub
            fps: 10


mog2:
  motion_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_2 above
        fps: 10
        trigger_recorder: true
      camera_2:  # Attach detector to the configured camera_2 above
        fps: 10
        trigger_recorder: true
      camera_3:  # Attach detector to the configured camera_2 above
        fps: 10
        trigger_recorder: true
      camera_4:  # Attach detector to the configured camera_2 above
        fps: 10
        trigger_recorder: true
      camera_5:  # Attach detector to the configured camera_2 above
        fps: 10
        trigger_recorder: true

nvr:
  camera_1:  # Run NVR for camera_1
  camera_2:  # Run NVR for camera_2
  camera_3:  # Run NVR for camera_1
  camera_4:  # Run NVR for camera_2
  camera_5:  # Run NVR for camera_1
```

The live view is ok, I can see the correct camera immage
