### ISSUE TITLE
ffmpeg "recorder" and mog2

### ISSUE THREAD

**Issue by superkekko** [roflcoopter/viseron#833]
Hi,

I've setup the "recorder" feature in the ffmpeg part but I don't understand how these are merged with the mog2 part

ffmpeg:
`      
recorder:
        lookback: 10
        idle_timeout: 10
        retain: 3
`
mog2:
`
fps: 1
        trigger_recorder: true
        recorder_keepalive: true
        area: 0
        threshold: 0
        learning_rate: -1
`

Do I need both?

**Comment by roflcoopter** [comment]
Can you paste your config according to [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) so it preserves the formatting?

They are linked together by the camera identifier:
```yaml
ffmpeg:
  camera:
    camera_1: This is the camera identifier

mog2:
  motion_detector:
    cameras:
      camera_1: Same identifier as above
```
