### ISSUE TITLE
CodeprojectAI оbject mask not working

### ISSUE THREAD

**Issue by bsyomov** [roflcoopter/viseron#859]
Seems like CodeprojectAI component оbject mask not working:

![detection_of_masked_object](https://github.com/user-attachments/assets/69a0bc30-2def-4f36-801f-f6dbd7318eef)

Viseron image: latest roflcoopter/amd64-viseron:dev 
CodeprojectAI image: codeproject/ai-server:cuda12_2-2.9.5

Camera object detector config:
```
      bssdc_cam1:
        scan_on_motion_only: true
        fps: 3
        log_all_objects: true
        labels:
          - label: person
            confidence: 0.80
            trigger_recorder: true
          - label: cat
            confidence: 0.75
            trigger_recorder: true
          - label: dog
            confidence: 0.75
            trigger_recorder: true
          - label: bird
            confidence: 0.75
            trigger_recorder: true
          - label: car
            confidence: 0.75
            trigger_recorder: true
          - label: truck
            confidence: 0.75
            trigger_recorder: true
        mask:
          - coordinates:
            - x: 742
              y: 156
            - x: 847 
              y: 153
            - x: 896
              y: 164
            - x: 929
              y: 193
            - x: 952
              y: 192
            - x: 991
              y: 205
            - x: 1003
              y: 248
            - x: 968
              y: 288
            - x: 905
              y: 300
            - x: 751
              y: 312
```
