### ISSUE TITLE
Viseron can't get the RTSP stream from reolink camera

### ISSUE THREAD

**Issue by stiriak** [roflcoopter/viseron#889]
# The error
```
FFprobe could not connect to stream. Output: {'error': {'code': -5, 'string': 'Input/output error'}}
```
# The camera
Reolink P320 POE IP camera

# General config

My config file is:

```yaml
## Start by adding some cameras
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: FrontYard
      host: 192.168.50.20
      port: 554
      path: /h264Preview_01_main
      username: !secret camera_user
      password: !secret camera_pass
```
I have tried the path with and without the h254. When I try to connect from VLC with /h264Preview_01_main it works. So the camera's RTSP seems to be configured properly. 

# Details on the environment
I am running the docker container in a VM in Proxmox. The VM is connected to a VLAN. The camera is on the same VLAN as the VM. I have added a temporary allow all rule within the VLAN so there should be no firewall issues. I have tried connecting from another VLAN where I have allowed port 8888 to the VM so I can access the webui, as well as within the same VLAN with the same result.

I'm fairly certain that my network configuration is not the issue. 

# Information on the VM

CPU: 4 cores (in host mode)
RAM: 8gb
Network: virtual device with VLAN tagging enabled

I can connect to the VM via SSH just fine. 

# Docker log output

```
[ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - [tcp @ 0x5edb521080c0] Failed to resolve hostname admin: Temporary failure in name resolution

[ERROR   ] [viseron.components.ffmpeg.stream.camera_1] - rtsp://*****:*****@192.168.50.20:554/h264Preview_01_main: Input/output error

[ERROR   ] [viseron.components] - Domain camera for component ffmpeg is not ready. Retrying in 180 seconds. Error: FFprobe could not connect to stream. Output: {'error': {'code': -5, 'string': 'Input/output error'}}

[WARNING ] [viseron.components] - Domain nvr for component nvr with identifier camera_1 is still waiting for dependencies: ['domain: camera, identifier: camera_1']
```

**Comment by stiriak** [comment]
Never mind. I think I fixed the issue. The problem was improper formatting of my secrets file. I've been working on this for like 2 days and so I thought it was a bug. My bad.

**Comment by webhostsg** [comment]
I'm using Reolink Camera Doorbell (Battery) no issues.  My config  as follows:

```
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Reolink
      host: !secret doorbell_ip #!secret mqtt_host
      port: 554
      path: /Preview_01_main #/reolink_camera
      width: 2048
      height: 2048
      fps: 15
      username: !secret reolink_user
      password: !secret reolink_pwd
```

Follow the guide from here: https://support.reolink.com/hc/en-us/articles/360007010473-How-to-Live-View-Reolink-Cameras-via-VLC-Media-Player/

```
The RTSP URL should be:

Main Stream: rtsp://admin:password@ip_address/Preview_01_main

Sub Stream: rtsp://admin:password@ip_address/Preview_01_sub

Alternatively, you can also use this URL (Main Stream by default): rtsp://(user name):(password)@(ip address):554/

For example,

if your device IP address is 192.168.0.110 and the password is 111111, then your RTSP URL should be:

Main Stream: rtsp://admin:111111@192.168.0.110/Preview_01_main

Sub Stream:  rtsp://admin:111111@192.168.0.110/Preview_01_sub

Note: Do not use special characters for your password.
```
