### ISSUE TITLE
[FR] Save unknown faces

### ISSUE THREAD

**Issue by mihaiblaga89** [roflcoopter/viseron#90]
Do something similar to how ZoneMinder does, have a `unknown_faces` folder next to the `faces` folder where it can save all the faces that it doesn't recognise. This makes it easy to train your known faces (just move the unknown face to the known ones). All this enabled with the "save_unknown_faces: true" config param.

I'll try to take a stab at this when I have some free time and make a PR.

**Comment by roflcoopter** [comment]
Great idea!

**Comment by roflcoopter** [comment]
This is available in the ```roflcoopter/viseron:dev``` tag.
You can now set ```save_unknown_faces: true``` in your config and it will save all unknown faces in your faces folder.
Example:

```yaml
post_processors:
  face_recognition:
    type: dlib
    model: cnn
    expire_after: 10
    save_unknown_faces: true
```
