### ISSUE TITLE
No thumbnail file on disk

### ISSUE THREAD

**Issue by coyote1** [roflcoopter/viseron#91]
Hey,

i activated "save_to_disk" under recorder, but there isn't a thumbail (named: latest_thumbnail.jpg) file in recorder subdirectory. 

I have also activated "send_to_mqtt", this works fine.

```
  recorder:
  lookback: 10
  timeout: 10
  retain: 7
  folder: /recordings
  thumbnail:
    save_to_disk: true
    send_to_mqtt: true
```
Are there logs to see why it is not created.
