### ISSUE TITLE
Configuration question/issues

### ISSUE THREAD

**Issue by stonehencs** [roflcoopter/viseron#927]
Hello!

I would like to ask if it is possible to do a separate motion detection and if motion is detected then run the object detector if it finds an object on it then save the recording? 

But I would like it so that if it finds any object, I don't necessarily want to specify all acceptable objects, because anything can happen.

And could you please help me with this that I turned on "draw_motion" but it doesn't do anything. I set it as in the example config.

Thanks in advance!

My config:
```
 
ffmpeg:
  camera:
    camera_1:
      name: vigi_kamera_1
      host: !secret camera1_ip
      port: 554
      path: !secret camera1_path1
      username: !secret camera1_user
      password: !secret camera1_pswd
      fps: 25
      width: 2304
      height: 1296
      stream_format: rtsp
      mjpeg_streams:
        my_stream:
          width: 704
          height: 576
          draw_objects: true
        objects:
          draw_objects: true
          draw_zones: true
          draw_motion: true
          draw_motion_mask: true
          draw_object_mask: true
      substream:
        path: !secret camera1_path2
        port: 554
        stream_format: rtsp
        fps: 15
        width: 704
        height: 576
      recorder:
        lookback: 15 #esemény elött
        idle_timeout: 15 #esemény utan
        retain: 30  #meddig tarol nap


mog2:
  motion_detector:
    cameras:
      camera_1:
        recorder_keepalive: true
        #threshold: 8
        fps: 10
        #area: 0.009
        #history: 200
        #detect_shadows: true
        trigger_recorder: true
        width: 704
        height: 576

nvr:
  camera_1:
```

**Comment by roflcoopter** [comment]
The default behaviour if you configure both motion and object detection is that object detection only runs while there is active motion. It is controlled by the `scan_on_motion_only` config option.

Currently you cant search for all labels, you need to specify the ones of interest. Will add that to the to-do list!

Motion not being drawn could be a bug, looking into it

**Comment by stonehencs** [comment]
Thanks! I'll try it and if it doesn't work I'll get back to you.
Can I at least list it in the label? e.g.: label: cat, dog, person ....?

**Comment by roflcoopter** [comment]
Just did some testing with `draw_motion` and it works fine on my cameras.
Could you tell me a bit more what it is you are trying?



> Can I at least list it in the label? e.g.: label: cat, dog, person ....?

Sadly no, you need separate entries for each label:
```yaml
         labels:
           - label: person
             confidence: 0.7
             trigger_event_recording: true
           - label: car
             confidence: 0.6
             trigger_event_recording: true
           - label: vehicle
             confidence: 0.6
             trigger_event_recording: true
```
