### ISSUE TITLE
The /event_clips folder does not exist. Please mount it to the container.

### ISSUE THREAD

**Issue by akbarhabiby** [roflcoopter/viseron#929]
Hello, i just tried the new viseron image `roflcoopter/amd64-viseron:3.0.0` and the app wont start because i got an error `voluptuous.error.MultipleInvalid: The /event_clips folder does not exist. Please mount it to the container.`

Please help me, I am not sure what am I missing

Here i attach the screenshot of the error

![Image](https://github.com/user-attachments/assets/d55df165-a452-4d80-b3f4-7ab188ff3475)

also here the `docker-compose.yaml`

```
services:
  nvr:
    image: roflcoopter/amd64-viseron:3.0.0
    container_name: viseron
    shm_size: "1024mb"
    volumes:
      - ./data/segments:/segments \
      - ./data/snapshots:/snapshots \
      - ./data/thumbnails:/thumbnails \
      - ./data/event_clips:/event_clips \
      - ./data/config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8003:8888
    environment:
      - PUID=1000
      - PGID=1000
```

Thanks in advance for your answers!
