### ISSUE TITLE
The mask is not working for some reason

### ISSUE THREAD

**Issue by stonehencs** [roflcoopter/viseron#936]
Hi!

I have set the mask on one of the cameras which can see a little bit of the street and it filters out cars very well but if a bus or a bigger car passes by it detects it. Same thing with night mode. 
I wondered if I had set the mask to the substream and knew it was doing the motion detection on that and not the main stream. I'm correct, right?

Can anyone help me why?

Here's what the mask is covering in the picture:

![Image](https://github.com/user-attachments/assets/b58baf8d-7fb5-4c13-b619-761354add2e0)

the recorded video (it uses the main stream): https://drive.google.com/drive/folders/1w6BPS_XjG8EDk7NSzDim37lxj_gP29l4?usp=sharing

Config:
```
ffmpeg:
  camera:
    camera_1:
      name: vigi_kamera_1
      host: !secret camera1_ip
      port: 554
      path: !secret camera1_path1
      username: !secret camera1_user
      password: !secret camera1_pswd
      fps: 25
      width: 2304
      height: 1296
      stream_format: rtsp
      mjpeg_streams:
        my_stream:
          width: 704
          height: 576
          draw_objects: true
        objects:
          draw_objects: true
          draw_zones: true
          draw_motion: true
          draw_motion_mask: true
          draw_object_mask: true
      substream:
        path: !secret camera1_path2
        port: 554
        stream_format: rtsp
        fps: 15
        width: 704
        height: 576
      recorder:
        lookback: 15 #esemény elött
        idle_timeout: 15 #esemény utan
        retain: 30  #meddig tarol nap
    camera_2:
      name: vigi_kamera_2
      host: !secret camera2_ip
      port: 554
      path: !secret camera2_path1
      username: !secret camera2_user
      password: !secret camera2_pswd
      fps: 25
      width: 2304
      height: 1296
      stream_format: rtsp
      mjpeg_streams:
        my_stream:
          width: 704
          height: 576
          draw_objects: true
        objects:
          draw_objects: true
          draw_zones: true
          draw_motion: true
          draw_motion_mask: true
          draw_object_mask: true
      substream:
        path: !secret camera2_path2
        port: 554
        stream_format: rtsp
        fps: 15
        width: 704
        height: 576
      recorder:
        lookback: 15 #esemény elött
        idle_timeout: 15 #esemény utan
        retain: 30  #meddig tarol nap
mog2:
  motion_detector:
    cameras:
      camera_1:
        recorder_keepalive: true
        threshold: 10
        fps: 10
        area: 0.012
        #history: 200
        #detect_shadows: true
        trigger_recorder: true
        width: 704
        height: 576
      camera_2:
        recorder_keepalive: true
        trigger_recorder: true
        threshold: 10
        fps: 10
        area: 0.012
        width: 704
        height: 576
        mask:
          - coordinates:
              - x: 208
                y: 0
              - x: 704
                y: 0
              - x: 704
                y: 132
              - x: 587
                y: 154
              - x: 430
                y: 183
              - x: 273
                y: 183
              - x: 237
                y: 146
              - x: 211
                y: 50

nvr:
  camera_1:
  camera_2:
```
