### ISSUE TITLE
[FR] Add masks for facial recognition (dlib)

### ISSUE THREAD

**Issue by kennyboy55** [roflcoopter/viseron#937]
I am using dlib for facial recognition. This is not working great. My Doorbell camera has a window to the side in which reflections are visible. I masked this in the motion detection component. However, the facial recognition keeps finding faces in the window and never on the actual people. 

Is it possible to add a mask or zones to the facial recognition?

**Comment by roflcoopter** [comment]
Thats an oversight from my side, not possible atm, but shouldnt be hard to implement.
Will try to get it done during the coming week.

**Comment by roflcoopter** [comment]
Should be fixed now, you can pull the `dev` tag to try it out.

You specify it the same as any other mask (example is for codeprojectai but the same applies for dlib):
```yaml
codeprojectai:
  host: cpai
  port: 1234
  face_recognition:
    cameras:
      camera_one:
        mask:
          - coordinates:
              - x: 1800
                y: 0
              - x: 1919
                y: 0
              - x: 1919
                y: 1079
              - x: 1800
                y: 1079
```
