### ISSUE TITLE
Configuration error and missing saved files

### ISSUE THREAD

**Issue by stonehencs** [roflcoopter/viseron#945]
Hi!

I upgraded to the latest version which is viseron:latest (3.0.0 - 9865c8c) and configured the new storage component. 

However, when I specify the path I can't find the saved files anywhere on the server. I searched the entire system for .mp4 files but to no avail and it didn't save to the folder I specified. But it could just be that I set something wrong.

The other thing is that I didn't touch anything but the storage component in the config and I noticed that when it detects motion in the video it starts the video with the motion and not with the 15 second lookback. It's like the lookback is after the event not before. I tried to increase the lookback but the same problem persists. I looked at the logs but did not see anything suspicious.

Also, something must have happened to the database after the update because the previous videos are no longer shown but the files exist.

Video link: https://drive.google.com/drive/folders/1w6BPS_XjG8EDk7NSzDim37lxj_gP29l4?usp=sharing

docker-compose.yml: 
```
services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    shm_size: "4096mb"
    volumes:
      - ./rec/save:/recordings:rw
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - ./rec/segments:/segments:rw
      - ./rec/snapshots:/snapshots:rw
      - ./rec/thumbnails:/thumbnails:rw
      - ./rec/event_clips:/event_clips:rw
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
```

config.yml:

```
storage:
  recorder:
    tiers:
      - path: /recordings
        events:
          max_age:
            days: 730
  snapshots:
    tiers:
      - path: /snapshots
        max_age:
          days: 730

ffmpeg:
  camera:
    camera_1:
      name: vigi_kamera_1
      host: !secret camera1_ip
      port: 554
      path: !secret camera1_path1
      username: !secret camera1_user
      password: !secret camera1_pswd
      fps: 25
      width: 2304
      height: 1296
      stream_format: rtsp
      mjpeg_streams:
        my_stream:
          width: 704
          height: 576
          draw_objects: true
        objects:
          draw_objects: true
          draw_zones: true
          draw_motion: true
          draw_motion_mask: true
          draw_object_mask: true
      substream:
        path: !secret camera1_path2
        port: 554
        stream_format: rtsp
        fps: 15
        width: 704
        height: 576
      recorder:
        lookback: 15
        idle_timeout: 15 
    camera_2:
      name: vigi_kamera_2
      host: !secret camera2_ip
      port: 554
      path: !secret camera2_path1
      username: !secret camera2_user
      password: !secret camera2_pswd
      fps: 25
      width: 2304
      height: 1296
      stream_format: rtsp
      mjpeg_streams:
        my_stream:
          width: 704
          height: 576
          draw_objects: true
        objects:
          draw_objects: true
          draw_zones: true
          draw_motion: true
          draw_motion_mask: true
          draw_object_mask: true
      substream:
        path: !secret camera2_path2
        port: 554
        stream_format: rtsp
        fps: 15
        width: 704
        height: 576
      recorder:
        lookback: 15
        idle_timeout: 15
mog2:
  motion_detector:
    cameras:
      camera_1:
        recorder_keepalive: true
        threshold: 10
        fps: 10
        area: 0.012
        trigger_event_recording: true
        width: 704
        height: 576
      camera_2:
        recorder_keepalive: true
        trigger_event_recording: true
        threshold: 10
        fps: 10
        area: 0.012
        width: 704
        height: 576


nvr:
  camera_1:
  camera_2:
```
