### ISSUE TITLE
Webui cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by flazzarini** [roflcoopter/viseron#948]
I've noticed that I am unable to use the Events view in the web browser for a given camera, the others are working fine. Here is the error I am getting in the webgui

![Image](https://github.com/user-attachments/assets/3c2008b5-079e-4b62-8b5d-d4ca2795a3ec)

The related configuration file is here.

```
## Start by adding some cameras
ffmpeg:
  camera:
    bruno_cam:  # This value has to be unique across all cameras
      name: Bruno Cam
      host: 192.168.0.1
      port: 8554
      path: /bruno_cam
      protocol: rtsp
      stream_format: rtsp
      pix_fmt: yuv420p
      fps: 20
      ffprobe_loglevel: info
      recorder:
        continuous_recording: true
        continuous:
          max_size:
            gb: 10
        events:
          max_age:
            days: 14

    cam_1:  # This value has to be unique across all cameras
      name: Cam 1
      host: 192.168.0.2
      port: 554
      path: /Preview_01_sub
      username: "stream"
      password: "foobar"
      protocol: rtsp
      stream_format: rtsp
      pix_fmt: yuv420p
      fps: 30
      ffprobe_loglevel: info
      recorder:
        continuous_recording: true
        continuous:
          max_size:
            gb: 10
        events:
          max_age:
            days: 14

## To tie everything together we need to configure one more component.
nvr:
  bruno_cam:  # Run NVR
  cam_1:   # Run NVR

# Now you can restart Viseron and you should be good to go!
```

Not sure if is a bug in my configuration file, or if is actually a bug in the WebUI
