### ISSUE TITLE
Notification Not Working Via Telegram

### ISSUE THREAD

**Issue by dustpannn** [roflcoopter/viseron#950]
I am not receiving telegram notifications here is my .yaml & .yml to help identify any issues. I got my bot token and then the chat id from https://api.telegram.org/bot[mybotstokenhere]/getUpdates so that proves those values are good what else am I missing?

When I start the docker compose I do get this error.

[ERROR   ] [viseron.components] - Failed to load component notifications: No module named 'viseron.components.notifications'

docker compose file

```
services:
  viseron:
    image: roflcoopter/viseron:latest
    container_name: viseron
    shm_size: "1024mb"
    volumes:
      - ./segments:/segments
      - ./snapshots:/snapshots
      - ./thumbnails:/thumbnails
      - ./event_clips:/event_clips
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8888:8888
    environment:
      - PUID=1000
      - PGID=1000
```
.yaml
```
# Thanks for trying out Viseron!
# This is a small walkthrough of the configuration to get you started.
# There are far more components and options available than what is listed here.
# See the documentation for the full list of configuration options.

## Start by adding some cameras
---
ffmpeg:
  camera:
    camera_1:  # This value has to be unique across all cameras
      name: Front door
      host: 192.168.XX.XX
      port: xxx
      path: /Preview_01_main
      username: xxxx
      password: xxxxx
      fps: 30

    #camera_2:  # This value has to be unique across all cameras
     # name: <camera friendly name>
      #host: <ip address or hostname of camera>
      #port: <port the camera listens on>
      #path: <URL path to the stream>
      #username: <if auth is enabled>
      #password: <if auth is enabled>


## Then add an object detector
darknet:
  object_detector:
    cameras:
      camera_1:  # Attach detector to the configured camera_1 above
        fps: 30
        scan_on_motion_only: false  # Scan for objects even when there is no motion
        labels:
          - label: person
            confidence: 0.75
            trigger_event_recording: true
          - label: dog
            confidence: 0.60
            trigger_event_recording: true
          - label: car
            confidence: 0.75
            trigger_event_recording: true
          - label: cat
            confidence: 0.75
            trigger_event_recording: true
          - label: truck
            confidence: 0.50
            trigger_event_recording: true
          - label: bus
            confidence: 0.50
            trigger_event_recording: true
          - label: motorbike
            confidence: 0.50
            trigger_event_recording: true

      #camera_2:  # Attach detector to the configured camera_2 above
       # fps: 5
        #labels:
         # - label: person
          #  confidence: 0.75
           # trigger_event_recording: true


## You can also use motion detection
mog2:
  motion_detector:
    cameras:
      camera_1:
        fps: 30
      #camera_2:  # Attach detector to the configured camera_2 above
       # fps: 5


## To tie everything together we need to configure one more component.
nvr:
  camera_1:  # Run NVR for camera_1
#  camera_2:  # Run NVR for camera_2
notifications:
  telegram:
  telegram_bot_token: xxxxxxxxxx:xxxxxx-xxxxxxxxxxx_xxxxxxxxxxxxxxx
  telegram_chat_ids: [xxxxxxxxxx]
  detection_label: 
    - person
    - car
    - truck
    - dog
  send_detection_thumbnail: true
  send_detection_video: true
  send_detection_message: true
  cameras:
    camera_1:
# Now you can restart Viseron and you should be good to go!
#
#
#

```
