### ISSUE TITLE
Drawtext only working for the substream

### ISSUE THREAD

**Issue by aguinaldoabbj** [roflcoopter/viseron#951]
Hello,

I have some problems with cameras eventually loosing their clock (NTP setting getting switched to “manual” by itself). So I found very convenient the possibility of drawing the server time to the video.

The issue is that the drawing is working only for the substream (live view). The recorded files, obtained from the main stream, aren't receiving the time stamp.

```
ffmpeg:
  camera:
    b01:  # This value has to be unique across all cameras (lowercase)
      name: "Camera B01"
      host: CameraB01.example.com
      port: 554
      path: /Streaming/Channels/101/
      username: admin
      password: "XXXXXXXXX"
      fps: 15
      video_filters:
        - drawtext=text='Server\ Time\:\ %{localtime}':x=5:y=h-th-5:fontcolor=LightGrey:box=1:boxcolor=0x00000000@1:fontsize=12
      substream:
        path: /Streaming/Channels/102/
        port: 554
        fps: 15
```
What could I be doing wrong?

**Comment by roflcoopter** [comment]
It might be a bit confusing, but the `video_filters` you have specified is applied to the input stream, which is then later decoded and processed by Viseron. As written in the docs : _A list of FFmpeg filter arguments. These filters are applied before Viseron receives the image for processing._ 

I think its a bug tho that the `video_filters` specified on the main stream bleeds through to the substream.

However, to get the recorded files to also have the filter, you should use `video_filters` under `recorder`.
```yaml
ffmpeg:
  camera:
    b01:  # This value has to be unique across all cameras (lowercase)
      name: "Camera B01"
      host: CameraB01.example.com
      port: 554
      path: /Streaming/Channels/101/
      username: admin
      password: "XXXXXXXXX"
      fps: 15
      video_filters:
        - drawtext=text='Server\ Time\:\ %{localtime}':x=5:y=h-th-5:fontcolor=LightGrey:box=1:boxcolor=0x00000000@1:fontsize=12
      substream:
        path: /Streaming/Channels/102/
        port: 554
        fps: 15
      recorder:
        codec: h264
        video_filters:
          - drawtext=text='Server\ Time\:\ %{localtime}':x=5:y=h-th-5:fontcolor=LightGrey:box=1:boxcolor=0x00000000@1:fontsize=12

```

Note that you need to set `codec` as well since the files have to be re-encoded

Will update the instructions in the docs
