### ISSUE TITLE
DB is  not updated

### ISSUE THREAD

**Issue by DevFares** [roflcoopter/viseron#958]
when you use the storage component , for example 

```

storage:
  recorder:
    tiers:
      # Storing 128 MB of segments in RAM disk
      - path: /tmp/viseron_tier1
        move_on_shutdown: true
        events:
          max_size:
            mb :  128
          max_age:
            minutes: 5
        check_interval:
          minutes: 2
        

      - path: /recordings
        poll: true
        events:
          max_size:
            gb: 100

```

segments **gets saved** in memory and then they **get moved**  to disk , but the **PostgreSQL DB** doesn't **get updated** about those segments/thumbnails path after they get moved , so the Viseron  website shows them as " Missing" . 

Another note please advice Viseron users who use HDD devices as their storage device to use **RAM disks** instead and then move files to HDD , its 1000% **faster** for me , specially for object detection , i think its because the object detector is reading   data from disk when trying to detect an object , which takes longer time . and maybe RAM disk  is faster than some SSDs too .

and finally i like your project . keep up the good work :)
